// Punto d'ingresso del dominio per extension host, webview e test. Non conosce
// né `apparato` né il DOM, così `node --test` lo esegue così com'è.

export * from './models.js'
// Il lessico esce come spazio di nomi: scorciatoie corte come `il`, `i`, `un`,
// `del` sciolte nel barile rischiano omonimi (`lessico.corto(lessico.PIF)`).
export * as lessico from './lexicon.js'
export * from './text.js'
export * from './lists.js'
export * from './csv.js'
export * from './identifiers.js'
export * from './dates.js'
export * from './years.js'
export * from './calculations.js'
export * from './factories.js'
export * from './communications.js'
export * from './mailbox.js'
export * from './importing.js'
export * from './courses.js'
export * from './locations.js'
export * from './compositions.js'
export * from './automation.js'
export * from './timetable.js'
export * from './breaks.js'
export * from './upgrades.js'
export * from './calendar.js'
export * from './calendarIcs.js'
export * from './calendarLinks.js'
export * from './calendarRules.js'
export * from './validation.js'
export * from './normalization.js'
export * from './integrity.js'
export * from './repairs.js'
export * from './deletions.js'
export * from './dashboard.js'
export * from './reminders.js'
export * from './birthdays.js'
export * from './addresses.js'
export * from './persistence.js'
export * from './phones.js'
export * from './contacts.js'
export * from './tray.js'
export * from './todo.js'
export * from './activities.js'
export * from './assignments.js'
export * from './check.js'
export * from './absences.js'
export * from './sorting.js'
export * from './courseMatrix.js'
export * from './observations.js'
export * from './orphans.js'
export * from './retakes.js'
export * from './alerts.js'
export * from './returns.js'
export * from './reports.js'
export * from './reportData.js'
export * from './letterhead.js'
export * from './templateCatalog.js'
export * from './templateCheck.js'
export * from './projection.js'
export * from './map.js'
export * from './schoolCalendar.js'
