// Punto d'ingresso unico del dominio: quello che importano l'extension host, il
// webview e i test. Il dominio non conosce né `apparato` né il DOM, ed è per
// questo che `node --test` lo può eseguire così com'è.

export * from './models.js'
// Il lessico esce come spazio di nomi e non a nomi sciolti: le sue scorciatoie
// si chiamano `il`, `i`, `un`, `del`, e a nomi così corti sparsi nel barile
// prima o poi qualcuno ne aggiunge uno uguale. Chi importa dal dominio scrive
// `lessico.corto(lessico.PIF)`; chi sta dentro l'applicazione importa il file
// e li usa nudi, dove il contesto li spiega.
export * as lessico from './lexicon.js'
export * from './text.js'
export * from './lists.js'
export * from './csv.js'
export * from './identifiers.js'
export * from './dates.js'
export * from './years.js'
export * from './calculations.js'
export * from './factories.js'
export * from './communications.js'
export * from './mailbox.js'
export * from './importing.js'
export * from './courses.js'
export * from './locations.js'
export * from './compositions.js'
export * from './automation.js'
export * from './timetable.js'
export * from './validation.js'
export * from './repairs.js'
export * from './deletions.js'
export * from './dashboard.js'
export * from './reminders.js'
export * from './birthdays.js'
export * from './addresses.js'
export * from './persistence.js'
export * from './phones.js'
export * from './contacts.js'
export * from './tray.js'
export * from './agenda.js'
export * from './agendaMonth.js'
export * from './agendaPending.js'
export * from './agendaLesson.js'
export * from './todo.js'
export * from './activities.js'
export * from './assignments.js'
export * from './absences.js'
export * from './sorting.js'
export * from './courseMatrix.js'
export * from './observations.js'
export * from './orphans.js'
export * from './retakes.js'
export * from './alerts.js'
export * from './returns.js'
export * from './reports.js'
export * from './reportData.js'
export * from './templateCatalog.js'
export * from './templateCheck.js'
export * from './projection.js'
export * from './map.js'
