// Le parole di tutti: pulsanti ed etichette che ogni pagina dice allo stesso
// modo («Salva», non «Registra» nella finestra accanto). Solo parole sole; una
// frase che ne contiene una sta nel catalogo di chi la dice.
//
// Un catalogo che ne ricopia una (stesse quattro lingue) fa fallire
// `tests/i18n/words.test.mjs`: si usa `parole().x`. Un omonimo (stesso
// italiano, altra traduzione) va dichiarato nella lista della prova, col
// perché. Le pagine native (`shell/pages/`) importano questo file: deve
// importare soltanto `src/i18n/`.

import { catalogo } from '../i18n/index.js'

const it = {
  salva: 'Salva',
  annulla: 'Annulla',
  chiudi: 'Chiudi',
  elimina: 'Elimina',
  modifica: 'Modifica',
  aggiungi: 'Aggiungi',
  apri: 'Apri',
  conferma: 'Conferma',
  si: 'Sì',
  no: 'No',
  ok: 'OK',
  indietro: 'Indietro',
  avanti: 'Avanti',
  cerca: 'Cerca',
  filtra: 'Filtra…',
  tutti: 'Tutti',
  nessuno: 'Nessuno',
  copia: 'Copia',
  incolla: 'Incolla',
  stampa: 'Stampa',
  esporta: 'Esporta',
  importa: 'Importa',
  sfoglia: 'Sfoglia…',
  riprova: 'Riprova',
  continua: 'Continua',
  fatto: 'Fatto',
  mostra: 'Mostra',
  nascondi: 'Nascondi',
  rinomina: 'Rinomina',
  duplica: 'Duplica',
  sposta: 'Sposta',
  scegli: 'Scegli…',
  oggi: 'Oggi',
  ieri: 'Ieri',
  domani: 'Domani',
  errore: 'Errore',
  attenzione: 'Attenzione',
  dettagli: 'Dettagli',
  altro: 'Altro',
  anteprima: 'Anteprima',
  caricamento: 'Caricamento…',
  nome: 'Nome',
  cognome: 'Cognome',
  data: 'Data',
  ora: 'Ora',
  note: 'Note',
  titolo: 'Titolo',
  descrizione: 'Descrizione',
  togli: 'Togli',
  aggiorna: 'Aggiorna',
  aula: 'Aula',
  tipo: 'Tipo',
  dal: 'Dal',
  al: 'Al',
  // Senza puntini: conferma una scelta in fondo a una finestra; quello che la
  // apre è `scegli`.
  scegliConferma: 'Scegli',
  buttaVia: 'Butta via',
  scarica: 'Scarica',
  esci: 'Esci',
  tutte: 'Tutte',
  senzaTitolo: 'senza titolo',
  vuoto: 'vuoto',
  colore: 'Colore',
  indirizzo: 'Indirizzo',
  email: 'E-mail',
  stato: 'Stato',
  periodo: 'Periodo',
  giorno: 'Giorno',
  settimana: 'Settimana',
  mese: 'Mese',
  chi: 'Chi',
  cheCosa: 'Che cosa',
  dove: 'Dove',
  con: 'Con',
  senza: 'Senza',
  immagini: 'Immagini',
}

export const parole = catalogo(it, {
  de: {
    salva: 'Speichern',
    annulla: 'Abbrechen',
    chiudi: 'Schliessen',
    elimina: 'Löschen',
    modifica: 'Bearbeiten',
    aggiungi: 'Hinzufügen',
    apri: 'Öffnen',
    conferma: 'Bestätigen',
    si: 'Ja',
    no: 'Nein',
    ok: 'OK',
    indietro: 'Zurück',
    avanti: 'Weiter',
    cerca: 'Suchen',
    filtra: 'Filtern…',
    tutti: 'Alle',
    nessuno: 'Keine',
    copia: 'Kopieren',
    incolla: 'Einfügen',
    stampa: 'Drucken',
    esporta: 'Exportieren',
    importa: 'Importieren',
    sfoglia: 'Durchsuchen…',
    riprova: 'Erneut versuchen',
    continua: 'Fortfahren',
    fatto: 'Fertig',
    mostra: 'Anzeigen',
    nascondi: 'Ausblenden',
    rinomina: 'Umbenennen',
    duplica: 'Duplizieren',
    sposta: 'Verschieben',
    scegli: 'Auswählen…',
    oggi: 'Heute',
    ieri: 'Gestern',
    domani: 'Morgen',
    errore: 'Fehler',
    attenzione: 'Achtung',
    dettagli: 'Details',
    altro: 'Weiteres',
    anteprima: 'Vorschau',
    caricamento: 'Wird geladen…',
    nome: 'Vorname',
    cognome: 'Nachname',
    data: 'Datum',
    ora: 'Uhrzeit',
    note: 'Notizen',
    titolo: 'Titel',
    descrizione: 'Beschreibung',
    togli: 'Entfernen',
    aggiorna: 'Aktualisieren',
    aula: 'Zimmer',
    tipo: 'Art',
    dal: 'Von',
    al: 'Bis',
    scegliConferma: 'Auswählen',
    buttaVia: 'Wegwerfen',
    scarica: 'Herunterladen',
    esci: 'Beenden',
    tutte: 'Alle',
    senzaTitolo: 'ohne Titel',
    vuoto: 'leer',
    colore: 'Farbe',
    indirizzo: 'Adresse',
    email: 'E-Mail',
    stato: 'Status',
    periodo: 'Zeitraum',
    giorno: 'Tag',
    settimana: 'Woche',
    mese: 'Monat',
    chi: 'Wer',
    cheCosa: 'Was',
    dove: 'Wo',
    con: 'Mit',
    senza: 'Ohne',
    immagini: 'Bilder',
  },
  fr: {
    salva: 'Enregistrer',
    annulla: 'Annuler',
    chiudi: 'Fermer',
    elimina: 'Supprimer',
    modifica: 'Modifier',
    aggiungi: 'Ajouter',
    apri: 'Ouvrir',
    conferma: 'Confirmer',
    si: 'Oui',
    no: 'Non',
    ok: 'OK',
    indietro: 'Retour',
    avanti: 'Suivant',
    cerca: 'Rechercher',
    filtra: 'Filtrer…',
    tutti: 'Tous',
    nessuno: 'Aucun',
    copia: 'Copier',
    incolla: 'Coller',
    stampa: 'Imprimer',
    esporta: 'Exporter',
    importa: 'Importer',
    sfoglia: 'Parcourir…',
    riprova: 'Réessayer',
    continua: 'Continuer',
    fatto: 'Terminé',
    mostra: 'Afficher',
    nascondi: 'Masquer',
    rinomina: 'Renommer',
    duplica: 'Dupliquer',
    sposta: 'Déplacer',
    scegli: 'Choisir…',
    oggi: 'Aujourd’hui',
    ieri: 'Hier',
    domani: 'Demain',
    errore: 'Erreur',
    attenzione: 'Attention',
    dettagli: 'Détails',
    altro: 'Autre',
    anteprima: 'Aperçu',
    caricamento: 'Chargement…',
    nome: 'Prénom',
    cognome: 'Nom',
    data: 'Date',
    ora: 'Heure',
    note: 'Notes',
    titolo: 'Titre',
    descrizione: 'Description',
    togli: 'Retirer',
    aggiorna: 'Mettre à jour',
    aula: 'Salle',
    tipo: 'Type',
    dal: 'Du',
    al: 'Au',
    scegliConferma: 'Choisir',
    buttaVia: 'Jeter',
    scarica: 'Télécharger',
    esci: 'Quitter',
    tutte: 'Toutes',
    senzaTitolo: 'sans titre',
    vuoto: 'vide',
    colore: 'Couleur',
    indirizzo: 'Adresse',
    email: 'E-mail',
    stato: 'État',
    periodo: 'Période',
    giorno: 'Jour',
    settimana: 'Semaine',
    mese: 'Mois',
    chi: 'Qui',
    cheCosa: 'Quoi',
    dove: 'Où',
    con: 'Avec',
    senza: 'Sans',
    immagini: 'Images',
  },
  en: {
    salva: 'Save',
    annulla: 'Cancel',
    chiudi: 'Close',
    elimina: 'Delete',
    modifica: 'Edit',
    aggiungi: 'Add',
    apri: 'Open',
    conferma: 'Confirm',
    si: 'Yes',
    no: 'No',
    ok: 'OK',
    indietro: 'Back',
    avanti: 'Next',
    cerca: 'Search',
    filtra: 'Filter…',
    tutti: 'All',
    nessuno: 'None',
    copia: 'Copy',
    incolla: 'Paste',
    stampa: 'Print',
    esporta: 'Export',
    importa: 'Import',
    sfoglia: 'Browse…',
    riprova: 'Try again',
    continua: 'Continue',
    fatto: 'Done',
    mostra: 'Show',
    nascondi: 'Hide',
    rinomina: 'Rename',
    duplica: 'Duplicate',
    sposta: 'Move',
    scegli: 'Choose…',
    oggi: 'Today',
    ieri: 'Yesterday',
    domani: 'Tomorrow',
    errore: 'Error',
    attenzione: 'Warning',
    dettagli: 'Details',
    altro: 'Other',
    anteprima: 'Preview',
    caricamento: 'Loading…',
    nome: 'First name',
    cognome: 'Last name',
    data: 'Date',
    ora: 'Time',
    note: 'Notes',
    titolo: 'Title',
    descrizione: 'Description',
    togli: 'Remove',
    aggiorna: 'Update',
    aula: 'Room',
    tipo: 'Type',
    dal: 'From',
    al: 'To',
    scegliConferma: 'Choose',
    buttaVia: 'Throw away',
    scarica: 'Download',
    esci: 'Quit',
    tutte: 'All',
    senzaTitolo: 'untitled',
    vuoto: 'empty',
    colore: 'Colour',
    indirizzo: 'Address',
    email: 'Email',
    stato: 'Status',
    periodo: 'Period',
    giorno: 'Day',
    settimana: 'Week',
    mese: 'Month',
    chi: 'Who',
    cheCosa: 'What',
    dove: 'Where',
    con: 'With',
    senza: 'Without',
    immagini: 'Images',
  },
})
