// I testi di `sorting.ts`: lo smistamento dei PDF, le pagine e i ritagli.

import { catalogo } from '../i18n/index.js'
import { plurale } from '../domain/text.js'

const it = {
  /** Il nome del ritaglio che si apre nel lettore: «Firme pagine 4-6.pdf». */
  pagina: (n: number) => `pagina ${n}`,
  pagineDaA: (da: number, a: number) => `pagine ${da}-${a}`,
  /** Il nome del ritaglio quando quello del PDF non dà niente di scrivibile. */
  documento: 'documento',
  /** La riga della coda di lettura: «Scansione.pdf · pagina 3». */
  etichettaPagina: (nome: string, n: number) => `${nome} · pagina ${n}`,
  assegnazioneNonRiuscita: 'Assegnazione non riuscita.',
  archiviazioneNonRiuscita: 'Archiviazione non riuscita.',
  smistamentoSparito: 'Quello smistamento non c’è più.',
  titoloDialogo: 'PDF da smistare',
  tasto: 'Smista',
  illeggibile: (nome: string, motivo: string) => `«${nome}»: non si riesce a leggerlo (${motivo}).`,
  trascinatoIlleggibile: 'Il file trascinato non si riesce a leggere.',
  trascinatoVuoto: 'Il file trascinato è vuoto.',
  richiestaNonSua: 'Quella richiesta non è stata fatta a questa persona.',
  senzaDocumento: 'Prima si deve dire a quale documento appartiene questo PDF.',
  nessunaProposta: 'Non c’è nessuna proposta da confermare.',
  nessunaDaButtare: 'Nessuna pagina da buttare via.',
  nonPiuInAttesa: 'Quelle pagine non sono più in attesa.',
  originaleSparito: 'Il PDF originale non è più nella cartella del registro.',
  nessunaDaAprire: 'Nessuna pagina da aprire.',
  ritaglioNonRiuscito: (motivo: string) => `Ritaglio non riuscito: ${motivo}`,
  ritaglioNonApribile: 'Ritaglio scritto, ma non si è potuto aprire da qui.',
  nonArchiviate: 'Quelle pagine non sono archiviate da nessuna parte.',
  nessunaScansione: 'Non c’è nessuna scansione da leggere qui.',
  nessunaDaRileggere: 'Non c’è nessuna pagina da rileggere.',
  classeSparita: 'Quella classe non c’è più.',
  passate: (nome: string, pagine: number, da: string, a: string) =>
    `«${nome}»: ${plurale(pagine, 'pagina', 'pagine')} passate da ${da} a ${a}.`,
  oraDi: (nome: string, classe: string) => `«${nome}» è ora di ${classe}.`,
  nessunPdf: 'Nessun PDF da aprire.',
}

export const testi = catalogo(it, {
  de: {
    pagina: (n) => `Seite ${n}`,
    pagineDaA: (da, a) => `Seiten ${da}-${a}`,
    documento: 'Dokument',
    etichettaPagina: (nome, n) => `${nome} · Seite ${n}`,
    assegnazioneNonRiuscita: 'Zuweisung fehlgeschlagen.',
    archiviazioneNonRiuscita: 'Ablage fehlgeschlagen.',
    smistamentoSparito: 'Diese Zuordnung gibt es nicht mehr.',
    titoloDialogo: 'Zuzuordnende PDFs',
    tasto: 'Zuordnen',
    illeggibile: (nome, motivo) => `«${nome}»: lässt sich nicht lesen (${motivo}).`,
    trascinatoIlleggibile: 'Die hineingezogene Datei lässt sich nicht lesen.',
    trascinatoVuoto: 'Die hineingezogene Datei ist leer.',
    richiestaNonSua: 'Diese Anfrage wurde nicht an diese Person gerichtet.',
    senzaDocumento: 'Gib zuerst an, zu welchem Dokument dieses PDF gehört.',
    nessunaProposta: 'Es gibt keinen Vorschlag zu bestätigen.',
    nessunaDaButtare: 'Keine Seite zum Verwerfen.',
    nonPiuInAttesa: 'Diese Seiten warten nicht mehr.',
    originaleSparito: 'Das ursprüngliche PDF ist nicht mehr im Ordner des Klassenbuchs.',
    nessunaDaAprire: 'Keine Seite zum Öffnen.',
    ritaglioNonRiuscito: (motivo) => `Ausschnitt fehlgeschlagen: ${motivo}`,
    ritaglioNonApribile: 'Ausschnitt geschrieben, liess sich aber von hier aus nicht öffnen.',
    nonArchiviate: 'Diese Seiten sind nirgends abgelegt.',
    nessunaScansione: 'Hier gibt es keinen Scan zu lesen.',
    nessunaDaRileggere: 'Es gibt keine Seite neu zu lesen.',
    classeSparita: 'Diese Klasse gibt es nicht mehr.',
    passate: (nome, pagine, da, a) =>
      `«${nome}»: ${plurale(pagine, 'Seite', 'Seiten')} von ${da} zu ${a} verschoben.`,
    oraDi: (nome, classe) => `«${nome}» gehört jetzt zu ${classe}.`,
    nessunPdf: 'Kein PDF zum Öffnen.',
  },
  fr: {
    pagina: (n) => `page ${n}`,
    pagineDaA: (da, a) => `pages ${da}-${a}`,
    documento: 'document',
    etichettaPagina: (nome, n) => `${nome} · page ${n}`,
    assegnazioneNonRiuscita: 'Attribution impossible.',
    archiviazioneNonRiuscita: 'Archivage impossible.',
    smistamentoSparito: 'Ce tri n’existe plus.',
    titoloDialogo: 'PDF à trier',
    tasto: 'Trier',
    illeggibile: (nome, motivo) => `« ${nome} » : impossible de le lire (${motivo}).`,
    trascinatoIlleggibile: 'Le fichier glissé ne peut pas être lu.',
    trascinatoVuoto: 'Le fichier glissé est vide.',
    richiestaNonSua: 'Cette demande n’a pas été faite à cette personne.',
    senzaDocumento: 'Il faut d’abord dire à quel document appartient ce PDF.',
    nessunaProposta: 'Il n’y a aucune proposition à confirmer.',
    nessunaDaButtare: 'Aucune page à jeter.',
    nonPiuInAttesa: 'Ces pages ne sont plus en attente.',
    originaleSparito: 'Le PDF d’origine n’est plus dans le dossier du registre.',
    nessunaDaAprire: 'Aucune page à ouvrir.',
    ritaglioNonRiuscito: (motivo) => `Extrait impossible : ${motivo}`,
    ritaglioNonApribile: 'Extrait écrit, mais il n’a pas pu être ouvert d’ici.',
    nonArchiviate: 'Ces pages ne sont archivées nulle part.',
    nessunaScansione: 'Il n’y a aucun scan à lire ici.',
    nessunaDaRileggere: 'Il n’y a aucune page à relire.',
    classeSparita: 'Cette classe n’existe plus.',
    passate: (nome, pagine, da, a) =>
      `« ${nome} » : ${plurale(pagine, 'page déplacée', 'pages déplacées')} de ${da} à ${a}.`,
    oraDi: (nome, classe) => `« ${nome} » appartient maintenant à ${classe}.`,
    nessunPdf: 'Aucun PDF à ouvrir.',
  },
  en: {
    pagina: (n) => `page ${n}`,
    pagineDaA: (da, a) => `pages ${da}-${a}`,
    documento: 'document',
    etichettaPagina: (nome, n) => `${nome} · page ${n}`,
    assegnazioneNonRiuscita: 'Allocation failed.',
    archiviazioneNonRiuscita: 'Filing failed.',
    smistamentoSparito: 'That sorting is no longer there.',
    titoloDialogo: 'PDFs to sort',
    tasto: 'Sort',
    illeggibile: (nome, motivo) => `“${nome}”: it can’t be read (${motivo}).`,
    trascinatoIlleggibile: 'The dragged file can’t be read.',
    trascinatoVuoto: 'The dragged file is empty.',
    richiestaNonSua: 'That request wasn’t made to this person.',
    senzaDocumento: 'First say which document this PDF belongs to.',
    nessunaProposta: 'There’s no suggestion to confirm.',
    nessunaDaButtare: 'No pages to throw away.',
    nonPiuInAttesa: 'Those pages are no longer waiting.',
    originaleSparito: 'The original PDF is no longer in the register’s folder.',
    nessunaDaAprire: 'No pages to open.',
    ritaglioNonRiuscito: (motivo) => `Extract failed: ${motivo}`,
    ritaglioNonApribile: 'Extract written, but it couldn’t be opened from here.',
    nonArchiviate: 'Those pages aren’t filed anywhere.',
    nessunaScansione: 'There’s no scan to read here.',
    nessunaDaRileggere: 'There’s no page to read again.',
    classeSparita: 'That class is no longer there.',
    passate: (nome, pagine, da, a) =>
      `“${nome}”: ${plurale(pagine, 'page', 'pages')} moved from ${da} to ${a}.`,
    oraDi: (nome, classe) => `“${nome}” now belongs to ${classe}.`,
    nessunPdf: 'No PDF to open.',
  },
})
