// I testi della scheda personale, parte presenze (`student/attendance.ts`).

import { catalogo, perNumero } from '../../../i18n/index.js'
import { plurale } from '../../../domain/text.js'

const it = {
  senzaCorso: 'senza corso',
  /** A che punto è una pratica di assenze, in una pastiglia. */
  fasi: {
    fuori: 'niente da firmare',
    'da-spedire': 'da spedire',
    'in-attesa': 'in attesa di firma',
    firmato: 'firmato',
  },
  giornoPerGiorno: 'Giorno per giorno',
  giorno: 'giorno',
  materie: 'materie',
  udPreviste: 'UD previste',
  udConAppello: 'UD con appello',
  presenzaSuAppello: 'presenza (ore con appello)',
  udDiAssenzaSu: (previste: number) => `UD di assenza su ${previste}`,
  oreConRitardo: 'ore con ritardo',
  udDiEsonero: 'UD di esonero',
  segnatoBene: 'segnato molto bene',
  segnatoMale: 'segnato da migliorare',
  nelComplesso: 'Nel complesso',
  aiutoComplesso:
    'la presenza è sulle UD con l’appello fatto, l’assenza su quelle previste dall’orario',
  nienteNelPeriodoScelto: 'Nessuna ora in programma nel periodo scelto.',
  udPerse: (perse: number, su: number) => `${perse} UD perse su ${su}`,
  minuti: (minuti: number) => `${minuti} min`,
  presenze: 'Presenze',
  nienteNelPeriodo: 'Nessuna ora in programma nel periodo.',
  assenzaSoglia: (soglia: number) => `assenza · soglia ${soglia}%`,
  assenza: 'assenza',
  presenza: 'presenza',
  suPreviste: (fatte: number, previste: number) => `${fatte} su ${previste}`,
  semprePresente: 'Sempre presente: niente da segnalare.',
}

export const testi = catalogo(it, {
  de: {
    senzaCorso: 'ohne Kurs',
    fasi: {
      fuori: 'nichts zu unterschreiben',
      'da-spedire': 'zu verschicken',
      'in-attesa': 'wartet auf Unterschrift',
      firmato: 'unterschrieben',
    },
    giornoPerGiorno: 'Tag für Tag',
    giorno: 'Tag',
    materie: 'Fächer',
    udPreviste: 'vorgesehene Lektionen',
    udConAppello: 'Lektionen mit Präsenzkontrolle',
    presenzaSuAppello: 'Anwesenheit (Stunden mit Präsenzkontrolle)',
    udDiAssenzaSu: (previste) => `Absenzlektionen von ${previste}`,
    oreConRitardo: 'Stunden mit Verspätung',
    udDiEsonero: 'dispensierte Lektionen',
    segnatoBene: 'als sehr gut markiert',
    segnatoMale: 'als verbesserungswürdig markiert',
    nelComplesso: 'Insgesamt',
    aiutoComplesso:
      'die Anwesenheit bezieht sich auf die Lektionen mit Präsenzkontrolle, die Absenz auf ' +
      'die im Stundenplan vorgesehenen',
    nienteNelPeriodoScelto: 'Im gewählten Zeitraum ist keine Stunde geplant.',
    udPerse: (perse, su) => `${perse} von ${su} Lektionen verpasst`,
    minuti: (minuti) => `${minuti} Min.`,
    presenze: 'Anwesenheit',
    nienteNelPeriodo: 'Im Zeitraum ist keine Stunde geplant.',
    assenzaSoglia: (soglia) => `Absenz · Grenze ${soglia}%`,
    assenza: 'Absenz',
    presenza: 'Anwesenheit',
    suPreviste: (fatte, previste) => `${fatte} von ${previste}`,
    semprePresente: 'Immer anwesend: nichts zu melden.',
  },
  fr: {
    senzaCorso: 'sans cours',
    fasi: {
      fuori: 'rien à signer',
      'da-spedire': 'à envoyer',
      'in-attesa': 'en attente de signature',
      firmato: 'signé',
    },
    giornoPerGiorno: 'Jour par jour',
    giorno: 'jour',
    materie: 'branches',
    udPreviste: 'périodes prévues',
    udConAppello: 'périodes avec appel',
    presenzaSuAppello: 'présence (leçons avec appel)',
    udDiAssenzaSu: (previste) => `périodes d’absence sur ${previste}`,
    oreConRitardo: 'leçons avec retard',
    udDiEsonero: 'périodes de dispense',
    segnatoBene: 'marqué très bien',
    segnatoMale: 'marqué à améliorer',
    nelComplesso: 'Dans l’ensemble',
    aiutoComplesso:
      'la présence porte sur les périodes avec appel, l’absence sur celles prévues par l’horaire',
    nienteNelPeriodoScelto: 'Aucune leçon prévue dans la période choisie.',
    udPerse: (perse, su) =>
      `${perse} ${perNumero(perse, 'période manquée', 'périodes manquées')} sur ${su}`,
    minuti: (minuti) => `${minuti} min`,
    presenze: 'Présences',
    nienteNelPeriodo: 'Aucune leçon prévue dans la période.',
    assenzaSoglia: (soglia) => `absence · seuil ${soglia}%`,
    assenza: 'absence',
    presenza: 'présence',
    suPreviste: (fatte, previste) => `${fatte} sur ${previste}`,
    semprePresente: 'Toujours présent : rien à signaler.',
  },
  en: {
    senzaCorso: 'no course',
    fasi: {
      fuori: 'nothing to sign',
      'da-spedire': 'to send',
      'in-attesa': 'awaiting signature',
      firmato: 'signed',
    },
    giornoPerGiorno: 'Day by day',
    giorno: 'day',
    materie: 'subjects',
    udPreviste: 'scheduled periods',
    udConAppello: 'periods with attendance taken',
    presenzaSuAppello: 'attendance (lessons with attendance taken)',
    udDiAssenzaSu: (previste) => `periods absent out of ${previste}`,
    oreConRitardo: 'lessons with late arrival',
    udDiEsonero: 'excused periods',
    segnatoBene: 'marked very good',
    segnatoMale: 'marked needs improvement',
    nelComplesso: 'Overall',
    aiutoComplesso:
      'attendance counts the periods with attendance taken, absence those in the timetable',
    nienteNelPeriodoScelto: 'No lessons scheduled in the chosen period.',
    udPerse: (perse, su) => `${perse} of ${plurale(su, 'period', 'periods')} missed`,
    minuti: (minuti) => `${minuti} min`,
    presenze: 'Attendance',
    nienteNelPeriodo: 'No lessons scheduled in the period.',
    assenzaSoglia: (soglia) => `absence · threshold ${soglia}%`,
    assenza: 'absence',
    presenza: 'attendance',
    suPreviste: (fatte, previste) => `${fatte} of ${previste}`,
    semprePresente: 'Always present: nothing to report.',
  },
})
