// I testi della scheda personale, parte anagrafica (`student/registry.ts`).

import { catalogo, minuscolo } from '../../../i18n/index.js'
import { PERSONE, del } from '../../../domain/lexicon.js'
import { plurale } from '../../../domain/text.js'

const it = {
  quelliChiesti: 'quelli chiesti a lui',
  consegnato: 'consegnato',
  atteso: 'atteso',
  nonCollocato: 'Indirizzo non ancora collocato sulla mappa.',
  trova: 'Trova',
  dallaSede: (distanza: string) => `${distanza} dalla sede`,
  ancheUno: (chi: string) => `anche ${chi}`,
  ancheAltre: (quante: number) => `anche altre ${quante} persone`,
  sullaMappa: 'Sulla mappa',
  laSede: 'La sede: è da qui che si contano le distanze',
  inLineaDAria: (distanza: string) => `${distanza} dalla sede, in linea d’aria`,
  doveSta: 'Dove sta',
  casaA: (distanza: string) => `casa a ${distanza} dalla sede`,
  lavoroA: (dove: string, distanza: string) => `${dove} a ${distanza}`,
  fraCasaELavoro: (distanza: string) => `${distanza} fra casa e lavoro`,
  apriLaMappa: 'Apri la mappa',
  /** Il titolo del tasto che copia una riga dell'anagrafica. */
  copia: (etichetta: string) => `Copia ${etichetta.toLowerCase()}`,
  negliAppunti: (che: string) => `${che} negli appunti.`,
  appuntiNegati: 'Gli appunti non si sono lasciati scrivere.',
  dataDiNascita: 'Data di nascita',
  anni: (anni: number) => `${anni} anni`,
  minorenne: 'minorenne',
  daFarFirmare: 'Assenze da far firmare',
  tuttoFirmato: 'tutto tornato indietro firmato',
  daChiudere: (aperti: number) => `${aperti} periodo${aperti === 1 ? '' : 'i'} ancora da chiudere`,
  apriLeAssenze: 'Apri le assenze',
  /** Il nome dell'azienda, nel blocco dell'azienda: non è il nome di battesimo. */
  nomeAzienda: 'Nome',
  emailDatore: `E-mail ${del(PERSONE.datore)}`,
  /** Quel che manca quando una persona non ha nessun numero, per chi risponde. */
  telefonoDi: {
    pif: `telefono ${del(PERSONE.pif)}`,
    rappresentante: `telefono ${del(PERSONE.rappresentante)}`,
    datore: `telefono ${del(PERSONE.datore)}`,
  },
  /** Un'etichetta dentro la riga di quel che manca. */
  mancante: (etichetta: string) => etichetta.toLowerCase(),
  manca: (voci: readonly string[]) => `Manca: ${voci.join(', ')}.`,
  anagrafica: 'Anagrafica',
  nessunRecapito: 'Nessun recapito',
  comeSiAggiunge: 'Indirizzo, mail e telefoni si aggiungono da «Modifica».',
  compila: 'Compila',
}

export const testi = catalogo(it, {
  de: {
    quelliChiesti: 'die bei dieser Person angeforderten',
    consegnato: 'abgegeben',
    atteso: 'ausstehend',
    nonCollocato: 'Adresse noch nicht auf der Karte verortet.',
    trova: 'Finden',
    dallaSede: (distanza) => `${distanza} von der Schule`,
    ancheUno: (chi) => `auch ${chi}`,
    ancheAltre: (quante) => `noch ${quante} weitere Personen`,
    sullaMappa: 'Auf der Karte',
    laSede: 'Die Schule: Von hier aus werden die Distanzen gemessen',
    inLineaDAria: (distanza) => `${distanza} von der Schule, Luftlinie`,
    doveSta: 'Wohnort und Lehrbetrieb',
    casaA: (distanza) => `Wohnort ${distanza} von der Schule`,
    lavoroA: (dove, distanza) => `${dove} ${distanza} entfernt`,
    fraCasaELavoro: (distanza) => `${distanza} zwischen Wohnort und Arbeit`,
    apriLaMappa: 'Karte öffnen',
    copia: (etichetta) => `${etichetta} kopieren`,
    negliAppunti: (che) => `${che} in die Zwischenablage kopiert.`,
    appuntiNegati: 'Die Zwischenablage liess sich nicht beschreiben.',
    dataDiNascita: 'Geburtsdatum',
    anni: (anni) => `${anni} Jahre`,
    minorenne: 'minderjährig',
    daFarFirmare: 'Absenzen zum Unterschreiben',
    tuttoFirmato: 'alles unterschrieben zurück',
    daChiudere: (aperti) => `${plurale(aperti, 'Zeitraum', 'Zeiträume')} noch offen`,
    apriLeAssenze: 'Absenzen öffnen',
    nomeAzienda: 'Name',
    emailDatore: 'E-Mail des Arbeitgebers',
    telefonoDi: {
      pif: 'Telefon der lernenden Person',
      rappresentante: 'Telefon der gesetzlichen Vertretung',
      datore: 'Telefon des Arbeitgebers',
    },
    // Im Deutschen bleiben die Nomen gross.
    mancante: (etichetta) => etichetta,
    manca: (voci) => `Es fehlt: ${voci.join(', ')}.`,
    anagrafica: 'Personalien',
    nessunRecapito: 'Keine Kontaktadresse',
    comeSiAggiunge: 'Adresse, E-Mail und Telefonnummern fügst du über «Bearbeiten» hinzu.',
    compila: 'Ausfüllen',
  },
  fr: {
    quelliChiesti: 'ceux qui lui ont été demandés',
    consegnato: 'remis',
    atteso: 'attendu',
    nonCollocato: 'Adresse pas encore placée sur la carte.',
    trova: 'Trouver',
    dallaSede: (distanza) => `${distanza} de l’école`,
    ancheUno: (chi) => `aussi ${chi}`,
    ancheAltre: (quante) => `aussi ${quante} autres personnes`,
    sullaMappa: 'Sur la carte',
    laSede: 'L’école : c’est d’ici que l’on compte les distances',
    inLineaDAria: (distanza) => `${distanza} de l’école, à vol d’oiseau`,
    doveSta: 'Domicile et entreprise',
    casaA: (distanza) => `domicile à ${distanza} de l’école`,
    lavoroA: (dove, distanza) => `${dove} à ${distanza}`,
    fraCasaELavoro: (distanza) => `${distanza} entre domicile et travail`,
    apriLaMappa: 'Ouvrir la carte',
    copia: (etichetta) => `Copier : ${minuscolo(etichetta)}`,
    negliAppunti: (che) => `${che} : copié dans le presse-papiers.`,
    appuntiNegati: 'Impossible d’écrire dans le presse-papiers.',
    dataDiNascita: 'Date de naissance',
    anni: (anni) => `${anni} ans`,
    minorenne: 'mineur',
    daFarFirmare: 'Absences à faire signer',
    tuttoFirmato: 'tout est revenu signé',
    daChiudere: (aperti) => `${plurale(aperti, 'période', 'périodes')} encore à clore`,
    apriLeAssenze: 'Ouvrir les absences',
    nomeAzienda: 'Nom',
    emailDatore: 'E-mail de l’employeur',
    telefonoDi: {
      pif: 'téléphone de la personne en formation',
      rappresentante: 'téléphone du représentant légal',
      datore: 'téléphone de l’employeur',
    },
    mancante: (etichetta) => minuscolo(etichetta),
    manca: (voci) => `Il manque : ${voci.join(', ')}.`,
    anagrafica: 'Données personnelles',
    nessunRecapito: 'Aucune adresse de contact',
    comeSiAggiunge: 'L’adresse, l’e-mail et les téléphones s’ajoutent depuis « Modifier ».',
    compila: 'Remplir',
  },
  en: {
    quelliChiesti: 'the ones asked of them',
    consegnato: 'handed in',
    atteso: 'expected',
    nonCollocato: 'Address not yet placed on the map.',
    trova: 'Find',
    dallaSede: (distanza) => `${distanza} from school`,
    ancheUno: (chi) => `also ${chi}`,
    ancheAltre: (quante) => `${quante} other people too`,
    sullaMappa: 'On the map',
    laSede: 'The school: distances are measured from here',
    inLineaDAria: (distanza) => `${distanza} from school, as the crow flies`,
    doveSta: 'Home and workplace',
    casaA: (distanza) => `home ${distanza} from school`,
    lavoroA: (dove, distanza) => `${dove} ${distanza} away`,
    fraCasaELavoro: (distanza) => `${distanza} between home and work`,
    apriLaMappa: 'Open the map',
    copia: (etichetta) => `Copy ${etichetta.toLowerCase()}`,
    negliAppunti: (che) => `${che} copied to the clipboard.`,
    appuntiNegati: 'The clipboard couldn’t be written to.',
    dataDiNascita: 'Date of birth',
    anni: (anni) => `${anni} years old`,
    minorenne: 'under 18',
    daFarFirmare: 'Absences to get signed',
    tuttoFirmato: 'everything back, signed',
    daChiudere: (aperti) => `${plurale(aperti, 'period', 'periods')} still to close`,
    apriLeAssenze: 'Open absences',
    nomeAzienda: 'Name',
    emailDatore: 'Employer’s email',
    telefonoDi: {
      pif: 'learner’s phone',
      rappresentante: 'guardian’s phone',
      datore: 'employer’s phone',
    },
    mancante: (etichetta) => etichetta.toLowerCase(),
    manca: (voci) => `Missing: ${voci.join(', ')}.`,
    anagrafica: 'Personal details',
    nessunRecapito: 'No contact address',
    comeSiAggiunge: 'Add the address, email and phone numbers from “Edit”.',
    compila: 'Fill in',
  },
})
