// I testi dello schermo per la classe (`projection.ts`): i titoli delle
// sezioni, le scritte piccole sotto le voci e quel che si legge in attesa.
//
// Si leggono da in fondo all'aula: parole corte, niente frasi da ufficio.

import { catalogo } from '../i18n/index.js'
import { PIF, Uno } from '../domain/lexicon.js'
import { lessico } from '../domain/lexicon.testi.js'

const it = {
  aula: (aula: string) => `aula ${aula}`,
  cheCosaFacciamo: 'Che cosa facciamo',
  portare: 'Portare: ',
  daFare: 'Da fare',

  // Il calendario proiettato.
  /** La colonna dei numeri del giorno nel calendario annuale. */
  giorno: 'g.',
  vacanze: 'vacanze',
  sabatoDomenica: 'sabato e domenica',
  giorniDiLezione: 'giorni di lezione',
  letteraSettimana: 'A e B: la settimana, sul lunedì',
  prova: 'prova',
  lezione: 'lezione',
  adesso: ' · adesso',

  // Le valutazioni e i documenti.
  votiSu: (espressi: number, attesi: number) => `${espressi} voti su ${attesi}`,
  persona: Uno(PIF),
  voto: 'Voto',
  valutazioni: 'Valutazioni',
  documentiDaPortare: 'Documenti da portare',
  entro: (scadenza: string) => `entro ${scadenza}`,
  senzaTermine: 'senza termine',
  manca: (chi: string) => ` · manca: ${chi}`,
  appello: (presenti: number, totale: number) =>
    `Appello · ${presenti} su ${totale}`,

  // L'attesa.
  registro: 'Registro',
  inAttesa: 'in attesa del pannello',
  pausa: 'Pausa',
  riprende: 'lo schermo riprende quando il docente lo riaccende',
  nienteDaMostrare: 'Niente da mostrare',
  schermoPulito: 'Schermo pulito',
  apriUnOra: 'apri una lezione nel registro',
  nessunaScheda: 'nessuna scheda aperta: si aprono dal pannello',
}

export const testi = catalogo(it, {
  de: {
    aula: (aula) => `Zimmer ${aula}`,
    cheCosaFacciamo: 'Was wir machen',
    portare: 'Mitbringen: ',
    daFare: 'Zu tun',
    giorno: 'T.',
    vacanze: 'Ferien',
    sabatoDomenica: 'Samstag und Sonntag',
    giorniDiLezione: 'Schultage',
    letteraSettimana: 'A und B: die Woche, am Montag',
    prova: 'Prüfung',
    lezione: 'Stunde',
    adesso: ' · jetzt',
    votiSu: (espressi, attesi) => `${espressi} von ${attesi} Noten`,
    persona: Uno(lessico.in('de').pif),
    voto: 'Note',
    valutazioni: 'Beurteilungen',
    documentiDaPortare: 'Mitzubringende Dokumente',
    entro: (scadenza) => `bis ${scadenza}`,
    senzaTermine: 'ohne Frist',
    manca: (chi) => ` · fehlt: ${chi}`,
    appello: (presenti, totale) =>
      `Präsenzkontrolle · ${presenti} von ${totale}`,
    registro: 'Klassenbuch',
    inAttesa: 'wartet auf das Klassenbuch',
    pausa: 'Pause',
    riprende:
      'der Bildschirm geht weiter, wenn die Lehrperson ihn wieder einschaltet',
    nienteDaMostrare: 'Nichts anzuzeigen',
    schermoPulito: 'Leerer Bildschirm',
    apriUnOra: 'öffne eine Stunde im Klassenbuch',
    nessunaScheda: 'keine Karte offen: Sie werden im Klassenbuch geöffnet',
  },
  fr: {
    aula: (aula) => `salle ${aula}`,
    cheCosaFacciamo: 'Ce que nous faisons',
    portare: 'Apporter : ',
    daFare: 'À faire',
    giorno: 'j.',
    vacanze: 'vacances',
    sabatoDomenica: 'samedi et dimanche',
    giorniDiLezione: 'jours de cours',
    letteraSettimana: 'A et B : la semaine, sur le lundi',
    prova: 'épreuve',
    lezione: 'leçon',
    adesso: ' · maintenant',
    votiSu: (espressi, attesi) => `${espressi} notes sur ${attesi}`,
    persona: Uno(lessico.in('fr').pif),
    voto: 'Note',
    valutazioni: 'Évaluations',
    documentiDaPortare: 'Documents à apporter',
    entro: (scadenza) => `d’ici le ${scadenza}`,
    senzaTermine: 'sans délai',
    manca: (chi) => ` · manque : ${chi}`,
    appello: (presenti, totale) => `Appel · ${presenti} sur ${totale}`,
    registro: 'Registre',
    inAttesa: 'en attente du registre',
    pausa: 'Pause',
    riprende: 'l’écran reprend quand l’enseignant le rallume',
    nienteDaMostrare: 'Rien à montrer',
    schermoPulito: 'Écran vide',
    apriUnOra: 'ouvre une leçon dans le registre',
    nessunaScheda: 'aucune fiche ouverte : elles s’ouvrent depuis le registre',
  },
  en: {
    aula: (aula) => `room ${aula}`,
    cheCosaFacciamo: 'What we’re doing',
    portare: 'Bring: ',
    daFare: 'To do',
    giorno: 'd.',
    vacanze: 'holidays',
    sabatoDomenica: 'Saturday and Sunday',
    giorniDiLezione: 'school days',
    letteraSettimana: 'A and B: the week, on the Monday',
    prova: 'test',
    lezione: 'lesson',
    adesso: ' · now',
    votiSu: (espressi, attesi) => `${espressi} of ${attesi} grades`,
    persona: Uno(lessico.in('en').pif),
    voto: 'Grade',
    valutazioni: 'Assessments',
    documentiDaPortare: 'Documents to bring',
    entro: (scadenza) => `by ${scadenza}`,
    senzaTermine: 'no deadline',
    manca: (chi) => ` · missing: ${chi}`,
    appello: (presenti, totale) => `Attendance · ${presenti} of ${totale}`,
    registro: 'Register',
    inAttesa: 'waiting for the register',
    pausa: 'Pause',
    riprende: 'the screen resumes when the teacher turns it back on',
    nienteDaMostrare: 'Nothing to show',
    schermoPulito: 'Clear screen',
    apriUnOra: 'open a lesson in the register',
    nessunaScheda: 'no card open: they are opened from the register',
  },
})
