// I testi delle riconsegne (`returns.ts`).

import { catalogo } from '../../i18n/index.js'
import { plurale } from '../../domain/text.js'

const it = {
  // Le pastiglie dello stato.
  daCorreggere: 'da correggere',
  daRiconsegnare: 'da riconsegnare',
  riconsegnata: 'riconsegnata',

  // Da quanto è stata svolta.
  oggi: 'oggi',
  ieri: 'ieri',
  giorniFa: (giorni: number) => `${giorni} giorni fa`,
  settimaneFa: (settimane: number) => `${settimane} settimane fa`,
  mesiFa: (mesi: number) => `${plurale(mesi, 'mese', 'mesi')} fa`,
  svolta: (quando: string, giorno: string) => `svolta ${quando}, il ${giorno}`,

  // La riga di una prova.
  segnata: 'Prova segnata come riconsegnata.',
  diNuovoDaRiconsegnare: 'Prova di nuovo da riconsegnare.',
  apriProva: 'Apri la prova e la sua griglia dei voti',
  resaATuttiEntro: (giorno: string) => `resa a tutti entro il ${giorno}`,
  nienteDaRidare: 'niente da ridare',
  resaATutti: (quante: number) => `Resa a tutti · ${quante}`,
  segnaIl: (giorno: string) => `Segna il ${giorno} su chi non ha ancora la sua data`,
  nonEraQuesta: 'Non era questa: togli la data a tutti',
  caselleVuote: (quante: number) =>
    plurale(quante, 'casella ancora vuota', 'caselle ancora vuote'),
  fermaDa: (settimane: number) => `ferma da più di ${settimane} settimane`,

  // Una riga per allievo.
  resaIl: 'resa il',
  ilGiornoIn: (chi: string) => `Il giorno in cui ${chi} ha riavuto la sua prova`,
  riconsegnataIlGiorno: (giorno: string) => `Riconsegnata il ${giorno}`,
  provaDel: (giorno: string) => `prova del ${giorno}`,
  riconsegnataIl: 'Riconsegnata il',
  segnapostoData: 'gg.mm.aaaa',
  riconsegnataOggi: 'Riconsegnata oggi',

  // Il pannello dell'ora e quello della prova.
  proveDaRiconsegnare: 'Prove da riconsegnare',
  daRidare: (quante: number) => `${quante} da ridare`,
  quanteDaCorreggere: (quante: number) => `${quante} da correggere`,
  daCompletare: 'Da completare',
  daRidareA: 'Da ridare a',
  recuperiDaRidare: 'Recuperi da ridare',
  daRidareAChiMancava: (quante: number) => `${quante} da ridare a chi mancava`,
  tornataATutti: (giorno: string) => `tornata a tutti entro il ${giorno}`,
  corretta: 'corretta, e ancora in mano a chi insegna',
}

export const testi = catalogo(it, {
  de: {
    daCorreggere: 'zu korrigieren',
    daRiconsegnare: 'zurückzugeben',
    riconsegnata: 'zurückgegeben',
    oggi: 'heute',
    ieri: 'gestern',
    giorniFa: (giorni) => `vor ${giorni} Tagen`,
    settimaneFa: (settimane) => `vor ${settimane} Wochen`,
    mesiFa: (mesi) => `vor ${plurale(mesi, 'Monat', 'Monaten')}`,
    svolta: (quando, giorno) => `geschrieben ${quando}, am ${giorno}`,
    segnata: 'Prüfung als zurückgegeben markiert.',
    diNuovoDaRiconsegnare: 'Prüfung wieder als zurückzugeben markiert.',
    apriProva: 'Prüfung und ihr Notenraster öffnen',
    resaATuttiEntro: (giorno) => `allen zurückgegeben bis ${giorno}`,
    nienteDaRidare: 'nichts zurückzugeben',
    resaATutti: (quante) => `Allen zurückgegeben · ${quante}`,
    segnaIl: (giorno) => `${giorno} bei allen eintragen, die noch kein Datum haben`,
    nonEraQuesta: 'Die falsche: Datum bei allen entfernen',
    caselleVuote: (quante) => plurale(quante, 'Feld noch leer', 'Felder noch leer'),
    fermaDa: (settimane) => `seit über ${settimane} Wochen liegen geblieben`,
    resaIl: 'zurückgegeben am',
    ilGiornoIn: (chi) => `Der Tag, an dem ${chi} die Prüfung zurückbekommen hat`,
    riconsegnataIlGiorno: (giorno) => `Zurückgegeben am ${giorno}`,
    provaDel: (giorno) => `Prüfung vom ${giorno}`,
    riconsegnataIl: 'Zurückgegeben am',
    segnapostoData: 'TT.MM.JJJJ',
    riconsegnataOggi: 'Heute zurückgegeben',
    proveDaRiconsegnare: 'Zurückzugebende Prüfungen',
    daRidare: (quante) => `${quante} zurückzugeben`,
    quanteDaCorreggere: (quante) => `${quante} zu korrigieren`,
    daCompletare: 'Zu vervollständigen',
    daRidareA: 'Zurückzugeben an',
    recuperiDaRidare: 'Zurückzugebende Nachprüfungen',
    daRidareAChiMancava: (quante) => `${quante} noch zurückzugeben an Abwesende`,
    tornataATutti: (giorno) => `allen zurückgegeben bis ${giorno}`,
    corretta: 'korrigiert, aber noch bei der Lehrperson',
  },
  fr: {
    daCorreggere: 'à corriger',
    daRiconsegnare: 'à rendre',
    riconsegnata: 'rendue',
    oggi: 'aujourd’hui',
    ieri: 'hier',
    giorniFa: (giorni) => `il y a ${giorni} jours`,
    settimaneFa: (settimane) => `il y a ${settimane} semaines`,
    mesiFa: (mesi) => `il y a ${mesi} mois`,
    svolta: (quando, giorno) => `passée ${quando}, le ${giorno}`,
    segnata: 'Épreuve marquée comme rendue.',
    diNuovoDaRiconsegnare: 'Épreuve de nouveau à rendre.',
    apriProva: 'Ouvrir l’épreuve et sa grille de notes',
    resaATuttiEntro: (giorno) => `rendue à tous au plus tard le ${giorno}`,
    nienteDaRidare: 'rien à rendre',
    resaATutti: (quante) => `Rendue à tous · ${quante}`,
    segnaIl: (giorno) => `Inscrire le ${giorno} pour ceux qui n’ont pas encore de date`,
    nonEraQuesta: 'Ce n’était pas celle-ci : retirer la date pour tous',
    caselleVuote: (quante) => plurale(quante, 'case encore vide', 'cases encore vides'),
    fermaDa: (settimane) => `en attente depuis plus de ${settimane} semaines`,
    resaIl: 'rendue le',
    ilGiornoIn: (chi) => `Le jour où ${chi} a récupéré son épreuve`,
    riconsegnataIlGiorno: (giorno) => `Rendue le ${giorno}`,
    provaDel: (giorno) => `épreuve du ${giorno}`,
    riconsegnataIl: 'Rendue le',
    segnapostoData: 'jj.mm.aaaa',
    riconsegnataOggi: 'Rendue aujourd’hui',
    proveDaRiconsegnare: 'Épreuves à rendre',
    daRidare: (quante) => `${quante} à rendre`,
    quanteDaCorreggere: (quante) => `${quante} à corriger`,
    daCompletare: 'À compléter',
    daRidareA: 'À rendre à',
    recuperiDaRidare: 'Rattrapages à rendre',
    daRidareAChiMancava: (quante) => `${quante} à rendre aux absents`,
    tornataATutti: (giorno) => `rendue à tous au plus tard le ${giorno}`,
    corretta: 'corrigée, mais encore entre les mains de l’enseignant',
  },
  en: {
    daCorreggere: 'to mark',
    daRiconsegnare: 'to hand back',
    riconsegnata: 'handed back',
    oggi: 'today',
    ieri: 'yesterday',
    giorniFa: (giorni) => `${giorni} days ago`,
    settimaneFa: (settimane) => `${settimane} weeks ago`,
    mesiFa: (mesi) => `${plurale(mesi, 'month', 'months')} ago`,
    svolta: (quando, giorno) => `sat ${quando}, on ${giorno}`,
    segnata: 'Test marked as handed back.',
    diNuovoDaRiconsegnare: 'Test marked as still to hand back.',
    apriProva: 'Open the test and its grade grid',
    resaATuttiEntro: (giorno) => `handed back to everyone by ${giorno}`,
    nienteDaRidare: 'nothing to hand back',
    resaATutti: (quante) => `Handed back to all · ${quante}`,
    segnaIl: (giorno) => `Set ${giorno} for everyone without a date yet`,
    nonEraQuesta: 'Wrong one: remove the date for everyone',
    caselleVuote: (quante) => plurale(quante, 'cell still empty', 'cells still empty'),
    fermaDa: (settimane) => `waiting for more than ${settimane} weeks`,
    resaIl: 'handed back on',
    ilGiornoIn: (chi) => `The day ${chi} got the test back`,
    riconsegnataIlGiorno: (giorno) => `Handed back on ${giorno}`,
    provaDel: (giorno) => `test from ${giorno}`,
    riconsegnataIl: 'Handed back on',
    segnapostoData: 'dd.mm.yyyy',
    riconsegnataOggi: 'Handed back today',
    proveDaRiconsegnare: 'Tests to hand back',
    daRidare: (quante) => `${quante} to hand back`,
    quanteDaCorreggere: (quante) => `${quante} to mark`,
    daCompletare: 'To complete',
    daRidareA: 'To hand back to',
    recuperiDaRidare: 'Resits to hand back',
    daRidareAChiMancava: (quante) => `${quante} to hand back to those who were absent`,
    tornataATutti: (giorno) => `back with everyone by ${giorno}`,
    corretta: 'marked, and still with the teacher',
  },
})
