// I testi di `persone.scheda`. Si leggono al momento dell'uso
// (`titolo: () => …`), mai al caricamento.

import { catalogo } from '../../../i18n/index.js'

const it = {
  titolo: 'La scheda di una persona in formazione: anagrafica, corsi, presenze, per semestre',
  allievoId: 'La persona di cui si vuole la scheda',
  oreEVoti: 'le ore e i voti contati',
  laScheda: 'la scheda',
  udPreviste: 'Le UD che l’orario prevedeva nel periodo',
  assenza: 'Quota di assenza sulle UD PREVISTE, da 0 a 1',
  presenza: 'Quota di presenza sulle UD CON APPELLO',
  media: 'Media pesata dei voti di quel corso',
  attivo: 'Falso per chi si è ritirato',
  indirizzo: 'In una riga, come si scrive su una busta',
  via: 'La via con il civico, da sola: è la casella, non la frase',
  cap: 'Il NAP: si confronta e si raggruppa, la riga composta no',
  localita: 'Il comune: è quel che si conta in «chi viene da dove»',
  nellaZona: 'Se il domicilio è nella zona chiesta. Vero quando non se n’è chiesta nessuna',
  periodi: 'I semestri su cui si è contato a parte. Uno solo se se n’è chiesto uno',
  corso: 'Come si legge: «I MEC A — Matematica»',
  semestreId: 'La voce di «periodi» in cima che dice quando è',
  periodiCorso: 'Le stesse cifre, semestre per semestre: il totale nasconde la china',
  presentazione: {
    titolo: 'La scheda della persona',
    classe: 'Classe',
    azienda: 'Azienda',
    domicilio: 'Domicilio',
    posta: 'Posta',
    suQualiPeriodi: 'Su quali periodi si è contato',
    corsoPerCorso: 'Come sta, corso per corso',
    corso: 'Corso',
    udPerse: 'UD perse',
    assenza: 'Assenza (su previste)',
    perSemestre: 'Per semestre',
    presenza: 'Presenza (su appello)',
    ritardi: 'Ritardi',
    prove: 'Prove',
    media: 'Media',
  },
}

export const testi = catalogo(it, {
  de: {
    titolo:
      'Das Personenblatt einer lernenden Person: Personalien, Kurse, Anwesenheiten, pro Semester',
    allievoId: 'Die Person, deren Personenblatt man will',
    oreEVoti: 'die gezählten Stunden und Noten',
    laScheda: 'das Personenblatt',
    udPreviste: 'Die Lektionen, die der Stundenplan im Zeitraum vorsah',
    assenza: 'Abwesenheitsquote auf die VORGESEHENEN Lektionen, von 0 bis 1',
    presenza: 'Anwesenheitsquote auf die Lektionen MIT PRÄSENZKONTROLLE',
    media: 'Gewichteter Notendurchschnitt dieses Kurses',
    attivo: 'Falsch für ausgetretene Personen',
    indirizzo: 'In einer Zeile, wie man sie auf einen Umschlag schreibt',
    via: 'Die Strasse mit Hausnummer, allein: das Feld, nicht der Satz',
    cap: 'Die PLZ: Sie lässt sich vergleichen und gruppieren, die zusammengesetzte Zeile nicht',
    localita: 'Die Gemeinde: Das zählt man bei «wer kommt woher»',
    nellaZona:
      'Ob der Wohnort in der gefragten Region liegt. Wahr, wenn keine gefragt wurde',
    periodi: 'Die Semester, die einzeln gezählt wurden. Nur eines, wenn eines verlangt wurde',
    corso: 'Wie man ihn liest: «I MEC A — Matematica»',
    semestreId: 'Der Eintrag in «periodi» oben, der sagt, wann es ist',
    periodiCorso:
      'Dieselben Zahlen, Semester für Semester: Das Total verdeckt den Abwärtstrend',
    presentazione: {
      titolo: 'Das Personenblatt',
      classe: 'Klasse',
      azienda: 'Lehrbetrieb',
      domicilio: 'Wohnort',
      posta: 'E-Mail',
      suQualiPeriodi: 'Auf welche Zeiträume gezählt wurde',
      corsoPerCorso: 'Wie es steht, Kurs für Kurs',
      corso: 'Kurs',
      udPerse: 'Verpasste Lekt.',
      assenza: 'Abwesenheit (auf vorgesehene)',
      perSemestre: 'Pro Semester',
      presenza: 'Anwesenheit (auf kontrollierte)',
      ritardi: 'Verspätungen',
      prove: 'Prüfungen',
      media: 'Durchschnitt',
    },
  },
  fr: {
    titolo:
      'La fiche d’une personne en formation : données personnelles, cours, présences, par semestre',
    allievoId: 'La personne dont on veut la fiche',
    oreEVoti: 'les leçons et les notes comptées',
    laScheda: 'la fiche',
    udPreviste: 'Les périodes que l’horaire prévoyait sur l’intervalle',
    assenza: 'Taux d’absence sur les périodes PRÉVUES, de 0 à 1',
    presenza: 'Taux de présence sur les périodes AVEC APPEL',
    media: 'Moyenne pondérée des notes de ce cours',
    attivo: 'Faux pour qui a abandonné',
    indirizzo: 'En une ligne, comme on l’écrit sur une enveloppe',
    via: 'La rue avec le numéro, seule : c’est la case, pas la phrase',
    cap: 'Le NPA : il se compare et se regroupe, la ligne composée non',
    localita: 'La commune : c’est ce qu’on compte dans « qui vient d’où »',
    nellaZona:
      'Si le domicile est dans la zone demandée. Vrai quand aucune n’a été demandée',
    periodi: 'Les semestres comptés séparément. Un seul si on en a demandé un',
    corso: 'Comment il se lit : « I MEC A — Matematica »',
    semestreId: 'L’entrée de « periodi » en haut qui dit quand c’est',
    periodiCorso: 'Les mêmes chiffres, semestre par semestre : le total cache la baisse',
    presentazione: {
      titolo: 'La fiche de la personne',
      classe: 'Classe',
      azienda: 'Entreprise',
      domicilio: 'Domicile',
      posta: 'E-mail',
      suQualiPeriodi: 'Sur quelles périodes on a compté',
      corsoPerCorso: 'Où en est la personne, cours par cours',
      corso: 'Cours',
      udPerse: 'Pér. manquées',
      assenza: 'Absence (sur prévues)',
      perSemestre: 'Par semestre',
      presenza: 'Présence (sur appel)',
      ritardi: 'Retards',
      prove: 'Épreuves',
      media: 'Moyenne',
    },
  },
  en: {
    titolo: 'A learner’s record: personal details, courses, attendance, by semester',
    allievoId: 'The person whose record is wanted',
    oreEVoti: 'the lessons and grades counted',
    laScheda: 'the record',
    udPreviste: 'The periods the timetable planned in the date range',
    assenza: 'Absence rate on the PLANNED periods, from 0 to 1',
    presenza: 'Attendance rate on the periods WITH ATTENDANCE TAKEN',
    media: 'Weighted average of the grades in that course',
    attivo: 'False for those who have withdrawn',
    indirizzo: 'In one line, as written on an envelope',
    via: 'The street with the number, on its own: the field, not the sentence',
    cap: 'The postcode: it can be compared and grouped, the combined line cannot',
    localita: 'The municipality: it is what is counted in “who comes from where”',
    nellaZona: 'Whether the home address is in the area asked for. True when none was asked for',
    periodi: 'The semesters counted separately. Only one if one was asked for',
    corso: 'How it reads: “I MEC A — Matematica”',
    semestreId: 'The entry in “periodi” at the top that says when it is',
    periodiCorso: 'The same figures, semester by semester: the total hides the downward trend',
    presentazione: {
      titolo: 'The person’s record',
      classe: 'Class',
      azienda: 'Company',
      domicilio: 'Home',
      posta: 'Email',
      suQualiPeriodi: 'Which periods were counted',
      corsoPerCorso: 'How they are doing, course by course',
      corso: 'Course',
      udPerse: 'Per. missed',
      assenza: 'Absence (of planned)',
      perSemestre: 'By semester',
      presenza: 'Attendance (of recorded)',
      ritardi: 'Late arrivals',
      prove: 'Tests',
      media: 'Average',
    },
  },
})
