// I testi della finestra nativa delle impostazioni: il telaio della pagina e
// le parole sullo stato di ogni voce. Etichette, descrizioni e scelte arrivano
// con le voci (`vociImpostazioni()`, dal manifesto).

import { catalogo } from '../../../src/i18n/index.js'

const it = {
  // Il telaio, in `settings.html`
  titolo: 'Impostazioni',
  filtroSegnaposto: 'Filtra le impostazioni per nome, chiave o descrizione…',
  filtroEtichetta: 'Filtra le impostazioni',
  rimando: 'Le stesse impostazioni, spiegate e insieme a quelle dell’anno, stanno nel registro.',
  apriNelRegistro: 'Apri nel registro',

  /**
   * I titoli dei gruppi, per il pezzo di chiave che li nomina: `aspetto` per
   * `registroDocenti.aspetto.tema`. Un gruppo che qui non c'è si chiama come
   * la sua chiave.
   */
  gruppi: {
    '': 'Generale',
    aspetto: 'Aspetto',
    vassoio: 'Vassoio',
    avvio: 'Avvio',
    promemoria: 'Promemoria',
    proiezione: 'Proiezione',
    posta: 'Posta',
    recapiti: 'Recapiti',
    modelli: 'Modelli',
    ocr: 'OCR',
    assistente: 'Assistente',
    dettatura: 'Dettatura',
    aggiornamenti: 'Aggiornamenti',
    api: 'API',
  } as Readonly<Record<string, string>>,

  // Un valore, detto fuori dal campo
  acceso: 'acceso',
  spento: 'spento',
  /** Accanto alla spunta. */
  spuntaAccesa: 'Acceso',
  spuntaSpenta: 'Spento',

  /** La nota sotto «Sistema» del tema, quando è la scelta di adesso. */
  temaAdesso: (scuro: boolean) => `adesso: ${scuro ? 'scuro' : 'chiaro'}, come Windows`,
  /** La nota sotto «Sistema» della lingua; il nome come la lingua chiama sé stessa. */
  linguaAdesso: (nome: string) => `adesso: ${nome}, come Windows`,

  ciPensaIlRegistro: 'Ci pensa il registro',
  nessunModello: 'Nessuno: si sceglie nel registro, Impostazioni › Modelli linguistici',
  spiegazione: (etichetta: string) => 'Spiegazione: ' + etichetta,
  ritira: 'Ritira',
  sospesa: (padre: string) => 'sospesa · ' + padre + ' è spento',
  nonSiAccende: 'non si accende',
  modificata: (prima: string) => 'modificata · prima: ' + prima,
  predefinito: (valore: string) => 'predefinito: ' + valore,
  tornaAlPredefinito: (valore: string) => 'Torna al predefinito: ' + valore,
  nessunaCorrisponde: 'Nessuna impostazione corrisponde.',
}

export const testi = catalogo(it, {
  de: {
    titolo: 'Einstellungen',
    filtroSegnaposto: 'Einstellungen nach Name, Schlüssel oder Beschreibung filtern…',
    filtroEtichetta: 'Einstellungen filtern',
    rimando: 'Dieselben Einstellungen, erklärt und zusammen mit denen des Schuljahrs, gibt es im Klassenbuch.',
    apriNelRegistro: 'Im Klassenbuch öffnen',
    gruppi: {
      '': 'Allgemein',
      aspetto: 'Darstellung',
      vassoio: 'Symbol neben der Uhr',
      avvio: 'Start',
      promemoria: 'Erinnerungen',
      proiezione: 'Projektion',
      posta: 'E-Mail',
      recapiti: 'Kontaktangaben',
      modelli: 'Sprachmodelle',
      ocr: 'OCR',
      assistente: 'Assistent',
      dettatura: 'Diktat',
      aggiornamenti: 'Aktualisierungen',
      api: 'API',
    },
    acceso: 'ein',
    spento: 'aus',
    spuntaAccesa: 'Ein',
    spuntaSpenta: 'Aus',
    temaAdesso: (scuro) => `jetzt: ${scuro ? 'dunkel' : 'hell'}, wie Windows`,
    linguaAdesso: (nome) => `jetzt: ${nome}, wie Windows`,
    ciPensaIlRegistro: 'Das Klassenbuch kümmert sich darum',
    nessunModello: 'Keines: Die Wahl erfolgt im Klassenbuch, Einstellungen › Sprachmodelle',
    spiegazione: (etichetta) => 'Erklärung: ' + etichetta,
    ritira: 'Zurücknehmen',
    sospesa: (padre) => 'ausgesetzt · ' + padre + ' ist aus',
    nonSiAccende: 'lässt sich nicht einschalten',
    modificata: (prima) => 'geändert · vorher: ' + prima,
    predefinito: (valore) => 'Standard: ' + valore,
    tornaAlPredefinito: (valore) => 'Zurück zum Standard: ' + valore,
    nessunaCorrisponde: 'Keine Einstellung passt.',
  },
  fr: {
    titolo: 'Paramètres',
    filtroSegnaposto: 'Filtrer les paramètres par nom, clé ou description…',
    filtroEtichetta: 'Filtrer les paramètres',
    rimando: 'Les mêmes paramètres, expliqués et avec ceux de l’année, se trouvent dans le registre.',
    apriNelRegistro: 'Ouvrir dans le registre',
    gruppi: {
      '': 'Général',
      aspetto: 'Apparence',
      vassoio: 'Icône près de l’horloge',
      avvio: 'Démarrage',
      promemoria: 'Rappels',
      proiezione: 'Projection',
      posta: 'Messagerie',
      recapiti: 'Coordonnées',
      modelli: 'Modèles de langage',
      ocr: 'OCR',
      assistente: 'Assistant',
      dettatura: 'Dictée',
      aggiornamenti: 'Mises à jour',
      api: 'API',
    },
    acceso: 'activé',
    spento: 'désactivé',
    spuntaAccesa: 'Activé',
    spuntaSpenta: 'Désactivé',
    temaAdesso: (scuro) => `maintenant : ${scuro ? 'sombre' : 'clair'}, comme Windows`,
    linguaAdesso: (nome) => `maintenant : ${nome}, comme Windows`,
    ciPensaIlRegistro: 'Le registre s’en occupe',
    nessunModello: 'Aucun : il se choisit dans le registre, Paramètres › Modèles de langage',
    spiegazione: (etichetta) => 'Explication : ' + etichetta,
    ritira: 'Retirer',
    sospesa: (padre) => 'suspendu · ' + padre + ' est désactivé',
    nonSiAccende: 'ne s’active pas',
    modificata: (prima) => 'modifié · avant : ' + prima,
    predefinito: (valore) => 'par défaut : ' + valore,
    tornaAlPredefinito: (valore) => 'Revenir à la valeur par défaut : ' + valore,
    nessunaCorrisponde: 'Aucun paramètre ne correspond.',
  },
  en: {
    titolo: 'Settings',
    filtroSegnaposto: 'Filter the settings by name, key or description…',
    filtroEtichetta: 'Filter the settings',
    rimando: 'The same settings, explained and together with the year’s, are in the register.',
    apriNelRegistro: 'Open in the register',
    gruppi: {
      '': 'General',
      aspetto: 'Appearance',
      vassoio: 'Icon next to the clock',
      avvio: 'Start-up',
      promemoria: 'Reminders',
      proiezione: 'Projection',
      posta: 'Mail',
      recapiti: 'Contact details',
      modelli: 'Language models',
      ocr: 'OCR',
      assistente: 'Assistant',
      dettatura: 'Dictation',
      aggiornamenti: 'Updates',
      api: 'API',
    },
    acceso: 'on',
    spento: 'off',
    spuntaAccesa: 'On',
    spuntaSpenta: 'Off',
    temaAdesso: (scuro) => `now: ${scuro ? 'dark' : 'light'}, like Windows`,
    linguaAdesso: (nome) => `now: ${nome}, like Windows`,
    ciPensaIlRegistro: 'The register takes care of it',
    nessunModello: 'None: choose one in the register, Settings › Language models',
    spiegazione: (etichetta) => 'Explanation: ' + etichetta,
    ritira: 'Revert',
    sospesa: (padre) => 'suspended · ' + padre + ' is off',
    nonSiAccende: 'won’t turn on',
    modificata: (prima) => 'changed · before: ' + prima,
    predefinito: (valore) => 'default: ' + valore,
    tornaAlPredefinito: (valore) => 'Back to the default: ' + valore,
    nessunaCorrisponde: 'No setting matches.',
  },
})
