// I testi di `forms/check.ts`: le finestre del check — la data di una casella,
// il nome di una colonna, l'elenco delle colonne da mettere in ordine.

import { catalogo } from '../../i18n/index.js'

const it = {
  spunteCheCadono: (n: number) => n === 1
    ? 'Se ne va anche una casella già spuntata, con la sua data.'
    : `Se ne vanno anche ${n} caselle già spuntate, con le loro date.`,
  data: {
    cambia: 'Cambia la data',
    scegli: 'Scegli la data',
    spunta: 'Spunta',
    fattoIl: 'Fatto il',
    aiuto: 'La casella resta spuntata con questo giorno, anche se la lezione si sposta.',
    serveUnGiorno: 'Serve un giorno: si scrive gg.mm.aaaa, per esempio 7.9.26.',
    spuntataIl: (giorno: string) => `Spuntata con il ${giorno}.`,
  },
  colonna: {
    rinomina: 'Rinomina la colonna',
    nuova: 'Nuova colonna',
    era: (titolo: string) => `Era «${titolo}»`,
    cheCosa: 'Che cosa si spunta',
    segnaposto: 'regolamento firmato, quaderno, relazione…',
    senzaNome: 'Una colonna senza nome non si distingue dalle altre.',
    toltaAltrove: 'Questa colonna non c’è più: è stata tolta altrove.',
    rinominata: (titolo: string) => `Colonna rinominata in «${titolo}».`,
    aggiunta: (titolo: string) => `Colonna «${titolo}» aggiunta.`,
  },
  colonne: {
    nessuna: 'Nessuna colonna: il check del corso sparisce.',
    segnaposto: 'che cosa si spunta',
    nomeDella: (n: number) => `Nome della colonna ${n}`,
    togli: (titolo: string) => `Togli «${titolo}»`,
    togliQuesta: 'Togli questa colonna',
    sottotitolo: 'Trascina per metterle in fila; si vedono in quest’ordine',
    aggiungi: 'Aggiungi una colonna',
    titoli: (titoli: string[]) => titoli.map((t) => `«${t}»`).join(', '),
    cambiateAltrove: 'Le colonne sono cambiate altrove',
    nate: (elenco: string) => `Nel frattempo sono nate ${elenco}: restano, in coda.`,
    tolte: (elenco: string) => `Nel frattempo sono state tolte ${elenco}: non tornano.`,
    salvaLoStesso: 'Salva lo stesso',
    togliere: 'Togliere delle colonne?',
    togliESalva: 'Togli e salva',
    salvate: 'Colonne del check salvate.',
  },
}

export const testi = catalogo(it, {
  de: {
    spunteCheCadono: (n) => n === 1
      ? 'Dabei geht auch ein bereits abgehaktes Feld samt Datum verloren.'
      : `Dabei gehen auch ${n} bereits abgehakte Felder samt Datum verloren.`,
    data: {
      cambia: 'Datum ändern',
      scegli: 'Datum wählen',
      spunta: 'Abhaken',
      fattoIl: 'Erledigt am',
      aiuto:
        'Das Feld bleibt mit diesem Tag abgehakt, auch wenn die Stunde verschoben wird.',
      serveUnGiorno: 'Es braucht einen Tag: Man schreibt TT.MM.JJJJ, zum Beispiel 7.9.26.',
      spuntataIl: (giorno) => `Abgehakt am ${giorno}.`,
    },
    colonna: {
      rinomina: 'Spalte umbenennen',
      nuova: 'Neue Spalte',
      era: (titolo) => `Bisher «${titolo}»`,
      cheCosa: 'Was abgehakt wird',
      segnaposto: 'unterschriebenes Reglement, Heft, Bericht…',
      senzaNome: 'Eine Spalte ohne Namen lässt sich nicht von den anderen unterscheiden.',
      toltaAltrove: 'Diese Spalte gibt es nicht mehr: Sie wurde anderswo entfernt.',
      rinominata: (titolo) => `Spalte in «${titolo}» umbenannt.`,
      aggiunta: (titolo) => `Spalte «${titolo}» hinzugefügt.`,
    },
    colonne: {
      nessuna: 'Keine Spalten: Der Check des Kurses verschwindet.',
      segnaposto: 'was abgehakt wird',
      nomeDella: (n) => `Name der Spalte ${n}`,
      togli: (titolo) => `«${titolo}» entfernen`,
      togliQuesta: 'Diese Spalte entfernen',
      sottotitolo: 'Zum Ordnen ziehen; sie erscheinen in dieser Reihenfolge',
      aggiungi: 'Spalte hinzufügen',
      titoli: (titoli) => titoli.map((t) => `«${t}»`).join(', '),
      cambiateAltrove: 'Die Spalten wurden anderswo geändert',
      nate: (elenco) => `Inzwischen sind ${elenco} dazugekommen: Sie bleiben, am Ende.`,
      tolte: (elenco) => `Inzwischen wurden ${elenco} entfernt: Sie kommen nicht zurück.`,
      salvaLoStesso: 'Trotzdem speichern',
      togliere: 'Spalten entfernen?',
      togliESalva: 'Entfernen und speichern',
      salvate: 'Check-Spalten gespeichert.',
    },
  },
  fr: {
    spunteCheCadono: (n) => n === 1
      ? 'Une case déjà cochée disparaît aussi, avec sa date.'
      : `${n} cases déjà cochées disparaissent aussi, avec leurs dates.`,
    data: {
      cambia: 'Changer la date',
      scegli: 'Choisir la date',
      spunta: 'Cocher',
      fattoIl: 'Fait le',
      aiuto: 'La case reste cochée à ce jour, même si la leçon est déplacée.',
      serveUnGiorno: 'Il faut un jour : on écrit jj.mm.aaaa, par exemple 7.9.26.',
      spuntataIl: (giorno) => `Cochée le ${giorno}.`,
    },
    colonna: {
      rinomina: 'Renommer la colonne',
      nuova: 'Nouvelle colonne',
      era: (titolo) => `Avant : « ${titolo} »`,
      cheCosa: 'Ce qu’on coche',
      segnaposto: 'règlement signé, cahier, rapport…',
      senzaNome: 'Une colonne sans nom ne se distingue pas des autres.',
      toltaAltrove: 'Cette colonne n’existe plus : elle a été supprimée ailleurs.',
      rinominata: (titolo) => `Colonne renommée en « ${titolo} ».`,
      aggiunta: (titolo) => `Colonne « ${titolo} » ajoutée.`,
    },
    colonne: {
      nessuna: 'Aucune colonne : le check du cours disparaît.',
      segnaposto: 'ce qu’on coche',
      nomeDella: (n) => `Nom de la colonne ${n}`,
      togli: (titolo) => `Retirer « ${titolo} »`,
      togliQuesta: 'Retirer cette colonne',
      sottotitolo: 'Glisse-les pour les mettre en ordre ; elles s’affichent dans cet ordre',
      aggiungi: 'Ajouter une colonne',
      titoli: (titoli) => titoli.map((t) => `« ${t} »`).join(', '),
      cambiateAltrove: 'Les colonnes ont changé ailleurs',
      nate: (elenco) => `Entre-temps, ${elenco} sont apparues : elles restent, à la fin.`,
      tolte: (elenco) => `Entre-temps, ${elenco} ont été supprimées : elles ne reviennent pas.`,
      salvaLoStesso: 'Enregistrer quand même',
      togliere: 'Retirer des colonnes ?',
      togliESalva: 'Retirer et enregistrer',
      salvate: 'Colonnes du check enregistrées.',
    },
  },
  en: {
    spunteCheCadono: (n) => n === 1
      ? 'A box that’s already ticked goes too, with its date.'
      : `${n} boxes that are already ticked go too, with their dates.`,
    data: {
      cambia: 'Change the date',
      scegli: 'Choose the date',
      spunta: 'Tick',
      fattoIl: 'Done on',
      aiuto: 'The box stays ticked with this day, even if the lesson moves.',
      serveUnGiorno: 'A day is needed: write dd.mm.yyyy, for example 7.9.26.',
      spuntataIl: (giorno) => `Ticked on ${giorno}.`,
    },
    colonna: {
      rinomina: 'Rename the column',
      nuova: 'New column',
      era: (titolo) => `Was “${titolo}”`,
      cheCosa: 'What gets ticked',
      segnaposto: 'signed rules, exercise book, report…',
      senzaNome: 'A column without a name can’t be told apart from the others.',
      toltaAltrove: 'This column is no longer there: it was removed elsewhere.',
      rinominata: (titolo) => `Column renamed to “${titolo}”.`,
      aggiunta: (titolo) => `Column “${titolo}” added.`,
    },
    colonne: {
      nessuna: 'No columns: the course’s check disappears.',
      segnaposto: 'what gets ticked',
      nomeDella: (n) => `Name of column ${n}`,
      togli: (titolo) => `Remove “${titolo}”`,
      togliQuesta: 'Remove this column',
      sottotitolo: 'Drag to put them in order; they appear in this order',
      aggiungi: 'Add a column',
      titoli: (titoli) => titoli.map((t) => `“${t}”`).join(', '),
      cambiateAltrove: 'The columns have changed elsewhere',
      nate: (elenco) => `Meanwhile ${elenco} appeared: they stay, at the end.`,
      tolte: (elenco) => `Meanwhile ${elenco} were removed: they won’t come back.`,
      salvaLoStesso: 'Save anyway',
      togliere: 'Remove columns?',
      togliESalva: 'Remove and save',
      salvate: 'Check columns saved.',
    },
  },
})
