// I testi di `forms/resources.ts`: l'elenco dei materiali di un piano o di una
// sua tappa, e le due finestre che aggiungono un collegamento e modificano una
// risorsa.

import { catalogo } from '../../i18n/index.js'

const it = {
  modificaRisorsa: 'Modifica la risorsa',
  nessunaRisorsa: 'Nessuna risorsa: si aggiungono qui accanto.',
  collegamento: 'Collegamento',
  aggiungiCollegamento: 'Aggiungi un collegamento',
  file: 'File',
  aggiungiFile: 'Aggiungi un file dalla cartella',
  immagine: 'Immagine',
  aggiungiImmagine: 'Aggiungi un’immagine',
  nuovoCollegamento: 'Nuovo collegamento',
  appesoAllAttivita: 'appeso a questa attività',
  delPianoIntero: 'del piano nel suo insieme',
  aiutoIndirizzo: 'Solo http e https: un piano è un documento, e da un documento si aprono pagine.',
  segnapostoTitolo: 'come lo si chiama nell’elenco',
  aiutoTitolo: 'Se resta vuoto vale l’indirizzo.',
  collegamentoAggiunto: 'Collegamento aggiunto.',
  pianoNelSuoInsieme: 'Il piano nel suo insieme',
  risorsa: (titolo: string) => `Risorsa ${titolo}`,
  appesaA: 'Appesa a',
  spostandola:
    'Spostandola cambia anche il nome del file nell’archivio, che dice a ' +
    'quale tappa appartiene.',
  fileDi: (nome: string) => `File: ${nome}.`,
  perSostituirlo: 'Per sostituirlo se ne aggiunge un altro.',
  segnapostoNote: 'a che cosa serve, quando usarla',
  spostamentoNonRiuscito: 'Spostamento non riuscito.',
  spostataSu: (dove: string) => `Risorsa spostata su «${dove}».`,
  unAltraTappa: 'un’altra tappa',
  spostataSulPiano: 'Risorsa spostata sul piano nel suo insieme.',
  aggiornata: 'Risorsa aggiornata.',
  eliminare: (titolo: string) => `Eliminare «${titolo}»?`,
  soloLaRiga: 'Sparisce solo la riga: la pagina resta dov’è.',
  fileNelCestino: 'Il file esce anche dall’archivio del registro, nel cestino.',
  eliminata: 'Risorsa eliminata.',
}

export const testi = catalogo(it, {
  de: {
    modificaRisorsa: 'Ressource bearbeiten',
    nessunaRisorsa: 'Keine Ressourcen: Du fügst sie gleich hier daneben hinzu.',
    collegamento: 'Link',
    aggiungiCollegamento: 'Link hinzufügen',
    file: 'Datei',
    aggiungiFile: 'Datei aus dem Ordner hinzufügen',
    immagine: 'Bild',
    aggiungiImmagine: 'Bild hinzufügen',
    nuovoCollegamento: 'Neuer Link',
    appesoAllAttivita: 'zu dieser Aktivität',
    delPianoIntero: 'für den ganzen Plan',
    aiutoIndirizzo:
      'Nur http und https: Ein Plan ist ein Dokument, und aus einem Dokument öffnet man Webseiten.',
    segnapostoTitolo: 'wie er in der Liste heisst',
    aiutoTitolo: 'Bleibt er leer, gilt die Adresse.',
    collegamentoAggiunto: 'Link hinzugefügt.',
    pianoNelSuoInsieme: 'Der ganze Plan',
    risorsa: (titolo) => `Ressource ${titolo}`,
    appesaA: 'Gehört zu',
    spostandola:
      'Beim Verschieben ändert sich auch der Dateiname im Archiv: Er sagt, zu welcher ' +
      'Etappe die Datei gehört.',
    fileDi: (nome) => `Datei: ${nome}.`,
    perSostituirlo: 'Um sie zu ersetzen, fügst du eine neue hinzu.',
    segnapostoNote: 'wozu sie dient, wann man sie braucht',
    spostamentoNonRiuscito: 'Verschieben hat nicht geklappt.',
    spostataSu: (dove) => `Ressource verschoben nach «${dove}».`,
    unAltraTappa: 'eine andere Etappe',
    spostataSulPiano: 'Ressource zum ganzen Plan verschoben.',
    aggiornata: 'Ressource aktualisiert.',
    eliminare: (titolo) => `«${titolo}» löschen?`,
    soloLaRiga: 'Nur die Zeile verschwindet: Die Webseite bleibt, wo sie ist.',
    fileNelCestino:
      'Die Datei verlässt auch das Archiv des Klassenbuchs und kommt in den Papierkorb.',
    eliminata: 'Ressource gelöscht.',
  },
  fr: {
    modificaRisorsa: 'Modifier la ressource',
    nessunaRisorsa: 'Aucune ressource : tu les ajoutes juste à côté.',
    collegamento: 'Lien',
    aggiungiCollegamento: 'Ajouter un lien',
    file: 'Fichier',
    aggiungiFile: 'Ajouter un fichier depuis le dossier',
    immagine: 'Image',
    aggiungiImmagine: 'Ajouter une image',
    nuovoCollegamento: 'Nouveau lien',
    appesoAllAttivita: 'rattaché à cette activité',
    delPianoIntero: 'pour l’ensemble du plan',
    aiutoIndirizzo:
      'Seulement http et https : un plan est un document, et depuis un document on ouvre des ' +
      'pages web.',
    segnapostoTitolo: 'son nom dans la liste',
    aiutoTitolo: 'S’il reste vide, c’est l’adresse qui compte.',
    collegamentoAggiunto: 'Lien ajouté.',
    pianoNelSuoInsieme: 'Le plan dans son ensemble',
    risorsa: (titolo) => `Ressource ${titolo}`,
    appesaA: 'Rattachée à',
    spostandola:
      'La déplacer change aussi le nom du fichier dans l’archive, qui indique à quelle ' +
      'étape il appartient.',
    fileDi: (nome) => `Fichier : ${nome}.`,
    perSostituirlo: 'Pour le remplacer, on en ajoute un autre.',
    segnapostoNote: 'à quoi elle sert, quand l’utiliser',
    spostamentoNonRiuscito: 'Le déplacement a échoué.',
    spostataSu: (dove) => `Ressource déplacée vers « ${dove} ».`,
    unAltraTappa: 'une autre étape',
    spostataSulPiano: 'Ressource déplacée vers le plan dans son ensemble.',
    aggiornata: 'Ressource mise à jour.',
    eliminare: (titolo) => `Supprimer « ${titolo} » ?`,
    soloLaRiga: 'Seule la ligne disparaît : la page reste où elle est.',
    fileNelCestino: 'Le fichier sort aussi de l’archive du registre et part à la corbeille.',
    eliminata: 'Ressource supprimée.',
  },
  en: {
    modificaRisorsa: 'Edit the resource',
    nessunaRisorsa: 'No resources: you add them right next to this.',
    collegamento: 'Link',
    aggiungiCollegamento: 'Add a link',
    file: 'File',
    aggiungiFile: 'Add a file from the folder',
    immagine: 'Image',
    aggiungiImmagine: 'Add an image',
    nuovoCollegamento: 'New link',
    appesoAllAttivita: 'attached to this activity',
    delPianoIntero: 'for the plan as a whole',
    aiutoIndirizzo: 'Only http and https: a plan is a document, and a document opens web pages.',
    segnapostoTitolo: 'what it’s called in the list',
    aiutoTitolo: 'If left empty, the address is used.',
    collegamentoAggiunto: 'Link added.',
    pianoNelSuoInsieme: 'The plan as a whole',
    risorsa: (titolo) => `Resource ${titolo}`,
    appesaA: 'Attached to',
    spostandola:
      'Moving it also renames the file in the archive, since the name says which step ' +
      'it belongs to.',
    fileDi: (nome) => `File: ${nome}.`,
    perSostituirlo: 'To replace it, add another one.',
    segnapostoNote: 'what it’s for, when to use it',
    spostamentoNonRiuscito: 'Moving didn’t work.',
    spostataSu: (dove) => `Resource moved to “${dove}”.`,
    unAltraTappa: 'another step',
    spostataSulPiano: 'Resource moved to the plan as a whole.',
    aggiornata: 'Resource updated.',
    eliminare: (titolo) => `Delete “${titolo}”?`,
    soloLaRiga: 'Only the line disappears: the page stays where it is.',
    fileNelCestino: 'The file also leaves the register’s archive and goes to the recycle bin.',
    eliminata: 'Resource deleted.',
  },
})
