// I testi della scheda personale, parte anagrafica (`student/registry.tsx`).

import { catalogo, minuscolo } from '#core/i18n/index.js'
import { PERSONE, del } from '#core/dominio/lexicon.js'
import { plurale } from '#core/dominio/text.js'

const it = {
  quelliChiesti: 'quelli chiesti a lui',
  consegnato: 'consegnato',
  atteso: 'atteso',
  nonCollocato: 'Indirizzo non ancora collocato sulla mappa.',
  trova: 'Trova',
  dallaSede: (distanza: string) => `${distanza} dalla sede`,
  ancheUno: (chi: string) => `anche ${chi}`,
  ancheAltre: (quante: number) => `anche altre ${quante} persone`,
  sullaMappa: 'Sulla mappa',
  laSede: 'La sede: è da qui che si contano le distanze',
  inLineaDAria: (distanza: string) => `${distanza} dalla sede, in linea d’aria`,
  doveSta: 'Dove sta',
  casaA: (distanza: string) => `casa a ${distanza} dalla sede`,
  lavoroA: (dove: string, distanza: string) => `${dove} a ${distanza}`,
  fraCasaELavoro: (distanza: string) => `${distanza} fra casa e lavoro`,
  apriLaMappa: 'Apri la mappa',
  /** Il titolo del tasto che copia una riga dell'anagrafica. */
  copia: (etichetta: string) => `Copia ${etichetta.toLowerCase()}`,
  negliAppunti: (che: string) => `${che} negli appunti.`,
  appuntiNegati: 'Gli appunti non si sono lasciati scrivere.',
  dataDiNascita: 'Data di nascita',
  anni: (anni: number) => `${anni} anni`,
  minorenne: 'minorenne',
  daFarFirmare: 'Assenze da far firmare',
  tuttoFirmato: 'tutto tornato indietro firmato',
  daChiudere: (aperti: number) => `${aperti} periodo${aperti === 1 ? '' : 'i'} ancora da chiudere`,
  apriLeAssenze: 'Apri le assenze',
  // La linguetta del docente di classe quando non c'è ancora niente da seguire.
  nienteDaSeguire: 'Niente da seguire, per ora',
  cheCosaCompare:
    'Qui compaiono i documenti chiesti a questa persona e i fogli delle assenze da far ' +
    'firmare, appena ce ne sono.',
  chiediDocumento: 'Chiedi un documento',
  primaUnCorso: 'Un documento si chiede con una consegna: prima serve un corso in questa classe.',
  /** Il nome dell'azienda, nel blocco dell'azienda: non è il nome di battesimo. */
  nomeAzienda: 'Nome',
  emailDatore: `E-mail ${del(PERSONE.datore)}`,
  /** Quel che manca quando un blocco non ha nessun numero: di chi, lo dice il blocco. */
  telefono: 'telefono',
  /** Un'etichetta dentro la riga di quel che manca. */
  mancante: (etichetta: string) => etichetta.toLowerCase(),
  manca: 'Manca',
  /**
   * Quel che manca di un blocco, una riga per blocco: «e-mail, e-mail» in fila
   * non diceva di chi fosse ognuna.
   */
  mancaDi: (chi: string, voci: readonly string[]) => `${chi}: ${voci.join(', ')}.`,
  anagrafica: 'Anagrafica',
  nessunRecapito: 'Nessun recapito',
  comeSiAggiunge: 'Indirizzo, mail e telefoni si aggiungono da «Modifica».',
  compila: 'Compila',
}

export const testi = catalogo(it, {
  de: {
    quelliChiesti: 'die bei dieser Person angeforderten',
    consegnato: 'abgegeben',
    atteso: 'ausstehend',
    nonCollocato: 'Adresse noch nicht auf der Karte verortet.',
    trova: 'Finden',
    dallaSede: (distanza) => `${distanza} von der Schule`,
    ancheUno: (chi) => `auch ${chi}`,
    ancheAltre: (quante) => `noch ${quante} weitere Personen`,
    sullaMappa: 'Auf der Karte',
    laSede: 'Die Schule: Von hier aus werden die Distanzen gemessen',
    inLineaDAria: (distanza) => `${distanza} von der Schule, Luftlinie`,
    doveSta: 'Wohnort und Lehrbetrieb',
    casaA: (distanza) => `Wohnort ${distanza} von der Schule`,
    lavoroA: (dove, distanza) => `${dove} ${distanza} entfernt`,
    fraCasaELavoro: (distanza) => `${distanza} zwischen Wohnort und Arbeit`,
    apriLaMappa: 'Karte öffnen',
    copia: (etichetta) => `${etichetta} kopieren`,
    negliAppunti: (che) => `${che} in die Zwischenablage kopiert.`,
    appuntiNegati: 'Die Zwischenablage liess sich nicht beschreiben.',
    dataDiNascita: 'Geburtsdatum',
    anni: (anni) => `${anni} Jahre`,
    minorenne: 'minderjährig',
    daFarFirmare: 'Absenzen zum Unterschreiben',
    tuttoFirmato: 'alles unterschrieben zurück',
    daChiudere: (aperti) => `${plurale(aperti, 'Zeitraum', 'Zeiträume')} noch offen`,
    apriLeAssenze: 'Absenzen öffnen',
    nienteDaSeguire: 'Im Moment nichts zu verfolgen',
    cheCosaCompare:
      'Hier erscheinen die bei dieser Person angeforderten Dokumente und die Absenzenblätter ' +
      'zum Unterschreiben, sobald es welche gibt.',
    chiediDocumento: 'Ein Dokument verlangen',
    primaUnCorso:
      'Ein Dokument wird mit einem Auftrag verlangt: Zuerst braucht es einen Kurs in dieser Klasse.',
    nomeAzienda: 'Name',
    emailDatore: 'E-Mail des Arbeitgebers',
    telefono: 'Telefon',
    // Im Deutschen bleiben die Nomen gross.
    mancante: (etichetta) => etichetta,
    manca: 'Es fehlt',
    mancaDi: (chi, voci) => `${chi}: ${voci.join(', ')}.`,
    anagrafica: 'Personalien',
    nessunRecapito: 'Keine Kontaktadresse',
    comeSiAggiunge: 'Adresse, E-Mail und Telefonnummern fügst du über «Bearbeiten» hinzu.',
    compila: 'Ausfüllen',
  },
  fr: {
    quelliChiesti: 'ceux qui lui ont été demandés',
    consegnato: 'remis',
    atteso: 'attendu',
    nonCollocato: 'Adresse pas encore placée sur la carte.',
    trova: 'Trouver',
    dallaSede: (distanza) => `${distanza} de l’école`,
    ancheUno: (chi) => `aussi ${chi}`,
    ancheAltre: (quante) => `aussi ${quante} autres personnes`,
    sullaMappa: 'Sur la carte',
    laSede: 'L’école : c’est d’ici que l’on compte les distances',
    inLineaDAria: (distanza) => `${distanza} de l’école, à vol d’oiseau`,
    doveSta: 'Domicile et entreprise',
    casaA: (distanza) => `domicile à ${distanza} de l’école`,
    lavoroA: (dove, distanza) => `${dove} à ${distanza}`,
    fraCasaELavoro: (distanza) => `${distanza} entre domicile et travail`,
    apriLaMappa: 'Ouvrir la carte',
    copia: (etichetta) => `Copier : ${minuscolo(etichetta)}`,
    negliAppunti: (che) => `${che} : copié dans le presse-papiers.`,
    appuntiNegati: 'Impossible d’écrire dans le presse-papiers.',
    dataDiNascita: 'Date de naissance',
    anni: (anni) => `${anni} ans`,
    minorenne: 'mineur',
    daFarFirmare: 'Absences à faire signer',
    tuttoFirmato: 'tout est revenu signé',
    daChiudere: (aperti) => `${plurale(aperti, 'période', 'périodes')} encore à clore`,
    apriLeAssenze: 'Ouvrir les absences',
    nienteDaSeguire: 'Rien à suivre pour l’instant',
    cheCosaCompare:
      'Ici apparaissent les documents demandés à cette personne et les feuilles d’absences ' +
      'à faire signer, dès qu’il y en a.',
    chiediDocumento: 'Demander un document',
    primaUnCorso:
      'Un document se demande avec un devoir : il faut d’abord un cours dans cette classe.',
    nomeAzienda: 'Nom',
    emailDatore: 'E-mail de l’employeur',
    telefono: 'téléphone',
    mancante: (etichetta) => minuscolo(etichetta),
    manca: 'Il manque',
    mancaDi: (chi, voci) => `${chi} : ${voci.join(', ')}.`,
    anagrafica: 'Données personnelles',
    nessunRecapito: 'Aucune adresse de contact',
    comeSiAggiunge: 'L’adresse, l’e-mail et les téléphones s’ajoutent depuis « Modifier ».',
    compila: 'Remplir',
  },
  en: {
    quelliChiesti: 'the ones asked of them',
    consegnato: 'handed in',
    atteso: 'expected',
    nonCollocato: 'Address not yet placed on the map.',
    trova: 'Find',
    dallaSede: (distanza) => `${distanza} from school`,
    ancheUno: (chi) => `also ${chi}`,
    ancheAltre: (quante) => `${quante} other people too`,
    sullaMappa: 'On the map',
    laSede: 'The school: distances are measured from here',
    inLineaDAria: (distanza) => `${distanza} from school, as the crow flies`,
    doveSta: 'Home and workplace',
    casaA: (distanza) => `home ${distanza} from school`,
    lavoroA: (dove, distanza) => `${dove} ${distanza} away`,
    fraCasaELavoro: (distanza) => `${distanza} between home and work`,
    apriLaMappa: 'Open the map',
    copia: (etichetta) => `Copy ${etichetta.toLowerCase()}`,
    negliAppunti: (che) => `${che} copied to the clipboard.`,
    appuntiNegati: 'The clipboard couldn’t be written to.',
    dataDiNascita: 'Date of birth',
    anni: (anni) => `${anni} years old`,
    minorenne: 'under 18',
    daFarFirmare: 'Absences to get signed',
    tuttoFirmato: 'everything back, signed',
    daChiudere: (aperti) => `${plurale(aperti, 'period', 'periods')} still to close`,
    apriLeAssenze: 'Open absences',
    nienteDaSeguire: 'Nothing to follow up yet',
    cheCosaCompare:
      'Documents requested from this person and absence sheets to get signed appear here ' +
      'as soon as there are any.',
    chiediDocumento: 'Request a document',
    primaUnCorso: 'A document is requested with an assignment: first this class needs a course.',
    nomeAzienda: 'Name',
    emailDatore: 'Employer’s email',
    telefono: 'phone',
    mancante: (etichetta) => etichetta.toLowerCase(),
    manca: 'Missing',
    mancaDi: (chi, voci) => `${chi}: ${voci.join(', ')}.`,
    anagrafica: 'Personal details',
    nessunRecapito: 'No contact address',
    comeSiAggiunge: 'Add the address, email and phone numbers from “Edit”.',
    compila: 'Fill in',
  },
})
