// I testi delle procedure di `mappa`. Valori fra virgolette («domicilio»,
// «entroKm») e nomi di procedura restano uguali in ogni lingua. Si leggono al
// momento dell'uso (`titolo: () => t().titolo`), mai al caricamento.

import { catalogo } from '../../../i18n/index.js'

const it = {
  elenco: {
    titolo: 'Dove abitano: indirizzi collocati, per zona e per distanza',
    classeId: 'Solo gli indirizzi di questa classe',
    allievoId: 'Solo gli indirizzi di questa persona',
    genere: 'Quale indirizzo: «domicilio», «lavoro» o «tutti». Senza, tutti e due',
    entroKm:
      'Solo chi sta entro tanti km in linea d’aria dal punto. Chi non ha coordinate esce',
    lat: 'Latitudine in gradi',
    lon: 'Longitudine in gradi',
    attornoA: 'Il punto da cui si misura. Senza, la sede della scuola',
    ritirati: 'Vero per avere anche chi non frequenta più',
    archiviate: 'Vero per guardare anche nelle classi archiviate',
    ordina: 'Per «distanza» (senza, è questo), per «nome» o per «localita»',
    dove: 'nome, classe, azienda o indirizzo',
    genereRisposto: 'Di quali indirizzi si è risposto',
    comune: 'Il comune chiesto. Vuoto quando non se n’è chiesto',
    cap: 'Il NAP chiesto, anche a metà. Vuoto quando non se n’è chiesto',
    cerca: 'Il filtro di testo applicato. Vuoto quando non se n’è chiesto',
    raggio: 'Il raggio applicato, in km. Nullo quando non se n’è chiesto',
    attorno: 'Da dove si misura la distanza: la sede, o il punto chiesto',
    attornoLat: 'La latitudine del punto da cui si misura',
    attornoLon: 'La longitudine del punto da cui si misura',
    guardate: 'Quanti indirizzi scritti sono stati guardati',
    senzaIndirizzo:
      'Quante caselle d’indirizzo sono vuote: non sono qui dentro, e vanno compilate',
    collocati: 'Quanti fra quelli che corrispondono hanno un punto',
    senzaCoordinate:
      'Quanti non l’hanno: con «entroKm» sono quelli lasciati fuori, non giudicabili',
    lontane: 'Quanti il raggio ha lasciato fuori perché lontani. Nullo senza «entroKm»',
    escluse:
      'Quante persone restano fuori perché non frequentano più: con «ritirati» rientrano',
    classiEscluse:
      'Quante classi restano fuori perché archiviate: con «archiviate» rientrano',
    rigaAllievoId: 'Da passare a «persone.scheda» per il resto',
    attivo: 'Falso per chi si è ritirato: resta nel registro',
    rigaGenere: '«domicilio» o «lavoro»',
    azienda: 'Il nome della ditta. Vuoto quando la riga è il domicilio',
    indirizzo: 'In una riga, come si scrive su una busta',
    via: 'La via con il civico, da sola: è la casella, non la frase',
    rigaCap: 'Il NAP: si ordina e si raggruppa, la riga composta no',
    localita: 'Il comune: è quel che si conta in «chi viene da dove»',
    rigaLat: 'Nullo per chi non è collocato: «mappa.geocodifica» lo cerca',
    rigaLon: 'Nullo per chi non è ancora collocato',
    collocato: 'Vero quando il punto c’è: è il filtro di «chi manca sulla mappa»',
    approssimato: 'Vero quando il punto è il centro del paese e non il portone',
    etichetta: 'Come ha capito l’indirizzo il geocodificatore: serve a non fidarsi',
    distanzaKm: 'In linea d’aria dal punto. Nulla senza coordinate',
    presentazione: {
      titolo: 'Dove abitano',
      indirizzi: 'Indirizzi',
      comune: 'Comune',
      nap: 'NAP',
      distanzeDa: 'Distanze da',
      entroKm: 'Entro km',
      corrispondono: 'Indirizzi che corrispondono',
      conPunto: 'Con un punto',
      senzaPunto: 'Senza punto',
      senzaIndirizzo: 'Senza indirizzo scritto',
      escluse: 'Ritirate, fuori dal filtro',
      classiEscluse: 'Classi archiviate, fuori',
      persona: 'Persona',
      classe: 'Classe',
      cheCose: 'Che cos’è',
      via: 'Via',
      localita: 'Località',
      km: 'Km dal punto',
      sullaMappa: 'Sulla mappa',
    },
  },
  geocodifica: {
    titolo: 'Cerca in rete le coordinate degli indirizzi dell’anagrafica',
    classeIds: 'Senza, tutte le classi non archiviate',
    allievoId: 'Solo gli indirizzi di questa persona',
    rifaiTutto: 'Rimette in fila anche quelli già trovati',
  },
}

export const testi = catalogo(it, {
  de: {
    elenco: {
      titolo: 'Wo sie wohnen: verortete Adressen, nach Gebiet und nach Entfernung',
      classeId: 'Nur die Adressen dieser Klasse',
      allievoId: 'Nur die Adressen dieser Person',
      genere: 'Welche Adresse: «domicilio», «lavoro» oder «tutti». Ohne Angabe beide',
      entroKm:
        'Nur wer innerhalb so vieler km Luftlinie vom Punkt liegt. Wer keine Koordinaten hat, ' +
        'fällt heraus',
      lat: 'Breitengrad in Grad',
      lon: 'Längengrad in Grad',
      attornoA: 'Der Punkt, von dem aus gemessen wird. Ohne Angabe der Sitz der Schule',
      ritirati: 'Wahr, um auch Personen zu erhalten, die nicht mehr teilnehmen',
      archiviate: 'Wahr, um auch in den archivierten Klassen zu suchen',
      ordina: 'Nach «distanza» (Standard), nach «nome» oder nach «localita»',
      dove: 'Name, Klasse, Betrieb oder Adresse',
      genereRisposto: 'Zu welchen Adressen geantwortet wurde',
      comune: 'Die verlangte Gemeinde. Leer, wenn keine verlangt wurde',
      cap: 'Die verlangte PLZ, auch teilweise. Leer, wenn keine verlangt wurde',
      cerca: 'Der angewendete Textfilter. Leer, wenn keiner verlangt wurde',
      raggio: 'Der angewendete Radius, in km. Null, wenn keiner verlangt wurde',
      attorno: 'Von wo aus die Entfernung gemessen wird: der Sitz oder der verlangte Punkt',
      attornoLat: 'Der Breitengrad des Punkts, von dem aus gemessen wird',
      attornoLon: 'Der Längengrad des Punkts, von dem aus gemessen wird',
      guardate: 'Wie viele erfasste Adressen angeschaut wurden',
      senzaIndirizzo:
        'Wie viele Adressfelder leer sind: Sie sind hier nicht enthalten und müssen ausgefüllt ' +
        'werden',
      collocati: 'Wie viele der passenden einen Punkt haben',
      senzaCoordinate:
        'Wie viele keinen haben: Mit «entroKm» sind es die ausgelassenen, nicht beurteilbaren',
      lontane:
        'Wie viele der Radius ausgelassen hat, weil sie zu weit weg sind. Null ohne «entroKm»',
      escluse:
        'Wie viele Personen draussen bleiben, weil sie nicht mehr teilnehmen: Mit «ritirati» sind ' +
        'sie wieder dabei',
      classiEscluse:
        'Wie viele Klassen draussen bleiben, weil sie archiviert sind: Mit «archiviate» sind ' +
        'sie wieder dabei',
      rigaAllievoId: 'An «persone.scheda» zu übergeben für den Rest',
      attivo: 'Falsch für ausgetretene Personen: Sie bleiben im Klassenbuch',
      rigaGenere: '«domicilio» oder «lavoro»',
      azienda: 'Der Name des Betriebs. Leer, wenn die Zeile der Wohnort ist',
      indirizzo: 'In einer Zeile, wie man sie auf einen Umschlag schreibt',
      via: 'Die Strasse mit Hausnummer, allein: das Feld, nicht der Satz',
      rigaCap: 'Die PLZ: Nach ihr sortiert und gruppiert man, nach der ganzen Zeile nicht',
      localita: 'Die Gemeinde: Sie zählt man bei «wer kommt woher»',
      rigaLat: 'Null für nicht verortete Personen: «mappa.geocodifica» sucht den Punkt',
      rigaLon: 'Null für noch nicht verortete Personen',
      collocato: 'Wahr, wenn es den Punkt gibt: der Filter für «wer fehlt auf der Karte»',
      approssimato: 'Wahr, wenn der Punkt die Ortsmitte ist und nicht die Haustür',
      etichetta:
        'Wie der Geocoder die Adresse verstanden hat: dient dazu, ihm nicht blind zu vertrauen',
      distanzaKm: 'Luftlinie vom Punkt. Null ohne Koordinaten',
      presentazione: {
        titolo: 'Wo sie wohnen',
        indirizzi: 'Adressen',
        comune: 'Gemeinde',
        nap: 'PLZ',
        distanzeDa: 'Entfernungen ab',
        entroKm: 'Innerhalb km',
        corrispondono: 'Passende Adressen',
        conPunto: 'Mit Punkt',
        senzaPunto: 'Ohne Punkt',
        senzaIndirizzo: 'Ohne erfasste Adresse',
        escluse: 'Ausgetreten, ausserhalb des Filters',
        classiEscluse: 'Archivierte Klassen, ausserhalb',
        persona: 'Person',
        classe: 'Klasse',
        cheCose: 'Was es ist',
        via: 'Strasse',
        localita: 'Ort',
        km: 'Km vom Punkt',
        sullaMappa: 'Auf der Karte',
      },
    },
    geocodifica: {
      titolo: 'Sucht im Netz die Koordinaten der Adressen in den Personalien',
      classeIds: 'Ohne Angabe alle nicht archivierten Klassen',
      allievoId: 'Nur die Adressen dieser Person',
      rifaiTutto: 'Reiht auch die bereits gefundenen wieder ein',
    },
  },
  fr: {
    elenco: {
      titolo: 'Où ils habitent : adresses localisées, par zone et par distance',
      classeId: 'Seulement les adresses de cette classe',
      allievoId: 'Seulement les adresses de cette personne',
      genere: 'Quelle adresse : « domicilio », « lavoro » ou « tutti ». Sans, les deux',
      entroKm:
        'Seulement ceux qui sont à moins de tant de km à vol d’oiseau du point. Qui n’a pas ' +
        'de coordonnées sort',
      lat: 'Latitude en degrés',
      lon: 'Longitude en degrés',
      attornoA: 'Le point à partir duquel on mesure. Sans, le siège de l’école',
      ritirati: 'Vrai pour avoir aussi les personnes qui ne suivent plus les cours',
      archiviate: 'Vrai pour chercher aussi dans les classes archivées',
      ordina: 'Par « distanza » (par défaut), par « nome » ou par « localita »',
      dove: 'nom, classe, entreprise ou adresse',
      genereRisposto: 'Les adresses auxquelles on a répondu',
      comune: 'La commune demandée. Vide quand il n’y en a pas eu',
      cap: 'Le NPA demandé, même partiel. Vide quand il n’y en a pas eu',
      cerca: 'Le filtre de texte appliqué. Vide quand il n’y en a pas eu',
      raggio: 'Le rayon appliqué, en km. Null quand il n’y en a pas eu',
      attorno: 'D’où l’on mesure la distance : le siège, ou le point demandé',
      attornoLat: 'La latitude du point à partir duquel on mesure',
      attornoLon: 'La longitude du point à partir duquel on mesure',
      guardate: 'Combien d’adresses saisies ont été examinées',
      senzaIndirizzo:
        'Combien de cases d’adresse sont vides : elles ne sont pas ici, et sont à remplir',
      collocati: 'Combien de celles qui correspondent ont un point',
      senzaCoordinate:
        'Combien n’en ont pas : avec « entroKm », ce sont celles laissées de côté, non jugeables',
      lontane:
        'Combien le rayon a laissé de côté parce que trop loin. Null sans « entroKm »',
      escluse:
        'Combien de personnes restent de côté parce qu’elles ne suivent plus les cours : avec ' +
        '« ritirati », elles reviennent',
      classiEscluse:
        'Combien de classes restent de côté parce qu’archivées : avec « archiviate », elles ' +
        'reviennent',
      rigaAllievoId: 'À passer à « persone.scheda » pour le reste',
      attivo: 'Faux pour qui a abandonné : reste dans le registre',
      rigaGenere: '« domicilio » ou « lavoro »',
      azienda: 'Le nom de l’entreprise. Vide quand la ligne est le domicile',
      indirizzo: 'Sur une ligne, comme on l’écrit sur une enveloppe',
      via: 'La rue avec le numéro, seule : c’est la case, pas la phrase',
      rigaCap: 'Le NPA : on trie et on regroupe par lui, pas par la ligne complète',
      localita: 'La commune : c’est ce qu’on compte dans « qui vient d’où »',
      rigaLat: 'Null pour qui n’est pas localisé : « mappa.geocodifica » le cherche',
      rigaLon: 'Null pour qui n’est pas encore localisé',
      collocato: 'Vrai quand le point existe : c’est le filtre de « qui manque sur la carte »',
      approssimato: 'Vrai quand le point est le centre du village et non la porte d’entrée',
      etichetta:
        'Comment le géocodeur a compris l’adresse : sert à ne pas lui faire confiance aveuglément',
      distanzaKm: 'À vol d’oiseau depuis le point. Null sans coordonnées',
      presentazione: {
        titolo: 'Où ils habitent',
        indirizzi: 'Adresses',
        comune: 'Commune',
        nap: 'NPA',
        distanzeDa: 'Distances depuis',
        entroKm: 'Dans un rayon de km',
        corrispondono: 'Adresses correspondantes',
        conPunto: 'Avec un point',
        senzaPunto: 'Sans point',
        senzaIndirizzo: 'Sans adresse saisie',
        escluse: 'Ayant abandonné, hors filtre',
        classiEscluse: 'Classes archivées, hors filtre',
        persona: 'Personne',
        classe: 'Classe',
        cheCose: 'Ce que c’est',
        via: 'Rue',
        localita: 'Localité',
        km: 'Km depuis le point',
        sullaMappa: 'Sur la carte',
      },
    },
    geocodifica: {
      titolo: 'Cherche en ligne les coordonnées des adresses des données personnelles',
      classeIds: 'Sans, toutes les classes non archivées',
      allievoId: 'Seulement les adresses de cette personne',
      rifaiTutto: 'Remet aussi en file celles déjà trouvées',
    },
  },
  en: {
    elenco: {
      titolo: 'Where they live: located addresses, by area and by distance',
      classeId: 'Only the addresses of this class',
      allievoId: 'Only the addresses of this person',
      genere: 'Which address: “domicilio”, “lavoro” or “tutti”. Without it, both',
      entroKm:
        'Only those within so many km as the crow flies from the point. Anyone without ' +
        'coordinates is left out',
      lat: 'Latitude in degrees',
      lon: 'Longitude in degrees',
      attornoA: 'The point to measure from. Without it, the school’s premises',
      ritirati: 'True to also get those who no longer attend',
      archiviate: 'True to also look in archived classes',
      ordina: 'By “distanza” (the default), by “nome” or by “localita”',
      dove: 'name, class, company or address',
      genereRisposto: 'Which addresses the answer covers',
      comune: 'The municipality asked for. Empty when none was asked for',
      cap: 'The postcode asked for, even partial. Empty when none was asked for',
      cerca: 'The text filter applied. Empty when none was asked for',
      raggio: 'The radius applied, in km. Null when none was asked for',
      attorno: 'Where the distance is measured from: the premises, or the point asked for',
      attornoLat: 'The latitude of the point measured from',
      attornoLon: 'The longitude of the point measured from',
      guardate: 'How many written addresses were looked at',
      senzaIndirizzo:
        'How many address boxes are empty: they are not in here, and need filling in',
      collocati: 'How many of those that match have a point',
      senzaCoordinate:
        'How many do not: with “entroKm” they are the ones left out, which cannot be judged',
      lontane: 'How many the radius left out because too far away. Null without “entroKm”',
      escluse:
        'How many people are left out because they no longer attend: with “ritirati” they come back in',
      classiEscluse:
        'How many classes are left out because archived: with “archiviate” they come back in',
      rigaAllievoId: 'To pass to “persone.scheda” for the rest',
      attivo: 'False for those who have withdrawn: stays in the register',
      rigaGenere: '“domicilio” or “lavoro”',
      azienda: 'The company’s name. Empty when the row is the home address',
      indirizzo: 'On one line, as written on an envelope',
      via: 'The street with the house number, on its own: the box, not the sentence',
      rigaCap: 'The postcode: you sort and group by it, not by the full line',
      localita: 'The municipality: it is what you count in “who comes from where”',
      rigaLat: 'Null for those not located: “mappa.geocodifica” looks for it',
      rigaLon: 'Null for those not located yet',
      collocato: 'True when the point exists: it is the filter for “who is missing on the map”',
      approssimato: 'True when the point is the village centre and not the front door',
      etichetta: 'How the geocoder understood the address: it helps you not to trust it blindly',
      distanzaKm: 'As the crow flies from the point. Null without coordinates',
      presentazione: {
        titolo: 'Where they live',
        indirizzi: 'Addresses',
        comune: 'Municipality',
        nap: 'Postcode',
        distanzeDa: 'Distances from',
        entroKm: 'Within km',
        corrispondono: 'Matching addresses',
        conPunto: 'With a point',
        senzaPunto: 'Without a point',
        senzaIndirizzo: 'No written address',
        escluse: 'Withdrawn, outside the filter',
        classiEscluse: 'Archived classes, left out',
        persona: 'Person',
        classe: 'Class',
        cheCose: 'What it is',
        via: 'Street',
        localita: 'Place',
        km: 'Km from the point',
        sullaMappa: 'On the map',
      },
    },
    geocodifica: {
      titolo: 'Looks up online the coordinates of the addresses in the personal details',
      classeIds: 'Without it, all classes that are not archived',
      allievoId: 'Only the addresses of this person',
      rifaiTutto: 'Also puts back in the queue those already found',
    },
  },
})
