// I testi di `forms/project.tsx`: le finestre del progetto — testata, criteri,
// livelli, compiti, proroghe, inizi, giudizi e caselle della matrice.

import { catalogo } from '#core/i18n/index.js'

const it = {
  stati: { bozza: 'Bozza', 'in-corso': 'In corso', concluso: 'Concluso' },
  nuovo: 'Nuovo progetto',
  segnapostoTitolo: 'Per esempio: il giornale di classe',
  periodoDaFasi: 'Il periodo lo danno le lezioni: abbina delle fasi del piano al progetto.',
  nessunaLezioneAncora: 'Nessuna lezione ancora: abbina delle fasi del piano al progetto.',
  // Da sola la data non dice che cosa: è il giorno delle lezioni del progetto.
  ilGiorno: (data: string) => `Lezioni il ${data}`,
  dalAl: (dal: string, al: string) => `Dal ${dal} al ${al}`,
  obiettivi: 'Obiettivi',
  obiettiviAiuto: 'Uno per riga: si leggono come un elenco.',
  collegamenti: 'Collegamenti',
  titoloCollegamento: 'Titolo del collegamento',
  indirizzoCollegamento: 'Indirizzo del collegamento',
  togliCollegamento: 'Togli il collegamento',
  aggiungiCollegamento: 'Aggiungi un collegamento',
  serveTitolo: 'Serve un titolo.',
  creato: (titolo: string) => `Progetto «${titolo}» creato.`,
  salvato: 'Progetto salvato.',
  eliminato: 'Progetto eliminato.',
  togliereCelle: 'Togliere delle caselle della matrice?',
  celleCadono: (n: number) => n === 1
    ? 'Una casella della matrice usa un criterio o un livello che togli: se ne va con lui.'
    : `${n} caselle della matrice usano un criterio o un livello che togli: se ne vanno con lui.`,
  togliESalva: 'Togli e salva',
  togli: (titolo: string) => `Togli «${titolo}»`,
  criteriAiuto:
    'Ogni criterio è una riga della matrice. Rinominarlo tiene le caselle già date; ' +
    'toglierlo le toglie.',
  nomeCriterio: (n: number) => `Nome del criterio ${n}`,
  segnapostoCriterio: 'che cosa si guarda',
  nessunCriterio: 'Nessun criterio: la matrice resta vuota.',
  aggiungiCriterio: 'Aggiungi un criterio',
  criteriSalvati: 'Criteri salvati.',
  fasi: 'Fasi',
  fasiAiuto:
    'Le fasi dividono il progetto: ognuna raccoglie le attività dei piani che le assegni. ' +
    'Ce n’è sempre almeno una; togliendone una, le sue attività passano a quella prima.',
  nomeFase: (n: number) => `Nome della fase ${n}`,
  segnapostoFase: (n: number) => `Fase ${n}`,
  aggiungiFase: 'Aggiungi una fase',
  serveUnaFase: 'Serve almeno una fase.',
  fasiSalvate: 'Fasi salvate.',
  livelli: 'Livelli',
  livelliAiuto:
    'La scala con cui si giudica ogni criterio, dal basso. Rinominare un livello tiene ' +
    'le caselle; toglierlo le lascia senza livello.',
  coloreLivello: (n: number) => `Colore del livello ${n}`,
  descrizioneLivello: (n: number) => `Che cosa vuol dire il livello ${n}`,
  segnapostoDescrizioneLivello: 'Che cosa vuol dire raggiungerlo',
  colorePredefinito: 'Predefinito',
  colori: ['Rosso', 'Arancio', 'Verde', 'Blu', 'Viola', 'Giallo', 'Azzurro', 'Grigio'],
  nomeLivello: (n: number) => `Nome del livello ${n}`,
  segnapostoLivello: 'raggiunto, parziale…',
  aggiungiLivello: 'Aggiungi un livello',
  serveUnLivello: 'Serve almeno un livello.',
  livelliSalvati: 'Livelli salvati.',
  nuovoCompito: 'Nuovo compito',
  segnapostoCompito: 'Per esempio: la scaletta dell’articolo',
  fineComune: 'Fine per tutti',
  fineComuneAiuto: 'Una proroga la sposta per un allievo solo.',
  fineInLezione: 'Oppure entro la lezione',
  nessunaLezione: 'Nessuna: vale la data',
  compitoCreato: (titolo: string) => `Compito «${titolo}» aggiunto.`,
  compitoSalvato: 'Compito salvato.',
  eliminareCompito: (titolo: string) => `Eliminare «${titolo}»?`,
  eliminareCompitoTesto: 'Se ne vanno anche inizi, proroghe e spunte di tutti.',
  compitoEliminato: 'Compito eliminato.',
  proroga: 'Proroga',
  finoAl: 'Fino al',
  segnapostoProroga: 'perché, se serve',
  serveGiorno: 'Serve un giorno: si scrive gg.mm.aaaa, per esempio 7.9.26.',
  prorogaSalvata: (data: string) => `Proroga fino al ${data}.`,
  togliProroga: 'Togli la proroga',
  prorogaTolta: 'Proroga tolta: vale la fine per tutti.',
  inizioDelCompito: 'Inizio del compito',
  quanti: (n: number) => n === 1 ? 'una persona' : `${n} persone`,
  cominciatoIl: 'Cominciato il',
  inizioSalvato: (data: string) => `Inizio segnato il ${data}.`,
  nuovoGiudizio: 'Nuovo giudizio',
  tuttaLaClasse: 'Tutta la classe',
  nellOraDel: (data: string) => `Nella lezione di ${data}`,
  segnapostoGiudizio: 'Come sta andando, che cosa manca, che cosa funziona',
  giudizioVuoto: 'Un giudizio vuoto non dice niente.',
  giudizioSalvato: 'Giudizio salvato.',
  eliminareGiudizio: 'Eliminare il giudizio?',
  giudizioEliminato: 'Giudizio eliminato.',
  livello: 'Livello',
  senzaLivello: 'Nessun livello (solo la nota)',
  cellaSalvata: 'Casella salvata.',
}

export const testi = catalogo(it, {
  de: {
    stati: { bozza: 'Entwurf', 'in-corso': 'Laufend', concluso: 'Abgeschlossen' },
    nuovo: 'Neues Projekt',
    segnapostoTitolo: 'Zum Beispiel: die Klassenzeitung',
    periodoDaFasi: 'Den Zeitraum geben die Stunden: Ordne dem Projekt Phasen des Plans zu.',
    nessunaLezioneAncora: 'Noch keine Stunde: Ordne dem Projekt Phasen des Plans zu.',
    ilGiorno: (data) => `Stunden am ${data}`,
    dalAl: (dal, al) => `Vom ${dal} bis ${al}`,
    obiettivi: 'Ziele',
    obiettiviAiuto: 'Eines pro Zeile: Sie werden als Liste gelesen.',
    collegamenti: 'Links',
    titoloCollegamento: 'Titel des Links',
    indirizzoCollegamento: 'Adresse des Links',
    togliCollegamento: 'Link entfernen',
    aggiungiCollegamento: 'Link hinzufügen',
    serveTitolo: 'Es braucht einen Titel.',
    creato: (titolo) => `Projekt «${titolo}» erstellt.`,
    salvato: 'Projekt gespeichert.',
    eliminato: 'Projekt gelöscht.',
    togliereCelle: 'Felder des Rasters entfernen?',
    celleCadono: (n) => n === 1
      ? 'Ein Feld des Rasters verwendet ein Kriterium oder eine Stufe, die du entfernst: Es geht mit.'
      : `${n} Felder des Rasters verwenden ein Kriterium oder eine Stufe, die du entfernst: Sie gehen mit.`,
    togliESalva: 'Entfernen und speichern',
    togli: (titolo) => `«${titolo}» entfernen`,
    criteriAiuto:
      'Jedes Kriterium ist eine Zeile des Rasters. Umbenennen behält die vergebenen ' +
      'Felder; Entfernen entfernt sie.',
    nomeCriterio: (n) => `Name des Kriteriums ${n}`,
    segnapostoCriterio: 'worauf man achtet',
    nessunCriterio: 'Kein Kriterium: Das Raster bleibt leer.',
    aggiungiCriterio: 'Kriterium hinzufügen',
    criteriSalvati: 'Kriterien gespeichert.',
    fasi: 'Phasen',
    fasiAiuto:
      'Die Phasen teilen das Projekt: Jede sammelt die Aktivitäten der Pläne, die du ihr ' +
      'zuweist. Es gibt immer mindestens eine; wird eine entfernt, gehen ihre Aktivitäten zur vorherigen.',
    nomeFase: (n) => `Name der Phase ${n}`,
    segnapostoFase: (n) => `Phase ${n}`,
    aggiungiFase: 'Phase hinzufügen',
    serveUnaFase: 'Es braucht mindestens eine Phase.',
    fasiSalvate: 'Phasen gespeichert.',
    livelli: 'Stufen',
    livelliAiuto:
      'Die Skala, mit der jedes Kriterium beurteilt wird, von unten. Umbenennen behält ' +
      'die Felder; Entfernen lässt sie ohne Stufe.',
    coloreLivello: (n) => `Farbe der Stufe ${n}`,
    descrizioneLivello: (n) => `Was Stufe ${n} bedeutet`,
    segnapostoDescrizioneLivello: 'Was es heisst, sie zu erreichen',
    colorePredefinito: 'Standard',
    colori: ['Rot', 'Orange', 'Grün', 'Blau', 'Violett', 'Gelb', 'Hellblau', 'Grau'],
    nomeLivello: (n) => `Name der Stufe ${n}`,
    segnapostoLivello: 'erreicht, teilweise…',
    aggiungiLivello: 'Stufe hinzufügen',
    serveUnLivello: 'Es braucht mindestens eine Stufe.',
    livelliSalvati: 'Stufen gespeichert.',
    nuovoCompito: 'Neue Aufgabe',
    segnapostoCompito: 'Zum Beispiel: die Gliederung des Artikels',
    fineComune: 'Ende für alle',
    fineComuneAiuto: 'Eine Verlängerung verschiebt es für eine einzelne Person.',
    fineInLezione: 'Oder bis zur Stunde',
    nessunaLezione: 'Keine: Es gilt das Datum',
    compitoCreato: (titolo) => `Aufgabe «${titolo}» hinzugefügt.`,
    compitoSalvato: 'Aufgabe gespeichert.',
    eliminareCompito: (titolo) => `«${titolo}» löschen?`,
    eliminareCompitoTesto: 'Damit gehen auch Beginn, Verlängerungen und Häkchen aller verloren.',
    compitoEliminato: 'Aufgabe gelöscht.',
    proroga: 'Verlängerung',
    finoAl: 'Bis am',
    segnapostoProroga: 'warum, falls nötig',
    serveGiorno: 'Es braucht einen Tag: tt.mm.jjjj, zum Beispiel 7.9.26.',
    prorogaSalvata: (data) => `Verlängert bis am ${data}.`,
    togliProroga: 'Verlängerung entfernen',
    prorogaTolta: 'Verlängerung entfernt: Es gilt das Ende für alle.',
    inizioDelCompito: 'Beginn der Aufgabe',
    quanti: (n) => n === 1 ? 'eine Person' : `${n} Personen`,
    cominciatoIl: 'Begonnen am',
    inizioSalvato: (data) => `Beginn am ${data} eingetragen.`,
    nuovoGiudizio: 'Neue Einschätzung',
    tuttaLaClasse: 'Ganze Klasse',
    nellOraDel: (data) => `In der Stunde vom ${data}`,
    segnapostoGiudizio: 'Wie es läuft, was fehlt, was funktioniert',
    giudizioVuoto: 'Eine leere Einschätzung sagt nichts.',
    giudizioSalvato: 'Einschätzung gespeichert.',
    eliminareGiudizio: 'Einschätzung löschen?',
    giudizioEliminato: 'Einschätzung gelöscht.',
    livello: 'Stufe',
    senzaLivello: 'Keine Stufe (nur die Notiz)',
    cellaSalvata: 'Feld gespeichert.',
  },
  fr: {
    stati: { bozza: 'Brouillon', 'in-corso': 'En cours', concluso: 'Terminé' },
    nuovo: 'Nouveau projet',
    segnapostoTitolo: 'Par exemple : le journal de classe',
    periodoDaFasi: 'La période vient des périodes de cours : lie des phases du plan au projet.',
    nessunaLezioneAncora: 'Aucune période encore : lie des phases du plan au projet.',
    ilGiorno: (data) => `Leçons le ${data}`,
    dalAl: (dal, al) => `Du ${dal} au ${al}`,
    obiettivi: 'Objectifs',
    obiettiviAiuto: 'Un par ligne : ils se lisent comme une liste.',
    collegamenti: 'Liens',
    titoloCollegamento: 'Titre du lien',
    indirizzoCollegamento: 'Adresse du lien',
    togliCollegamento: 'Retirer le lien',
    aggiungiCollegamento: 'Ajouter un lien',
    serveTitolo: 'Il faut un titre.',
    creato: (titolo) => `Projet « ${titolo} » créé.`,
    salvato: 'Projet enregistré.',
    eliminato: 'Projet supprimé.',
    togliereCelle: 'Retirer des cases de la grille ?',
    celleCadono: (n) => n === 1
      ? 'Une case de la grille utilise un critère ou un niveau que tu retires : elle part avec lui.'
      : `${n} cases de la grille utilisent un critère ou un niveau que tu retires : elles partent avec lui.`,
    togliESalva: 'Retirer et enregistrer',
    togli: (titolo) => `Retirer « ${titolo} »`,
    criteriAiuto:
      'Chaque critère est une ligne de la grille. Le renommer garde les cases déjà ' +
      'données ; le retirer les retire.',
    nomeCriterio: (n) => `Nom du critère ${n}`,
    segnapostoCriterio: 'ce que l’on observe',
    nessunCriterio: 'Aucun critère : la grille reste vide.',
    aggiungiCriterio: 'Ajouter un critère',
    criteriSalvati: 'Critères enregistrés.',
    fasi: 'Phases',
    fasiAiuto:
      'Les phases divisent le projet : chacune réunit les activités des plans que tu lui ' +
      'attribues. Il y en a toujours au moins une ; si on en retire une, ses activités passent à la précédente.',
    nomeFase: (n) => `Nom de la phase ${n}`,
    segnapostoFase: (n) => `Phase ${n}`,
    aggiungiFase: 'Ajouter une phase',
    serveUnaFase: 'Il faut au moins une phase.',
    fasiSalvate: 'Phases enregistrées.',
    livelli: 'Niveaux',
    livelliAiuto:
      'L’échelle avec laquelle on juge chaque critère, du bas. Renommer un niveau garde ' +
      'les cases ; le retirer les laisse sans niveau.',
    coloreLivello: (n) => `Couleur du niveau ${n}`,
    descrizioneLivello: (n) => `Ce que veut dire le niveau ${n}`,
    segnapostoDescrizioneLivello: 'Ce que veut dire l’atteindre',
    colorePredefinito: 'Par défaut',
    colori: ['Rouge', 'Orange', 'Vert', 'Bleu', 'Violet', 'Jaune', 'Bleu clair', 'Gris'],
    nomeLivello: (n) => `Nom du niveau ${n}`,
    segnapostoLivello: 'atteint, partiel…',
    aggiungiLivello: 'Ajouter un niveau',
    serveUnLivello: 'Il faut au moins un niveau.',
    livelliSalvati: 'Niveaux enregistrés.',
    nuovoCompito: 'Nouvelle tâche',
    segnapostoCompito: 'Par exemple : le plan de l’article',
    fineComune: 'Fin pour tous',
    fineComuneAiuto: 'Une prolongation la déplace pour une seule personne.',
    fineInLezione: 'Ou d’ici la période',
    nessunaLezione: 'Aucune : la date fait foi',
    compitoCreato: (titolo) => `Tâche « ${titolo} » ajoutée.`,
    compitoSalvato: 'Tâche enregistrée.',
    eliminareCompito: (titolo) => `Supprimer « ${titolo} » ?`,
    eliminareCompitoTesto: 'Les débuts, prolongations et coches de tous partent aussi.',
    compitoEliminato: 'Tâche supprimée.',
    proroga: 'Prolongation',
    finoAl: 'Jusqu’au',
    segnapostoProroga: 'pourquoi, si besoin',
    serveGiorno: 'Il faut un jour : jj.mm.aaaa, par exemple 7.9.26.',
    prorogaSalvata: (data) => `Prolongé jusqu’au ${data}.`,
    togliProroga: 'Retirer la prolongation',
    prorogaTolta: 'Prolongation retirée : la fin pour tous fait foi.',
    inizioDelCompito: 'Début de la tâche',
    quanti: (n) => n === 1 ? 'une personne' : `${n} personnes`,
    cominciatoIl: 'Commencé le',
    inizioSalvato: (data) => `Début noté le ${data}.`,
    nuovoGiudizio: 'Nouvelle appréciation',
    tuttaLaClasse: 'Toute la classe',
    nellOraDel: (data) => `Dans la période du ${data}`,
    segnapostoGiudizio: 'Comment ça avance, ce qui manque, ce qui marche',
    giudizioVuoto: 'Une appréciation vide ne dit rien.',
    giudizioSalvato: 'Appréciation enregistrée.',
    eliminareGiudizio: 'Supprimer l’appréciation ?',
    giudizioEliminato: 'Appréciation supprimée.',
    livello: 'Niveau',
    senzaLivello: 'Aucun niveau (seulement la note)',
    cellaSalvata: 'Case enregistrée.',
  },
  en: {
    stati: { bozza: 'Draft', 'in-corso': 'In progress', concluso: 'Finished' },
    nuovo: 'New project',
    segnapostoTitolo: 'For example: the class newspaper',
    periodoDaFasi: 'The period comes from the lessons: link plan phases to the project.',
    nessunaLezioneAncora: 'No lessons yet: link plan phases to the project.',
    ilGiorno: (data) => `Lessons on ${data}`,
    dalAl: (dal, al) => `From ${dal} to ${al}`,
    obiettivi: 'Objectives',
    obiettiviAiuto: 'One per line: they read as a list.',
    collegamenti: 'Links',
    titoloCollegamento: 'Link title',
    indirizzoCollegamento: 'Link address',
    togliCollegamento: 'Remove the link',
    aggiungiCollegamento: 'Add a link',
    serveTitolo: 'A title is needed.',
    creato: (titolo) => `Project “${titolo}” created.`,
    salvato: 'Project saved.',
    eliminato: 'Project deleted.',
    togliereCelle: 'Remove cells from the grid?',
    celleCadono: (n) => n === 1
      ? 'One cell of the grid uses a criterion or a level you are removing: it goes with it.'
      : `${n} cells of the grid use a criterion or a level you are removing: they go with it.`,
    togliESalva: 'Remove and save',
    togli: (titolo) => `Remove “${titolo}”`,
    criteriAiuto:
      'Each criterion is a row of the grid. Renaming it keeps the cells already given; ' +
      'removing it removes them.',
    nomeCriterio: (n) => `Name of criterion ${n}`,
    segnapostoCriterio: 'what you look at',
    nessunCriterio: 'No criteria: the grid stays empty.',
    aggiungiCriterio: 'Add a criterion',
    criteriSalvati: 'Criteria saved.',
    fasi: 'Phases',
    fasiAiuto:
      'Phases divide the project: each gathers the plan activities you assign to it. There ' +
      'is always at least one; removing one moves its activities to the previous one.',
    nomeFase: (n) => `Name of phase ${n}`,
    segnapostoFase: (n) => `Phase ${n}`,
    aggiungiFase: 'Add a phase',
    serveUnaFase: 'At least one phase is needed.',
    fasiSalvate: 'Phases saved.',
    livelli: 'Levels',
    livelliAiuto:
      'The scale used to judge each criterion, from the bottom. Renaming a level keeps ' +
      'the cells; removing it leaves them without a level.',
    coloreLivello: (n) => `Colour of level ${n}`,
    descrizioneLivello: (n) => `What level ${n} means`,
    segnapostoDescrizioneLivello: 'What reaching it means',
    colorePredefinito: 'Default',
    colori: ['Red', 'Orange', 'Green', 'Blue', 'Purple', 'Yellow', 'Light blue', 'Grey'],
    nomeLivello: (n) => `Name of level ${n}`,
    segnapostoLivello: 'achieved, partly…',
    aggiungiLivello: 'Add a level',
    serveUnLivello: 'At least one level is needed.',
    livelliSalvati: 'Levels saved.',
    nuovoCompito: 'New task',
    segnapostoCompito: 'For example: the outline of the article',
    fineComune: 'End for everyone',
    fineComuneAiuto: 'An extension moves it for one learner only.',
    fineInLezione: 'Or by the lesson',
    nessunaLezione: 'None: the date applies',
    compitoCreato: (titolo) => `Task “${titolo}” added.`,
    compitoSalvato: 'Task saved.',
    eliminareCompito: (titolo) => `Delete “${titolo}”?`,
    eliminareCompitoTesto: 'Everyone’s starts, extensions and ticks go too.',
    compitoEliminato: 'Task deleted.',
    proroga: 'Extension',
    finoAl: 'Until',
    segnapostoProroga: 'why, if needed',
    serveGiorno: 'A day is needed: dd.mm.yyyy, for example 7.9.26.',
    prorogaSalvata: (data) => `Extended until ${data}.`,
    togliProroga: 'Remove the extension',
    prorogaTolta: 'Extension removed: the end for everyone applies.',
    inizioDelCompito: 'Start of the task',
    quanti: (n) => n === 1 ? 'one person' : `${n} people`,
    cominciatoIl: 'Started on',
    inizioSalvato: (data) => `Start noted on ${data}.`,
    nuovoGiudizio: 'New comment',
    tuttaLaClasse: 'Whole class',
    nellOraDel: (data) => `In the lesson of ${data}`,
    segnapostoGiudizio: 'How it is going, what is missing, what works',
    giudizioVuoto: 'An empty comment says nothing.',
    giudizioSalvato: 'Comment saved.',
    eliminareGiudizio: 'Delete the comment?',
    giudizioEliminato: 'Comment deleted.',
    livello: 'Level',
    senzaLivello: 'No level (note only)',
    cellaSalvata: 'Cell saved.',
  },
})
