import { catalogo } from '#core/i18n/index.js'

const it = {
  modificaScaletta: 'Modifica scaletta',
  scaletta: 'Scaletta del progetto',
  fase: 'Fase del progetto',
  aiuto: 'Il contenuto si aggiorna nel progetto e nei piani collegati. Qui imposti la durata indicativa; ogni piano conserva la sua durata e i suoi allegati.',
  salvata: 'Scaletta del progetto salvata.',
  faseSparita: 'Questa fase non esiste più.',
  importa: 'Importa dal progetto',
  importaSelezionate: 'Importa le attività selezionate',
  scegliProgetto: 'Scegli un progetto',
  nessuna: 'La fase non ha attività da importare.',
  seleziona: 'Seleziona almeno un’attività.',
  selezione: (minuti: string, disponibili: string) => `${minuti} selezionati · ${disponibili} disponibili`,
  senzaOra: (minuti: string) => `${minuti} selezionati · nessuna lezione associata`,
  residuo: (n: number) => n === 1
    ? 'Un’attività rimane per un’altra lezione.'
    : `${n} attività rimangono per un’altra lezione.`,
  oltre: 'Le attività selezionate superano il tempo disponibile. Riduci la selezione o personalizza le durate nel piano.',
  sincronizzata: 'Contenuto sincronizzato con il progetto; durata e allegati rimangono in questo piano.',
  indicativa: 'Durata indicativa',
  pianificata: 'Pianificata',
  daPianificare: 'Da pianificare',
  ordine: 'Le attività mantengono l’ordine della fase. Puoi importarne una parte e proseguire in un’altra lezione.',
}

export const testi = catalogo(it, {
  de: {
    modificaScaletta: 'Ablauf bearbeiten', scaletta: 'Projektablauf', fase: 'Projektphase',
    aiuto: 'Der Inhalt wird im Projekt und in den verknüpften Plänen aktualisiert. Hier legst du die Richtdauer fest; jeder Plan behält seine Dauer und Anhänge.',
    salvata: 'Projektablauf gespeichert.', faseSparita: 'Diese Phase besteht nicht mehr.',
    importa: 'Aus dem Projekt übernehmen', importaSelezionate: 'Ausgewählte Aktivitäten übernehmen',
    scegliProgetto: 'Wähle ein Projekt', nessuna: 'Diese Phase hat keine Aktivitäten zum Übernehmen.',
    seleziona: 'Wähle mindestens eine Aktivität.',
    selezione: (m, d) => `${m} ausgewählt · ${d} verfügbar`, senzaOra: (m) => `${m} ausgewählt · keine Stunde zugeordnet`,
    residuo: (n) => n === 1 ? 'Eine Aktivität bleibt für eine weitere Stunde.' : `${n} Aktivitäten bleiben für eine weitere Stunde.`,
    oltre: 'Die ausgewählten Aktivitäten überschreiten die verfügbare Zeit. Verkleinere die Auswahl oder passe die Dauer im Plan an.',
    sincronizzata: 'Inhalt mit dem Projekt synchronisiert; Dauer und Anhänge bleiben in diesem Plan.',
    indicativa: 'Richtdauer', pianificata: 'Eingeplant', daPianificare: 'Noch einzuplanen',
    ordine: 'Die Aktivitäten behalten die Reihenfolge der Phase. Du kannst einen Teil übernehmen und in einer weiteren Stunde fortfahren.',
  },
  fr: {
    modificaScaletta: 'Modifier le déroulement', scaletta: 'Déroulement du projet', fase: 'Phase du projet',
    aiuto: 'Le contenu est mis à jour dans le projet et les plans liés. Tu définis ici la durée indicative ; chaque plan garde sa durée et ses pièces jointes.',
    salvata: 'Déroulement du projet enregistré.', faseSparita: 'Cette phase n’existe plus.',
    importa: 'Importer du projet', importaSelezionate: 'Importer les activités sélectionnées',
    scegliProgetto: 'Choisis un projet', nessuna: 'Cette phase n’a pas d’activités à importer.',
    seleziona: 'Sélectionne au moins une activité.',
    selezione: (m, d) => `${m} sélectionnées · ${d} disponibles`, senzaOra: (m) => `${m} sélectionnées · aucune leçon associée`,
    residuo: (n) => n === 1 ? 'Une activité reste pour une autre leçon.' : `${n} activités restent pour une autre leçon.`,
    oltre: 'Les activités sélectionnées dépassent le temps disponible. Réduis la sélection ou adapte les durées dans le plan.',
    sincronizzata: 'Contenu synchronisé avec le projet ; la durée et les pièces jointes restent dans ce plan.',
    indicativa: 'Durée indicative', pianificata: 'Planifiée', daPianificare: 'À planifier',
    ordine: 'Les activités gardent l’ordre de la phase. Tu peux en importer une partie et poursuivre dans une autre leçon.',
  },
  en: {
    modificaScaletta: 'Edit outline', scaletta: 'Project outline', fase: 'Project phase',
    aiuto: 'Content is updated in the project and linked plans. Set the indicative duration here; each plan keeps its own duration and attachments.',
    salvata: 'Project outline saved.', faseSparita: 'This phase no longer exists.',
    importa: 'Import from project', importaSelezionate: 'Import selected activities',
    scegliProgetto: 'Choose a project', nessuna: 'This phase has no activities to import.',
    seleziona: 'Select at least one activity.',
    selezione: (m, d) => `${m} selected · ${d} available`, senzaOra: (m) => `${m} selected · no lesson assigned`,
    residuo: (n) => n === 1 ? 'One activity remains for another lesson.' : `${n} activities remain for another lesson.`,
    oltre: 'The selected activities exceed the available time. Reduce the selection or customise the durations in the plan.',
    sincronizzata: 'Content synchronised with the project; duration and attachments stay in this plan.',
    indicativa: 'Indicative duration', pianificata: 'Planned', daPianificare: 'To be planned',
    ordine: 'Activities keep the phase order. You can import part of a phase and continue in another lesson.',
  },
})
