// I testi delle opzioni di sviluppo: la finestra (`dev.html`, `dev.ts`) e le
// voci del menu «Sviluppo» (`desktop/shell/windows/devTools.ts`). Esistono solo
// con `npm run dev`, ma passano dal catalogo come ogni parola che si legge.

import { catalogo } from '../../../../core/i18n/index.js'

const it = {
  // Il menu
  menuSviluppo: 'Sviluppo',
  menuOpzioni: 'Opzioni di sviluppo…',
  ricaricaTutte: 'Ricarica tutte le finestre',
  riavvia: 'Riavvia il main process',

  // Il telaio, in `dev.html`
  titolo: 'Opzioni di sviluppo',
  sottotitolo: 'Solo con npm run dev: nel programma installato questa finestra non c’è.',
  finestreAperte: 'Finestre aperte',
  allAvvio: 'Console all’avvio',
  allAvvioSpiega: 'La console si apre quando una finestra di quel tipo ha finito di caricare.',
  posizionePredefinita: 'Posizione della console',
  ricaricaERiavvio: 'Ricarica e riavvio',
  ricaricaAutomatica: 'Ricarica le finestre quando cambia il bundle di una pagina',
  riavviaSpiega:
    'Salva, esce e lascia che npm run dev rilanci Electron: archivio e comandi ripartono da capo.',
  cartelle: 'Cartelle e file',
  ambiente: 'Ambiente',

  // Le righe
  console: 'Console',
  posizione: 'Posizione',
  ricaricaFinestra: 'Ricarica',
  nessunaFinestra: 'Nessuna finestra aperta.',
  altraFinestra: 'Altra finestra',
  posizioni: { right: 'A destra', bottom: 'In basso', detach: 'Staccata' },
  tipi: {
    pannello: 'Registro',
    proiezione: 'Schermo per la classe',
    assistente: 'Assistente',
    benvenuto: 'Benvenuto',
    impostazioni: 'Impostazioni',
    dialogo: 'Finestra di dialogo',
    lettore: 'Lettore di PDF',
    avvio: 'Riquadro d’avvio',
    sviluppo: 'Opzioni di sviluppo',
  },
  cartellaDati: 'Dati di Regiklass-dev',
  documento: 'Documento aperto',
  nessunDocumento: 'nessun documento aperto',
  giornale: 'Giornale degli errori',
  giornaleAssente: 'non ancora scritto',
  bundle: 'Bundle delle pagine',
  variabileAssente: 'non impostata',
  nonSalvato: 'Le scelte non si salvano: sviluppo.json è bloccato.',
}

export const testi = catalogo(it, {
  de: {
    menuSviluppo: 'Entwicklung',
    menuOpzioni: 'Entwickleroptionen…',
    ricaricaTutte: 'Alle Fenster neu laden',
    riavvia: 'Hauptprozess neu starten',
    titolo: 'Entwickleroptionen',
    sottotitolo: 'Nur mit npm run dev: im installierten Programm gibt es dieses Fenster nicht.',
    finestreAperte: 'Offene Fenster',
    allAvvio: 'Konsole beim Start',
    allAvvioSpiega: 'Die Konsole öffnet sich, wenn ein Fenster dieser Art fertig geladen hat.',
    posizionePredefinita: 'Position der Konsole',
    ricaricaERiavvio: 'Neu laden und neu starten',
    ricaricaAutomatica: 'Fenster neu laden, wenn sich das Bundle einer Seite ändert',
    riavviaSpiega:
      'Speichert, beendet und lässt npm run dev Electron neu starten: Archiv und Befehle beginnen von vorn.',
    cartelle: 'Ordner und Dateien',
    ambiente: 'Umgebung',
    console: 'Konsole',
    posizione: 'Position',
    ricaricaFinestra: 'Neu laden',
    nessunaFinestra: 'Kein Fenster offen.',
    altraFinestra: 'Anderes Fenster',
    posizioni: { right: 'Rechts', bottom: 'Unten', detach: 'Abgetrennt' },
    tipi: {
      pannello: 'Klassenbuch',
      proiezione: 'Bildschirm für die Klasse',
      assistente: 'Assistent',
      benvenuto: 'Willkommen',
      impostazioni: 'Einstellungen',
      dialogo: 'Dialogfenster',
      lettore: 'PDF-Anzeige',
      avvio: 'Startfenster',
      sviluppo: 'Entwickleroptionen',
    },
    cartellaDati: 'Daten von Regiklass-dev',
    documento: 'Geöffnetes Dokument',
    nessunDocumento: 'kein Dokument geöffnet',
    giornale: 'Fehlerprotokoll',
    giornaleAssente: 'noch nicht geschrieben',
    bundle: 'Bundles der Seiten',
    variabileAssente: 'nicht gesetzt',
    nonSalvato: 'Die Auswahl wird nicht gespeichert: sviluppo.json ist gesperrt.',
  },
  fr: {
    menuSviluppo: 'Développement',
    menuOpzioni: 'Options de développement…',
    ricaricaTutte: 'Recharger toutes les fenêtres',
    riavvia: 'Redémarrer le processus principal',
    titolo: 'Options de développement',
    sottotitolo: 'Seulement avec npm run dev : le programme installé n’a pas cette fenêtre.',
    finestreAperte: 'Fenêtres ouvertes',
    allAvvio: 'Console au démarrage',
    allAvvioSpiega: 'La console s’ouvre quand une fenêtre de ce type a fini de charger.',
    posizionePredefinita: 'Position de la console',
    ricaricaERiavvio: 'Rechargement et redémarrage',
    ricaricaAutomatica: 'Recharger les fenêtres quand le bundle d’une page change',
    riavviaSpiega:
      'Enregistre, quitte et laisse npm run dev relancer Electron : archive et commandes repartent de zéro.',
    cartelle: 'Dossiers et fichiers',
    ambiente: 'Environnement',
    console: 'Console',
    posizione: 'Position',
    ricaricaFinestra: 'Recharger',
    nessunaFinestra: 'Aucune fenêtre ouverte.',
    altraFinestra: 'Autre fenêtre',
    posizioni: { right: 'À droite', bottom: 'En bas', detach: 'Détachée' },
    tipi: {
      pannello: 'Registre',
      proiezione: 'Écran pour la classe',
      assistente: 'Assistant',
      benvenuto: 'Bienvenue',
      impostazioni: 'Réglages',
      dialogo: 'Boîte de dialogue',
      lettore: 'Lecteur PDF',
      avvio: 'Écran de démarrage',
      sviluppo: 'Options de développement',
    },
    cartellaDati: 'Données de Regiklass-dev',
    documento: 'Document ouvert',
    nessunDocumento: 'aucun document ouvert',
    giornale: 'Journal des erreurs',
    giornaleAssente: 'pas encore écrit',
    bundle: 'Bundles des pages',
    variabileAssente: 'non définie',
    nonSalvato: 'Les choix ne sont pas enregistrés : sviluppo.json est verrouillé.',
  },
  en: {
    menuSviluppo: 'Development',
    menuOpzioni: 'Developer options…',
    ricaricaTutte: 'Reload all windows',
    riavvia: 'Restart the main process',
    titolo: 'Developer options',
    sottotitolo: 'Only with npm run dev: the installed program has no such window.',
    finestreAperte: 'Open windows',
    allAvvio: 'Console at startup',
    allAvvioSpiega: 'The console opens when a window of that kind has finished loading.',
    posizionePredefinita: 'Console position',
    ricaricaERiavvio: 'Reload and restart',
    ricaricaAutomatica: 'Reload the windows when a page bundle changes',
    riavviaSpiega:
      'Saves, quits and lets npm run dev relaunch Electron: archive and commands start afresh.',
    cartelle: 'Folders and files',
    ambiente: 'Environment',
    console: 'Console',
    posizione: 'Position',
    ricaricaFinestra: 'Reload',
    nessunaFinestra: 'No window open.',
    altraFinestra: 'Other window',
    posizioni: { right: 'Right', bottom: 'Bottom', detach: 'Detached' },
    tipi: {
      pannello: 'Register',
      proiezione: 'Screen for the class',
      assistente: 'Assistant',
      benvenuto: 'Welcome',
      impostazioni: 'Settings',
      dialogo: 'Dialogue box',
      lettore: 'PDF reader',
      avvio: 'Startup screen',
      sviluppo: 'Developer options',
    },
    cartellaDati: 'Regiklass-dev data',
    documento: 'Open document',
    nessunDocumento: 'no document open',
    giornale: 'Error log',
    giornaleAssente: 'not written yet',
    bundle: 'Page bundles',
    variabileAssente: 'not set',
    nonSalvato: 'The choices are not saved: sviluppo.json is locked.',
  },
})
