// I testi degli schemi d'ingresso: i rifiuti («Serve un numero.»), gli aiuti
// predefiniti dei campi e la forma in breve della riga di comando.
// Si leggono quando si convalida o si pubblica, mai al caricamento: gli schemi
// si compongono una volta sola, a livello di modulo.

import { catalogo } from '../i18n/index.js'

const it = {
  serveTesto: 'Serve del testo.',
  testoAlmeno: (quanti: number) => `Serve del testo di almeno ${quanti} caratteri.`,
  testoOltre: (quanti: number) => `Il testo supera i ${quanti} caratteri.`,
  formaAttesa: (valore: string) => `«${valore}» non è nella forma attesa.`,
  serveNumero: 'Serve un numero.',
  serveIntero: 'Serve un numero intero.',
  numeroAlmeno: (minimo: number) => `Il numero deve essere almeno ${minimo}.`,
  numeroAlPiu: (massimo: number) => `Il numero non può superare ${massimo}.`,
  serveBooleano: 'Serve vero o falso.',
  /** I valori ammessi arrivano già in fila, separati da virgole. */
  serveUnoFra: (valori: string) => `Serve uno fra: ${valori}.`,
  aiutoIdentificatore:
    'Identificatore di una voce del registro: si copia da un elenco, non si inventa',
  serveIdentificatore: 'Serve un identificatore.',
  identificatoreLungo: 'Identificatore troppo lungo.',
  aiutoData: 'Data di calendario',
  serveData: 'Serve una data nella forma AAAA-MM-GG.',
  giornoInesistente: (valore: string) => `«${valore}» non è un giorno che esiste.`,
  aiutoOra: 'Ora del giorno',
  serveOra: 'Serve un’ora nella forma HH:MM.',
  serveElenco: 'Serve un elenco.',
  elencoAlmeno: (minimo: number) => `L’elenco deve avere almeno ${minimo} voci.`,
  elencoAlPiu: (massimo: number) => `L’elenco non può avere più di ${massimo} voci.`,
  serveOggetto: 'Serve un oggetto.',
  campoSconosciuto: (chiave: string) => `Questa procedura non ha un campo «${chiave}».`,
  serveValore: 'Serve un valore.',
  /** `cosa` è il nome dell'entità con la maiuscola: «Lezione», «Piano lezione». */
  aiutoEntita: (cosa: string) => `${cosa} intera, come la compone il dominio`,
  serveEntita: (cosa: string) => `Serve ${cosa.toLowerCase()}.`,
  entitaSenzaId: (cosa: string) => `${cosa} senza identificatore.`,
  entitaFuoriForma: (cosa: string) => `${cosa} non è nella forma attesa.`,
  /** La forma in breve, per l'aiuto della riga di comando. */
  breve: {
    oNullo: (forma: string) => `${forma} o nullo`,
    testo: 'testo',
    testoAdEsempio: (esempio: string) => `testo (es. ${esempio})`,
    intero: 'intero',
    numero: 'numero',
    veroFalso: 'vero/falso',
    elencoDi: (forma: string) => `elenco di ${forma}`,
    nullo: 'nullo',
    qualunque: 'qualunque',
  },
}

export const testi = catalogo(it, {
  de: {
    serveTesto: 'Erwartet wird Text.',
    testoAlmeno: (quanti) => `Erwartet wird Text mit mindestens ${quanti} Zeichen.`,
    testoOltre: (quanti) => `Der Text ist länger als ${quanti} Zeichen.`,
    formaAttesa: (valore) => `«${valore}» hat nicht die erwartete Form.`,
    serveNumero: 'Erwartet wird eine Zahl.',
    serveIntero: 'Erwartet wird eine ganze Zahl.',
    numeroAlmeno: (minimo) => `Die Zahl muss mindestens ${minimo} sein.`,
    numeroAlPiu: (massimo) => `Die Zahl darf ${massimo} nicht überschreiten.`,
    serveBooleano: 'Erwartet wird wahr oder falsch.',
    serveUnoFra: (valori) => `Erwartet wird einer dieser Werte: ${valori}.`,
    aiutoIdentificatore:
      'Kennung eines Eintrags im Klassenbuch: Sie wird aus einer Liste kopiert, nicht erfunden',
    serveIdentificatore: 'Erwartet wird eine Kennung.',
    identificatoreLungo: 'Die Kennung ist zu lang.',
    aiutoData: 'Kalenderdatum',
    serveData: 'Erwartet wird ein Datum in der Form JJJJ-MM-TT.',
    giornoInesistente: (valore) => `«${valore}» ist kein Tag, den es gibt.`,
    aiutoOra: 'Uhrzeit',
    serveOra: 'Erwartet wird eine Uhrzeit in der Form HH:MM.',
    serveElenco: 'Erwartet wird eine Liste.',
    elencoAlmeno: (minimo) => `Die Liste muss mindestens ${minimo} Einträge haben.`,
    elencoAlPiu: (massimo) => `Die Liste darf höchstens ${massimo} Einträge haben.`,
    serveOggetto: 'Erwartet wird ein Objekt.',
    campoSconosciuto: (chiave) => `Diese Prozedur hat kein Feld «${chiave}».`,
    serveValore: 'Erwartet wird ein Wert.',
    aiutoEntita: (cosa) => `${cosa}, vollständig, in der Form des Datenmodells`,
    serveEntita: (cosa) => `Erwartet wird: ${cosa}.`,
    entitaSenzaId: (cosa) => `${cosa} ohne Kennung.`,
    entitaFuoriForma: (cosa) => `${cosa} hat nicht die erwartete Form.`,
    breve: {
      oNullo: (forma) => `${forma} oder null`,
      testo: 'Text',
      testoAdEsempio: (esempio) => `Text (z. B. ${esempio})`,
      intero: 'ganze Zahl',
      numero: 'Zahl',
      veroFalso: 'wahr/falsch',
      elencoDi: (forma) => `Liste von ${forma}`,
      nullo: 'null',
      qualunque: 'beliebig',
    },
  },
  fr: {
    serveTesto: 'Il faut du texte.',
    testoAlmeno: (quanti) => `Il faut un texte d’au moins ${quanti} caractères.`,
    testoOltre: (quanti) => `Le texte dépasse ${quanti} caractères.`,
    formaAttesa: (valore) => `« ${valore} » n’a pas la forme attendue.`,
    serveNumero: 'Il faut un nombre.',
    serveIntero: 'Il faut un nombre entier.',
    numeroAlmeno: (minimo) => `Le nombre doit valoir au moins ${minimo}.`,
    numeroAlPiu: (massimo) => `Le nombre ne peut pas dépasser ${massimo}.`,
    serveBooleano: 'Il faut vrai ou faux.',
    serveUnoFra: (valori) => `Il faut l’une de ces valeurs : ${valori}.`,
    aiutoIdentificatore:
      'Identifiant d’un élément du registre : il se copie depuis une liste, il ne s’invente pas',
    serveIdentificatore: 'Il faut un identifiant.',
    identificatoreLungo: 'Identifiant trop long.',
    aiutoData: 'Date du calendrier',
    serveData: 'Il faut une date sous la forme AAAA-MM-JJ.',
    giornoInesistente: (valore) => `« ${valore} » n’est pas un jour qui existe.`,
    aiutoOra: 'Heure de la journée',
    serveOra: 'Il faut une heure sous la forme HH:MM.',
    serveElenco: 'Il faut une liste.',
    elencoAlmeno: (minimo) => `La liste doit compter au moins ${minimo} éléments.`,
    elencoAlPiu: (massimo) => `La liste ne peut pas compter plus de ${massimo} éléments.`,
    serveOggetto: 'Il faut un objet.',
    campoSconosciuto: (chiave) => `Cette procédure n’a pas de champ « ${chiave} ».`,
    serveValore: 'Il faut une valeur.',
    aiutoEntita: (cosa) => `${cosa} en entier, dans la forme que lui donne le modèle de données`,
    serveEntita: (cosa) => `Il faut : ${cosa}.`,
    entitaSenzaId: (cosa) => `${cosa} sans identifiant.`,
    entitaFuoriForma: (cosa) => `${cosa} n’a pas la forme attendue.`,
    breve: {
      oNullo: (forma) => `${forma} ou null`,
      testo: 'texte',
      testoAdEsempio: (esempio) => `texte (p. ex. ${esempio})`,
      intero: 'entier',
      numero: 'nombre',
      veroFalso: 'vrai/faux',
      elencoDi: (forma) => `liste de ${forma}`,
      nullo: 'null',
      qualunque: 'quelconque',
    },
  },
  en: {
    serveTesto: 'Text is required.',
    testoAlmeno: (quanti) => `Text of at least ${quanti} characters is required.`,
    testoOltre: (quanti) => `The text is longer than ${quanti} characters.`,
    formaAttesa: (valore) => `“${valore}” is not in the expected form.`,
    serveNumero: 'A number is required.',
    serveIntero: 'A whole number is required.',
    numeroAlmeno: (minimo) => `The number must be at least ${minimo}.`,
    numeroAlPiu: (massimo) => `The number cannot be more than ${massimo}.`,
    serveBooleano: 'True or false is required.',
    serveUnoFra: (valori) => `One of these is required: ${valori}.`,
    aiutoIdentificatore:
      'Identifier of an entry in the register: copy it from a list, never make one up',
    serveIdentificatore: 'An identifier is required.',
    identificatoreLungo: 'Identifier too long.',
    aiutoData: 'Calendar date',
    serveData: 'A date in the form YYYY-MM-DD is required.',
    giornoInesistente: (valore) => `“${valore}” is not a day that exists.`,
    aiutoOra: 'Time of day',
    serveOra: 'A time in the form HH:MM is required.',
    serveElenco: 'A list is required.',
    elencoAlmeno: (minimo) => `The list must have at least ${minimo} items.`,
    elencoAlPiu: (massimo) => `The list cannot have more than ${massimo} items.`,
    serveOggetto: 'An object is required.',
    campoSconosciuto: (chiave) => `This procedure has no field “${chiave}”.`,
    serveValore: 'A value is required.',
    aiutoEntita: (cosa) => `${cosa}, complete, as the data model puts it together`,
    serveEntita: (cosa) => `Required: ${cosa}.`,
    entitaSenzaId: (cosa) => `${cosa} without an identifier.`,
    entitaFuoriForma: (cosa) => `${cosa} is not in the expected form.`,
    breve: {
      oNullo: (forma) => `${forma} or null`,
      testo: 'text',
      testoAdEsempio: (esempio) => `text (e.g. ${esempio})`,
      intero: 'integer',
      numero: 'number',
      veroFalso: 'true/false',
      elencoDi: (forma) => `list of ${forma}`,
      nullo: 'null',
      qualunque: 'any',
    },
  },
})
