// Il lessico del registro in tutte le lingue: i nomi delle cose e le voci
// delle tendine. L'italiano viene da `lexicon.ts`; le altre lingue qui, termine
// per termine, con il genere (`m`, `f`, e `n` per il tedesco).
//
// Niente grammatica: articoli e accordi di `lexicon.ts` sono italiani; le
// altre lingue scrivono le frasi intere nei loro cataloghi. Maiuscola (`Uno`,
// `Molti`) e forma corta (`corto`) valgono per tutte. Le sigle dell'appello
// (`SIGLE_PRESENZA`) non si traducono: foglio e schermo devono combaciare fra
// colleghi di lingue diverse.
//
// Si legge con `lessico()` al momento dell'uso: `Uno(lessico().pif)`.

import { catalogo } from '../i18n/index.js'
import {
  CARTE,
  CATEGORIE_DOCUMENTO,
  DOCUMENTO_SCHEDE,
  ETICHETTE_TELEFONO,
  LEZIONE,
  PERSONE,
  RAGGRUPPAMENTI,
  RUOLI_ALLEGATO,
  SCUOLA,
  STATI_LEZIONE,
  TIPI_ATTIVITA,
  TIPI_CONSEGNA,
  TIPI_OSSERVAZIONE,
  TIPI_VALUTAZIONE,
  VALUTAZIONE,
  VOCI_PRESENZA,
  type Termine,
} from './lexicon.js'
import type { StatoPresenza } from './models.js'

/** Un termine, con il genere largo: il tedesco ha anche il neutro. */
type Parola = Omit<Termine, 'genere'> & { readonly genere: 'm' | 'f' | 'n' }

/** Le parole dell'appello, senza le sigle: quelle non cambiano con la lingua. */
const presenze = Object.fromEntries(
  Object.entries(VOCI_PRESENZA).map(([stato, voce]) => [stato, voce.nome]),
) as Record<StatoPresenza, string>

const it = {
  ...(PERSONE as Record<keyof typeof PERSONE, Parola>),
  ...(SCUOLA as Record<keyof typeof SCUOLA, Parola>),
  ...(LEZIONE as Record<keyof typeof LEZIONE, Parola>),
  ...(VALUTAZIONE as Record<keyof typeof VALUTAZIONE, Parola>),
  ...(CARTE as Record<keyof typeof CARTE, Parola>),
  /** Come si chiama, nel nome del file, la famiglia di fogli stampati una per persona. */
  documentoSchede: DOCUMENTO_SCHEDE,
  presenze,
  etichetteTelefono: { ...ETICHETTE_TELEFONO },
  tipiAttivita: { ...TIPI_ATTIVITA },
  raggruppamenti: { ...RAGGRUPPAMENTI },
  tipiValutazione: { ...TIPI_VALUTAZIONE },
  tipiOsservazione: { ...TIPI_OSSERVAZIONE },
  statiLezione: { ...STATI_LEZIONE },
  tipiConsegna: { ...TIPI_CONSEGNA },
  categorieDocumento: { ...CATEGORIE_DOCUMENTO },
  ruoliAllegato: { ...RUOLI_ALLEGATO },
}

export const lessico = catalogo(it, {
  de: {
    // Die Wörter der Berufsbildung in der Schweiz: «Lernende», «Lehrbetrieb»,
    // «Lektion» für die 45-Minuten-Einheit.
    pif: { singolare: 'Lernende', plurale: 'Lernende', genere: 'f', breve: 'LP' },
    docente: { singolare: 'Lehrperson', plurale: 'Lehrpersonen', genere: 'f' },
    docenteClasse: { singolare: 'Klassenlehrperson', plurale: 'Klassenlehrpersonen', genere: 'f' },
    rappresentante: {
      singolare: 'gesetzliche Vertretung',
      plurale: 'gesetzliche Vertretungen',
      genere: 'f',
      breve: 'Ges. Vertretung',
    },
    azienda: { singolare: 'Lehrbetrieb', plurale: 'Lehrbetriebe', genere: 'm', breve: 'Betrieb' },
    datore: { singolare: 'Arbeitgeber', plurale: 'Arbeitgeber', genere: 'm', breve: 'Arbeitgeber' },
    classe: { singolare: 'Klasse', plurale: 'Klassen', genere: 'f' },
    corso: { singolare: 'Kurs', plurale: 'Kurse', genere: 'm' },
    materia: { singolare: 'Fach', plurale: 'Fächer', genere: 'n' },
    annoScolastico: { singolare: 'Schuljahr', plurale: 'Schuljahre', genere: 'n', breve: 'Jahr' },
    semestre: { singolare: 'Semester', plurale: 'Semester', genere: 'n' },
    periodo: { singolare: 'Zeitraum', plurale: 'Zeiträume', genere: 'm' },
    vacanza: { singolare: 'Ferien', plurale: 'Ferien', genere: 'f' },
    lezione: { singolare: 'Stunde', plurale: 'Stunden', genere: 'f' },
    ora: { singolare: 'Stunde', plurale: 'Stunden', genere: 'f', breve: 'Std.' },
    unitaDidattica: { singolare: 'Lektion', plurale: 'Lektionen', genere: 'f', breve: 'Lekt.' },
    fascia: { singolare: 'Zeitfenster', plurale: 'Zeitfenster', genere: 'n', breve: 'Fenster' },
    pausa: { singolare: 'Pause', plurale: 'Pausen', genere: 'f' },
    orario: { singolare: 'Stundenplan', plurale: 'Stundenpläne', genere: 'm' },
    pianoLezione: { singolare: 'Unterrichtsplan', plurale: 'Unterrichtspläne', genere: 'm', breve: 'Plan' },
    attivita: { singolare: 'Aktivität', plurale: 'Aktivitäten', genere: 'f' },
    tappa: { singolare: 'Etappe', plurale: 'Etappen', genere: 'f' },
    scaletta: { singolare: 'Ablauf', plurale: 'Abläufe', genere: 'm' },
    risorsa: { singolare: 'Ressource', plurale: 'Ressourcen', genere: 'f' },
    momento: {
      singolare: 'Leistungsbeurteilung',
      plurale: 'Leistungsbeurteilungen',
      genere: 'f',
      breve: 'Beurteilung',
    },
    prova: { singolare: 'Prüfung', plurale: 'Prüfungen', genere: 'f' },
    voto: { singolare: 'Note', plurale: 'Noten', genere: 'f' },
    media: { singolare: 'Durchschnitt', plurale: 'Durchschnitte', genere: 'm' },
    nota: { singolare: 'Semesternote', plurale: 'Semesternoten', genere: 'f', breve: 'Note' },
    scala: { singolare: 'Notenskala', plurale: 'Notenskalen', genere: 'f', breve: 'Skala' },
    recupero: { singolare: 'Nachprüfung', plurale: 'Nachprüfungen', genere: 'f' },
    riconsegna: { singolare: 'Rückgabe', plurale: 'Rückgaben', genere: 'f' },
    osservazione: { singolare: 'Beobachtung', plurale: 'Beobachtungen', genere: 'f' },
    consegna: { singolare: 'Auftrag', plurale: 'Aufträge', genere: 'm' },
    check: { singolare: 'Check', plurale: 'Checks', genere: 'm' },
    colonnaCheck: { singolare: 'Check-Spalte', plurale: 'Check-Spalten', genere: 'f', breve: 'Spalte' },
    documento: { singolare: 'Dokument', plurale: 'Dokumente', genere: 'n' },
    calendario: { singolare: 'Kalender', plurale: 'Kalender', genere: 'm' },
    allegato: { singolare: 'Anhang', plurale: 'Anhänge', genere: 'm' },
    fascicolo: { singolare: 'Klassendossier', plurale: 'Klassendossiers', genere: 'n', breve: 'Dossier' },
    rapporto: { singolare: 'Bericht', plurale: 'Berichte', genere: 'm' },
    comunicazione: { singolare: 'Mitteilung', plurale: 'Mitteilungen', genere: 'f' },
    email: { singolare: 'E-Mail', plurale: 'E-Mails', genere: 'f' },
    bozza: { singolare: 'Entwurf', plurale: 'Entwürfe', genere: 'm' },
    pendenza: { singolare: 'Pendenz', plurale: 'Pendenzen', genere: 'f' },
    promemoria: { singolare: 'Erinnerung', plurale: 'Erinnerungen', genere: 'f' },
    smistamento: { singolare: 'Zuordnung', plurale: 'Zuordnungen', genere: 'f' },
    documentoSchede: 'Personenblatt',
    presenze: {
      'non-impostato': 'Nicht erfasst',
      presente: 'Anwesend',
      assente: 'Abwesend',
      ritardo: 'Verspätet',
      esonerato: 'Dispensiert',
    },
    etichetteTelefono: {
      cellulare: 'Handy',
      casa: 'Privat',
      lavoro: 'Geschäft',
      centralino: 'Zentrale',
      altro: 'Andere',
    },
    tipiAttivita: {
      'docenza-di-classe': 'Klassenlehrer-Aufgaben',
      introduzione: 'Einführung',
      spiegazione: 'Erklärung',
      esercizio: 'Übung',
      laboratorio: 'Labor',
      discussione: 'Diskussion',
      gruppo: 'Gruppenarbeit',
      verifica: 'Prüfung',
      ripasso: 'Repetition',
      compito: 'Aufgabe',
      altro: 'Anderes',
    },
    raggruppamenti: {
      plenaria: 'Ganze Klasse',
      individuale: 'Einzeln',
      coppie: 'Zu zweit',
      gruppi: 'In Gruppen',
    },
    tipiValutazione: {
      scritto: 'Schriftlich',
      orale: 'Mündlich',
      pratico: 'Praktisch',
      progetto: 'Projekt',
      compito: 'Hausaufgabe',
      osservazione: 'Beobachtung',
    },
    tipiOsservazione: {
      nota: 'Notiz',
      merito: 'Lob',
      disciplina: 'Disziplin',
      compiti: 'Hausaufgaben',
      materiale: 'Material',
      colloquio: 'Gespräch',
    },
    statiLezione: {
      pianificata: 'Geplant',
      svolta: 'Gehalten',
      annullata: 'Ausgefallen',
    },
    tipiConsegna: {
      compito: 'Aufgabe',
      studio: 'Lernen',
      materiale: 'Mitzubringendes Material',
      consegna: 'Abzugeben',
      preparazione: 'Vorbereitung (meine)',
      amministrativo: 'Administratives',
      altro: 'Anderes',
    },
    categorieDocumento: {
      certificato: 'Zeugnis',
      autorizzazione: 'Bewilligung',
      giustificazione: 'Entschuldigung',
      modulo: 'Formular',
      altro: 'Anderes',
    },
    ruoliAllegato: {
      verifica: 'Aufgabenblatt',
      soluzione: 'Lösung',
      prova: 'Korrigierte Prüfung',
      recupero: 'Aufgabenblatt der Nachprüfung',
      'recupero-soluzione': 'Lösung der Nachprüfung',
    },
  },
  fr: {
    // Les mots de la formation professionnelle en Suisse romande : « personne
    // en formation », « entreprise formatrice », « période » pour l'unité de
    // 45 minutes.
    pif: { singolare: 'personne en formation', plurale: 'personnes en formation', genere: 'f', breve: 'PeF' },
    docente: { singolare: 'enseignant', plurale: 'enseignants', genere: 'm' },
    docenteClasse: { singolare: 'maître de classe', plurale: 'maîtres de classe', genere: 'm' },
    rappresentante: {
      singolare: 'représentant légal',
      plurale: 'représentants légaux',
      genere: 'm',
      breve: 'Repr. légal',
    },
    azienda: {
      singolare: 'entreprise formatrice',
      plurale: 'entreprises formatrices',
      genere: 'f',
      breve: 'Entreprise',
    },
    datore: { singolare: 'employeur', plurale: 'employeurs', genere: 'm', breve: 'Employeur' },
    classe: { singolare: 'classe', plurale: 'classes', genere: 'f' },
    corso: { singolare: 'cours', plurale: 'cours', genere: 'm' },
    materia: { singolare: 'branche', plurale: 'branches', genere: 'f' },
    annoScolastico: { singolare: 'année scolaire', plurale: 'années scolaires', genere: 'f', breve: 'Année' },
    semestre: { singolare: 'semestre', plurale: 'semestres', genere: 'm' },
    periodo: { singolare: 'période', plurale: 'périodes', genere: 'f' },
    vacanza: { singolare: 'vacances', plurale: 'vacances', genere: 'f' },
    lezione: { singolare: 'leçon', plurale: 'leçons', genere: 'f' },
    ora: { singolare: 'leçon', plurale: 'leçons', genere: 'f', breve: 'Leçon' },
    unitaDidattica: { singolare: 'période', plurale: 'périodes', genere: 'f', breve: 'Pér.' },
    fascia: { singolare: 'plage horaire', plurale: 'plages horaires', genere: 'f', breve: 'Plage' },
    pausa: { singolare: 'pause', plurale: 'pauses', genere: 'f' },
    orario: { singolare: 'horaire', plurale: 'horaires', genere: 'm' },
    pianoLezione: { singolare: 'plan de leçon', plurale: 'plans de leçon', genere: 'm', breve: 'Plan' },
    attivita: { singolare: 'activité', plurale: 'activités', genere: 'f' },
    tappa: { singolare: 'étape', plurale: 'étapes', genere: 'f' },
    scaletta: { singolare: 'déroulement', plurale: 'déroulements', genere: 'm' },
    risorsa: { singolare: 'ressource', plurale: 'ressources', genere: 'f' },
    momento: { singolare: 'évaluation', plurale: 'évaluations', genere: 'f', breve: 'Évaluation' },
    prova: { singolare: 'épreuve', plurale: 'épreuves', genere: 'f' },
    voto: { singolare: 'note', plurale: 'notes', genere: 'f' },
    media: { singolare: 'moyenne', plurale: 'moyennes', genere: 'f' },
    nota: { singolare: 'note semestrielle', plurale: 'notes semestrielles', genere: 'f', breve: 'Note' },
    scala: { singolare: 'barème', plurale: 'barèmes', genere: 'm', breve: 'Barème' },
    recupero: { singolare: 'rattrapage', plurale: 'rattrapages', genere: 'm' },
    riconsegna: { singolare: 'restitution', plurale: 'restitutions', genere: 'f' },
    osservazione: { singolare: 'observation', plurale: 'observations', genere: 'f' },
    consegna: { singolare: 'devoir', plurale: 'devoirs', genere: 'm' },
    check: { singolare: 'check', plurale: 'checks', genere: 'm' },
    colonnaCheck: { singolare: 'colonne du check', plurale: 'colonnes du check', genere: 'f', breve: 'Colonne' },
    documento: { singolare: 'document', plurale: 'documents', genere: 'm' },
    calendario: { singolare: 'calendrier', plurale: 'calendriers', genere: 'm' },
    allegato: { singolare: 'pièce jointe', plurale: 'pièces jointes', genere: 'f' },
    fascicolo: { singolare: 'dossier de classe', plurale: 'dossiers de classe', genere: 'm', breve: 'Dossier' },
    rapporto: { singolare: 'rapport', plurale: 'rapports', genere: 'm' },
    comunicazione: { singolare: 'communication', plurale: 'communications', genere: 'f' },
    email: { singolare: 'e-mail', plurale: 'e-mails', genere: 'm' },
    bozza: { singolare: 'brouillon', plurale: 'brouillons', genere: 'm' },
    pendenza: { singolare: 'tâche en suspens', plurale: 'tâches en suspens', genere: 'f' },
    promemoria: { singolare: 'rappel', plurale: 'rappels', genere: 'm' },
    smistamento: { singolare: 'tri', plurale: 'tris', genere: 'm' },
    documentoSchede: 'Fiche PeF',
    presenze: {
      'non-impostato': 'Non saisi',
      presente: 'Présent',
      assente: 'Absent',
      ritardo: 'En retard',
      esonerato: 'Dispensé',
    },
    etichetteTelefono: {
      cellulare: 'portable',
      casa: 'domicile',
      lavoro: 'travail',
      centralino: 'central',
      altro: 'autre',
    },
    tipiAttivita: {
      'docenza-di-classe': 'Maîtrise de classe',
      introduzione: 'Introduction',
      spiegazione: 'Explication',
      esercizio: 'Exercice',
      laboratorio: 'Laboratoire',
      discussione: 'Discussion',
      gruppo: 'Travail de groupe',
      verifica: 'Contrôle',
      ripasso: 'Révision',
      compito: 'Devoir',
      altro: 'Autre',
    },
    raggruppamenti: {
      plenaria: 'Toute la classe',
      individuale: 'Seuls',
      coppie: 'Par deux',
      gruppi: 'En groupes',
    },
    tipiValutazione: {
      scritto: 'Écrit',
      orale: 'Oral',
      pratico: 'Pratique',
      progetto: 'Projet',
      compito: 'Devoir à la maison',
      osservazione: 'Observation',
    },
    tipiOsservazione: {
      nota: 'Note',
      merito: 'Mérite',
      disciplina: 'Discipline',
      compiti: 'Devoirs',
      materiale: 'Matériel',
      colloquio: 'Entretien',
    },
    statiLezione: {
      pianificata: 'Prévue',
      svolta: 'Donnée',
      annullata: 'Annulée',
    },
    tipiConsegna: {
      compito: 'Devoir',
      studio: 'Étude',
      materiale: 'Matériel à apporter',
      consegna: 'À rendre',
      preparazione: 'Préparation (la mienne)',
      amministrativo: 'Administratif',
      altro: 'Autre',
    },
    categorieDocumento: {
      certificato: 'Certificat',
      autorizzazione: 'Autorisation',
      giustificazione: 'Justificatif',
      modulo: 'Formulaire',
      altro: 'Autre',
    },
    ruoliAllegato: {
      verifica: 'Énoncé',
      soluzione: 'Corrigé',
      prova: 'Épreuve corrigée',
      recupero: 'Énoncé du rattrapage',
      'recupero-soluzione': 'Corrigé du rattrapage',
    },
  },
  en: {
    pif: { singolare: 'learner', plurale: 'learners', genere: 'm', breve: 'Learner' },
    docente: { singolare: 'teacher', plurale: 'teachers', genere: 'm' },
    docenteClasse: { singolare: 'class teacher', plurale: 'class teachers', genere: 'm' },
    rappresentante: {
      singolare: 'legal guardian',
      plurale: 'legal guardians',
      genere: 'm',
      breve: 'Guardian',
    },
    azienda: {
      singolare: 'training company',
      plurale: 'training companies',
      genere: 'f',
      breve: 'Company',
    },
    datore: { singolare: 'employer', plurale: 'employers', genere: 'm', breve: 'Employer' },
    classe: { singolare: 'class', plurale: 'classes', genere: 'f' },
    corso: { singolare: 'course', plurale: 'courses', genere: 'm' },
    materia: { singolare: 'subject', plurale: 'subjects', genere: 'f' },
    annoScolastico: { singolare: 'school year', plurale: 'school years', genere: 'm', breve: 'Year' },
    semestre: { singolare: 'semester', plurale: 'semesters', genere: 'm' },
    periodo: { singolare: 'period', plurale: 'periods', genere: 'm' },
    vacanza: { singolare: 'holiday', plurale: 'holidays', genere: 'f' },
    lezione: { singolare: 'lesson', plurale: 'lessons', genere: 'f' },
    ora: { singolare: 'lesson', plurale: 'lessons', genere: 'f', breve: 'Lesson' },
    unitaDidattica: { singolare: 'period', plurale: 'periods', genere: 'f', breve: 'Per.' },
    fascia: { singolare: 'time slot', plurale: 'time slots', genere: 'f', breve: 'Slot' },
    pausa: { singolare: 'break', plurale: 'breaks', genere: 'f' },
    orario: { singolare: 'timetable', plurale: 'timetables', genere: 'm' },
    pianoLezione: { singolare: 'lesson plan', plurale: 'lesson plans', genere: 'm', breve: 'Plan' },
    attivita: { singolare: 'activity', plurale: 'activities', genere: 'f' },
    tappa: { singolare: 'step', plurale: 'steps', genere: 'f' },
    scaletta: { singolare: 'outline', plurale: 'outlines', genere: 'f' },
    risorsa: { singolare: 'resource', plurale: 'resources', genere: 'f' },
    momento: { singolare: 'assessment', plurale: 'assessments', genere: 'm', breve: 'Assessment' },
    prova: { singolare: 'test', plurale: 'tests', genere: 'f' },
    voto: { singolare: 'grade', plurale: 'grades', genere: 'm' },
    media: { singolare: 'average', plurale: 'averages', genere: 'f' },
    nota: { singolare: 'semester grade', plurale: 'semester grades', genere: 'f', breve: 'Grade' },
    scala: { singolare: 'grading scale', plurale: 'grading scales', genere: 'f', breve: 'Scale' },
    recupero: { singolare: 'resit', plurale: 'resits', genere: 'm' },
    riconsegna: { singolare: 'return', plurale: 'returns', genere: 'f' },
    osservazione: { singolare: 'observation', plurale: 'observations', genere: 'f' },
    consegna: { singolare: 'assignment', plurale: 'assignments', genere: 'f' },
    check: { singolare: 'check', plurale: 'checks', genere: 'm' },
    colonnaCheck: { singolare: 'check column', plurale: 'check columns', genere: 'f', breve: 'Column' },
    documento: { singolare: 'document', plurale: 'documents', genere: 'm' },
    calendario: { singolare: 'calendar', plurale: 'calendars', genere: 'm' },
    allegato: { singolare: 'attachment', plurale: 'attachments', genere: 'm' },
    fascicolo: { singolare: 'class file', plurale: 'class files', genere: 'm', breve: 'File' },
    rapporto: { singolare: 'report', plurale: 'reports', genere: 'm' },
    comunicazione: { singolare: 'message', plurale: 'messages', genere: 'f' },
    email: { singolare: 'email', plurale: 'emails', genere: 'f' },
    bozza: { singolare: 'draft', plurale: 'drafts', genere: 'f' },
    pendenza: { singolare: 'pending item', plurale: 'pending items', genere: 'f' },
    promemoria: { singolare: 'reminder', plurale: 'reminders', genere: 'm' },
    smistamento: { singolare: 'sorting', plurale: 'sortings', genere: 'm' },
    documentoSchede: 'Learner record',
    presenze: {
      'non-impostato': 'Not set',
      presente: 'Present',
      assente: 'Absent',
      ritardo: 'Late',
      esonerato: 'Excused',
    },
    etichetteTelefono: {
      cellulare: 'mobile',
      casa: 'home',
      lavoro: 'work',
      centralino: 'switchboard',
      altro: 'other',
    },
    tipiAttivita: {
      'docenza-di-classe': 'Class teaching duties',
      introduzione: 'Introduction',
      spiegazione: 'Explanation',
      esercizio: 'Exercise',
      laboratorio: 'Lab',
      discussione: 'Discussion',
      gruppo: 'Group work',
      verifica: 'Test',
      ripasso: 'Revision',
      compito: 'Task',
      altro: 'Other',
    },
    raggruppamenti: {
      plenaria: 'Whole class',
      individuale: 'On their own',
      coppie: 'In pairs',
      gruppi: 'In groups',
    },
    tipiValutazione: {
      scritto: 'Written',
      orale: 'Oral',
      pratico: 'Practical',
      progetto: 'Project',
      compito: 'Homework',
      osservazione: 'Observation',
    },
    tipiOsservazione: {
      nota: 'Note',
      merito: 'Merit',
      disciplina: 'Discipline',
      compiti: 'Homework',
      materiale: 'Materials',
      colloquio: 'Meeting',
    },
    statiLezione: {
      pianificata: 'Planned',
      svolta: 'Held',
      annullata: 'Cancelled',
    },
    tipiConsegna: {
      compito: 'Task',
      studio: 'Study',
      materiale: 'Materials to bring',
      consegna: 'To hand in',
      preparazione: 'Preparation (mine)',
      amministrativo: 'Administrative',
      altro: 'Other',
    },
    categorieDocumento: {
      certificato: 'Certificate',
      autorizzazione: 'Authorisation',
      giustificazione: 'Excuse note',
      modulo: 'Form',
      altro: 'Other',
    },
    ruoliAllegato: {
      verifica: 'Test paper',
      soluzione: 'Solution',
      prova: 'Marked test',
      recupero: 'Resit paper',
      'recupero-soluzione': 'Resit solution',
    },
  },
})

/**
 * Tutti i nomi, in ogni lingua, della famiglia di fogli stampati una per
 * persona, più i nomi usati in passato (`prima`): per riconoscere i file già
 * sul disco. Una stampa non riconosciuta finirebbe fra i caricati, che non si
 * cancellano mai.
 */
export function nomiDelleSchede (prima: readonly string[]): string[] {
  return [...new Set([...lessico.tutte().map((l) => l.documentoSchede), ...prima])]
}
