// I testi di `tray.ts`: menu e suggerimento dell'icona. Il marchio «Regiclass»
// non si traduce e sta nel sorgente. Si contano le lezioni del calendario:
// «ore» in italiano, `lessico().lezione` nelle altre lingue.

import { catalogo, perNumero } from '../i18n/index.js'
import { plurale } from './text.js'

const it = {
  /** Le fasi dette dentro la riga di un'ora. */
  inCorso: 'in corso',
  annullata: 'annullata',
  /** I titoli dei sottomenu di un corso; il numero lo aggiunge il menu. */
  mucchi: {
    'in-corso': 'In corso',
    'da-chiudere': 'Da chiudere',
    prossime: 'Prossime',
    svolte: 'Svolte',
    annullate: 'Annullate',
  },
  oggi: 'oggi',
  ieri: 'ieri',
  domani: 'domani',
  finoAlle: (fine: string) => `fino alle ${fine}`,
  assenti: (quanti: number) => plurale(quanti, 'assente', 'assenti'),
  tuttiPresenti: 'tutti presenti',
  osservazioni: (quante: number) => plurale(quante, 'osservazione', 'osservazioni'),
  scalettaCorta: 'scaletta corta',
  senzaPiano: 'senza piano',
  pianoCompleto: 'piano completo',
  verifica: 'verifica',
  /** La riga spenta in cima al sottomenu di un corso. */
  riepilogo: {
    inCorso: (quante: number) => `${quante} in corso`,
    daChiudere: (quante: number) => `${quante} da chiudere`,
    prossime: (quante: number) => `${quante} in programma`,
    svolte: (quante: number) => `${quante} svolte`,
    annullate: (quante: number) => `${quante} annullate`,
  },
  nessunaOra: 'nessuna ora',
  daCompilare: 'Da compilare',
  prossima: 'Prossima',
  nienteDaChiudere: 'niente da chiudere',
  daChiudere: (quante: number) => plurale(quante, 'ora da chiudere', 'ore da chiudere'),
}

export const testi = catalogo(it, {
  de: {
    inCorso: 'läuft',
    annullata: 'ausgefallen',
    mucchi: {
      'in-corso': 'Laufend',
      'da-chiudere': 'Abzuschliessen',
      prossime: 'Nächste',
      svolte: 'Gehalten',
      annullate: 'Ausgefallen',
    },
    oggi: 'heute',
    ieri: 'gestern',
    domani: 'morgen',
    finoAlle: (fine) => `bis ${fine}`,
    assenti: (quanti) => `${quanti} abwesend`,
    tuttiPresenti: 'alle anwesend',
    osservazioni: (quante) => plurale(quante, 'Beobachtung', 'Beobachtungen'),
    scalettaCorta: 'Ablauf zu kurz',
    senzaPiano: 'ohne Plan',
    pianoCompleto: 'Plan vollständig',
    verifica: 'Prüfung',
    riepilogo: {
      inCorso: (quante) => `${quante} laufend`,
      daChiudere: (quante) => `${quante} abzuschliessen`,
      prossime: (quante) => `${quante} geplant`,
      svolte: (quante) => `${quante} gehalten`,
      annullate: (quante) => `${quante} ausgefallen`,
    },
    nessunaOra: 'keine Stunden',
    daCompilare: 'Auszufüllen',
    prossima: 'Als Nächstes',
    nienteDaChiudere: 'nichts abzuschliessen',
    daChiudere: (quante) =>
      `${quante} ${perNumero(quante, 'Stunde', 'Stunden')} abzuschliessen`,
  },
  fr: {
    inCorso: 'en cours',
    annullata: 'annulée',
    mucchi: {
      'in-corso': 'En cours',
      'da-chiudere': 'À clôturer',
      prossime: 'Prochaines',
      svolte: 'Données',
      annullate: 'Annulées',
    },
    oggi: 'aujourd’hui',
    ieri: 'hier',
    domani: 'demain',
    finoAlle: (fine) => `jusqu’à ${fine}`,
    assenti: (quanti) => plurale(quanti, 'absent', 'absents'),
    tuttiPresenti: 'tous présents',
    osservazioni: (quante) => plurale(quante, 'observation', 'observations'),
    scalettaCorta: 'déroulement trop court',
    senzaPiano: 'sans plan',
    pianoCompleto: 'plan complet',
    verifica: 'épreuve',
    riepilogo: {
      inCorso: (quante) => `${quante} en cours`,
      daChiudere: (quante) => `${quante} à clôturer`,
      prossime: (quante) => plurale(quante, 'prévue', 'prévues'),
      svolte: (quante) => plurale(quante, 'donnée', 'données'),
      annullate: (quante) => plurale(quante, 'annulée', 'annulées'),
    },
    nessunaOra: 'aucune leçon',
    daCompilare: 'À remplir',
    prossima: 'Prochaine',
    nienteDaChiudere: 'rien à clôturer',
    daChiudere: (quante) => plurale(quante, 'leçon à clôturer', 'leçons à clôturer'),
  },
  en: {
    inCorso: 'in progress',
    annullata: 'cancelled',
    mucchi: {
      'in-corso': 'In progress',
      'da-chiudere': 'To close',
      prossime: 'Coming up',
      svolte: 'Held',
      annullate: 'Cancelled',
    },
    oggi: 'today',
    ieri: 'yesterday',
    domani: 'tomorrow',
    finoAlle: (fine) => `until ${fine}`,
    assenti: (quanti) => `${quanti} absent`,
    tuttiPresenti: 'all present',
    osservazioni: (quante) => plurale(quante, 'observation', 'observations'),
    scalettaCorta: 'outline too short',
    senzaPiano: 'no plan',
    pianoCompleto: 'plan complete',
    verifica: 'test',
    riepilogo: {
      inCorso: (quante) => `${quante} in progress`,
      daChiudere: (quante) => `${quante} to close`,
      prossime: (quante) => `${quante} scheduled`,
      svolte: (quante) => `${quante} held`,
      annullate: (quante) => `${quante} cancelled`,
    },
    nessunaOra: 'no lessons',
    daCompilare: 'To fill in',
    prossima: 'Next',
    nienteDaChiudere: 'nothing to close',
    daChiudere: (quante) => plurale(quante, 'lesson to close', 'lessons to close'),
  },
})
