// I testi delle procedure di `assistente`. Gli esempi che nominano quel che si
// legge a schermo (campi della barra, pagine, schede) si scrivono come li
// mostra la pagina in quella lingua; dati e valori del contratto
// («DIC4a · Matematica», «corso.presenze») restano uguali. Si leggono al
// momento dell'uso (`titolo: () => …`), mai al caricamento.

import { catalogo } from '../../../i18n/index.js'

const it = {
  contesto: {
    titolo: 'Dice all’assistente su che pagina, che scheda e che filtri si sta lavorando',
    campo: 'Come si chiama il campo nella barra: «Corso», «Classe»',
    valore: 'Il valore come si legge a schermo: «DIC4a · Matematica»',
    id: 'L’id da passare agli attrezzi, quando ce n’è uno',
    valoreOpzione: 'Come si legge quella voce',
    idOpzione: 'L’id di quella voce, quando ne ha uno',
    opzioni: 'Che cosa si potrebbe scegliere al posto di quel che è scelto',
    vista: 'La pagina aperta',
    pagina: 'Come si chiama nella barra: «Lezione»',
    scheda: 'La scheda aperta dentro la pagina: «Appello»',
    sezione: 'La sezione aperta dentro la scheda: «Assistente»',
    scelte: 'Le scelte fatte nelle tendine in cima',
    filtri: 'Quel che la pagina sta restringendo',
    etichettaPeriodo: 'Come si legge nella tendina: «2° semestre», «Anno intero»',
    dal: 'Il primo giorno che conta: si passa come «dal»',
    al: 'L’ultimo giorno che conta: si passa come «al»',
    data: 'Il giorno che la pagina sta mostrando',
    oggi: 'Oggi: la pagina può benissimo non starlo mostrando',
    ricerca: 'La ricerca battuta nella pagina',
    cosa: 'Di che cosa è l’elenco: «corsi», «persone in formazione»',
    quanti: 'Quanti ne mostra in tutto',
    ids: 'Gli id mostrati, nell’ordine in cui si vedono',
    troncato: 'Vero se ne mostra più di quanti se ne sono mandati',
  },
  stacca: {
    titolo: 'Stacca l’assistente in una finestra sua, con la conversazione',
    procedura: 'Chi l’ha letto: «corso.presenze»',
    blocco: 'Un blocco impaginato: valori, tabella o elenco',
    ruolo: 'Chi ha detto questo turno',
    nomeAttrezzo: 'La procedura aperta, con il punto: «corso.presenze»',
    codice: 'Il codice dell’API, quando non è andata',
    messaggio: 'Perché non è andata, come si legge',
    guasto: 'Il servizio non ha risposto',
    idVisto: 'L’identificatore, come si passa a un attrezzo',
    nomeVisto: 'Come si legge: «Bernasconi Elia»',
    cosaVisto: 'Di che cosa è l’id: «allievo», «classe», «corso»',
    fermato: 'Chi ha chiesto ha smesso di aspettare',
    esaurito: 'Il modello ha finito le chiamate concesse',
    storia: 'La conversazione che si porta dietro',
    bozza: 'Quel che è battuto nel campo e non ancora mandato',
    visti: 'Quanti eventi di quel giro la finestra che consegna ha già ricevuto',
    busta: 'L’id della busta con cui quella pagina aveva chiesto',
    giro: 'La domanda ancora senza risposta, se se ne sta aspettando una',
  },
}

export const testi = catalogo(it, {
  de: {
    contesto: {
      titolo:
        'Sagt dem Assistenten, auf welcher Seite, in welchem Reiter und mit welchen Filtern ' +
        'gearbeitet wird',
      campo: 'Wie das Feld in der Leiste heisst: «Kurs», «Klasse»',
      valore: 'Der Wert, wie er am Bildschirm steht: «DIC4a · Matematica»',
      id: 'Die ID, die den Werkzeugen übergeben wird, falls es eine gibt',
      valoreOpzione: 'Wie dieser Eintrag zu lesen ist',
      idOpzione: 'Die ID dieses Eintrags, falls er eine hat',
      opzioni: 'Was man anstelle der aktuellen Auswahl wählen könnte',
      vista: 'Die geöffnete Seite',
      pagina: 'Wie sie in der Leiste heisst: «Stunde»',
      scheda: 'Der geöffnete Reiter innerhalb der Seite: «Präsenzkontrolle»',
      sezione: 'Der geöffnete Abschnitt innerhalb des Reiters: «Assistent»',
      scelte: 'Die Auswahl in den Menüs oben',
      filtri: 'Worauf die Seite gerade einschränkt',
      etichettaPeriodo: 'Wie es im Menü steht: «2. Semester», «Ganzes Jahr»',
      dal: 'Der erste Tag, der zählt: wird als «dal» übergeben',
      al: 'Der letzte Tag, der zählt: wird als «al» übergeben',
      data: 'Der Tag, den die Seite gerade zeigt',
      oggi: 'Heute: Die Seite zeigt ihn nicht unbedingt',
      ricerca: 'Die Suche, die auf der Seite eingegeben wurde',
      cosa: 'Wovon die Liste ist: «Kurse», «Lernende»',
      quanti: 'Wie viele sie insgesamt zeigt',
      ids: 'Die gezeigten IDs, in der Reihenfolge, in der sie zu sehen sind',
      troncato: 'Wahr, wenn sie mehr zeigt, als übermittelt wurden',
    },
    stacca: {
      titolo: 'Löst den Assistenten samt Gespräch in ein eigenes Fenster',
      procedura: 'Wer es gelesen hat: «corso.presenze»',
      blocco: 'Ein dargestellter Block: Werte, Tabelle oder Liste',
      ruolo: 'Wer diesen Gesprächsschritt gesagt hat',
      nomeAttrezzo: 'Die aufgerufene Prozedur, mit Punkt: «corso.presenze»',
      codice: 'Der Code der API, wenn es nicht geklappt hat',
      messaggio: 'Warum es nicht geklappt hat, in lesbarer Form',
      guasto: 'Der Dienst hat nicht geantwortet',
      idVisto: 'Die Kennung, so wie sie einem Werkzeug übergeben wird',
      nomeVisto: 'Wie man es liest: «Bernasconi Elia»',
      cosaVisto: 'Wozu die ID gehört: «allievo», «classe», «corso»',
      fermato: 'Die fragende Person hat aufgehört zu warten',
      esaurito: 'Das Modell hat die erlaubten Aufrufe aufgebraucht',
      storia: 'Das Gespräch, das mitgenommen wird',
      bozza: 'Was im Feld getippt und noch nicht gesendet ist',
      visti: 'Wie viele Ereignisse dieser Runde das übergebende Fenster schon erhalten hat',
      busta: 'Die ID des Umschlags, mit dem diese Seite gefragt hatte',
      giro: 'Die Frage, die noch keine Antwort hat, falls man auf eine wartet',
    },
  },
  fr: {
    contesto: {
      titolo:
        'Dit à l’assistant sur quelle page, quel onglet et avec quels filtres on travaille',
      campo: 'Comment s’appelle le champ dans la barre : « Cours », « Classe »',
      valore: 'La valeur telle qu’elle se lit à l’écran : « DIC4a · Matematica »',
      id: 'L’id à passer aux outils, quand il y en a un',
      valoreOpzione: 'Comment se lit cette entrée',
      idOpzione: 'L’id de cette entrée, quand elle en a un',
      opzioni: 'Ce qu’on pourrait choisir à la place de ce qui est choisi',
      vista: 'La page ouverte',
      pagina: 'Comment elle s’appelle dans la barre : « Leçon »',
      scheda: 'L’onglet ouvert sur la page : « Appel »',
      sezione: 'La section ouverte dans l’onglet : « Assistant »',
      scelte: 'Les choix faits dans les menus en haut',
      filtri: 'Ce que la page est en train de restreindre',
      etichettaPeriodo: 'Comment ça se lit dans le menu : « 2e semestre », « Année entière »',
      dal: 'Le premier jour qui compte : il se passe comme « dal »',
      al: 'Le dernier jour qui compte : il se passe comme « al »',
      data: 'Le jour que la page est en train de montrer',
      oggi: 'Aujourd’hui : la page peut très bien ne pas le montrer',
      ricerca: 'La recherche tapée sur la page',
      cosa: 'De quoi est faite la liste : « cours », « personnes en formation »',
      quanti: 'Combien elle en montre en tout',
      ids: 'Les id montrés, dans l’ordre où on les voit',
      troncato: 'Vrai si elle en montre plus qu’il n’en a été envoyé',
    },
    stacca: {
      titolo: 'Détache l’assistant dans sa propre fenêtre, avec la conversation',
      procedura: 'Qui l’a lu : « corso.presenze »',
      blocco: 'Un bloc mis en page : valeurs, tableau ou liste',
      ruolo: 'Qui a dit ce tour de parole',
      nomeAttrezzo: 'La procédure ouverte, avec le point : « corso.presenze »',
      codice: 'Le code de l’API, quand ça n’a pas marché',
      messaggio: 'Pourquoi ça n’a pas marché, tel que ça se lit',
      guasto: 'Le service n’a pas répondu',
      idVisto: 'L’identifiant, tel qu’on le passe à un outil',
      nomeVisto: 'Comment ça se lit : « Bernasconi Elia »',
      cosaVisto: 'À quoi appartient l’id : « allievo », « classe », « corso »',
      fermato: 'La personne qui a demandé a cessé d’attendre',
      esaurito: 'Le modèle a épuisé les appels accordés',
      storia: 'La conversation qu’on emporte',
      bozza: 'Ce qui est tapé dans le champ et pas encore envoyé',
      visti: 'Combien d’événements de ce tour la fenêtre qui transmet a déjà reçus',
      busta: 'L’id de l’enveloppe avec laquelle cette page avait demandé',
      giro: 'La question encore sans réponse, si on en attend une',
    },
  },
  en: {
    contesto: {
      titolo: 'Tells the assistant which page, tab and filters are being worked on',
      campo: 'What the field is called in the bar: “Course”, “Class”',
      valore: 'The value as it reads on screen: “DIC4a · Matematica”',
      id: 'The id to pass to the tools, when there is one',
      valoreOpzione: 'How that entry reads',
      idOpzione: 'The id of that entry, when it has one',
      opzioni: 'What could be chosen instead of what is chosen',
      vista: 'The open page',
      pagina: 'What it is called in the bar: “Lesson”',
      scheda: 'The tab open inside the page: “Attendance”',
      sezione: 'The section open inside the tab: “Assistant”',
      scelte: 'The choices made in the drop-down menus at the top',
      filtri: 'What the page is narrowing down',
      etichettaPeriodo: 'How it reads in the drop-down: “2nd semester”, “Whole year”',
      dal: 'The first day that counts: passed as “dal”',
      al: 'The last day that counts: passed as “al”',
      data: 'The day the page is showing',
      oggi: 'Today: the page may well not be showing it',
      ricerca: 'The search typed on the page',
      cosa: 'What the list is of: “courses”, “learners”',
      quanti: 'How many it shows in all',
      ids: 'The ids shown, in the order they appear',
      troncato: 'True if it shows more than were sent',
    },
    stacca: {
      titolo: 'Detaches the assistant into its own window, with the conversation',
      procedura: 'Who read it: “corso.presenze”',
      blocco: 'A laid-out block: values, table or list',
      ruolo: 'Who said this turn',
      nomeAttrezzo: 'The procedure opened, with the dot: “corso.presenze”',
      codice: 'The API code, when it did not work',
      messaggio: 'Why it did not work, as it reads',
      guasto: 'The service did not answer',
      idVisto: 'The identifier, as it is passed to a tool',
      nomeVisto: 'How it reads: “Bernasconi Elia”',
      cosaVisto: 'What the id is of: “allievo”, “classe”, “corso”',
      fermato: 'The person asking stopped waiting',
      esaurito: 'The model used up the calls allowed',
      storia: 'The conversation taken along',
      bozza: 'What is typed in the field and not yet sent',
      visti: 'How many events of that round the handing-over window has already received',
      busta: 'The id of the envelope that page had asked with',
      giro: 'The question still without an answer, if one is being waited for',
    },
  },
})
