// I testi comuni ai comandi del pannello (`commands.ts` e le sezioni in
// `commands/`): i riquadri, i motivi per cui un comando non si fa da qui e i
// comandi di Modifica, che legge anche `components/undoable.ts`. Il resto sta
// accanto alla sua sezione. La guida cita i nomi dei pulsanti fra
// virgolette: cambiandone uno va cambiato anche là, in tutte le lingue.

import { catalogo } from '#core/i18n/index.js'
import { plurale } from '#core/dominio/text.js'

const it = {
  /** I riquadri della riga delle azioni, e i gruppi del menu e della palette. */
  gruppi: {
    documento: 'Il documento',
    anno: 'L’anno',
    modifica: 'Modifica',
    finestra: 'La finestra',
    manutenzione: 'Manutenzione',
    adesso: 'Adesso',
    comeSiGuarda: 'Come si guarda',
    modificaLeOre: 'Modifica le lezioni',
    calendarioIcs: 'Calendario ICS',
    cheCosaSiGuarda: 'Che cosa si guarda',
    crea: 'Crea',
    statoDellOra: 'Stato della lezione',
    ora: 'La lezione',
    piano: 'Il piano',
    check: 'Il check',
    progetto: 'Il progetto',
    indirizzi: 'Indirizzi',
    elenco: 'Elenco',
    famiglie: 'Famiglie',
    classe: 'Classe',
    schermo: 'Lo schermo',
    sulloSchermo: 'Sullo schermo',
    comeSiVede: 'Come si vede',
    calendarioProiettato: 'Calendario proiettato',
    documentiDi: 'Documenti di',
    genera: 'Genera',
    chiLiRifa: 'Chi li rifà',
    posta: 'Posta',
  },
  // Perché un comando non si fa da qui.
  nonConQuelCheMostra: 'Non con quel che la pagina mostra adesso.',
  dallaSuaPagina: 'Si fa dalla sua pagina: aprila, e lo trovi nella barra.',
  // Modifica: «Annulla» lo legge anche `components/undoable.ts`.
  annulla: 'Annulla',
  annullaAiuto: 'Torna indietro dell’ultimo gesto fatto sul registro',
  annullaAiutoPassi: (passi: number) =>
    `Torna indietro dell’ultimo gesto fatto sul registro (${plurale(passi, 'passo', 'passi')})`,
  nienteDaAnnullare: 'Non c’è niente da annullare.',
  ripristina: 'Ripristina',
  ripristinaAiuto: 'Rifà il gesto appena annullato',
  ripristinaAiutoPassi: (passi: number) =>
    `Rifà il gesto appena annullato (${plurale(passi, 'passo', 'passi')})`,
  nienteDaRipristinare: 'Non c’è niente da ripristinare.',
}

export const testi = catalogo(it, {
  de: {
    gruppi: {
      documento: 'Das Dokument',
      anno: 'Das Schuljahr',
      modifica: 'Bearbeiten',
      finestra: 'Das Fenster',
      manutenzione: 'Wartung',
      adesso: 'Jetzt',
      comeSiGuarda: 'Ansicht',
      modificaLeOre: 'Stunden bearbeiten',
      calendarioIcs: 'ICS-Kalender',
      cheCosaSiGuarda: 'Was man sieht',
      crea: 'Erstellen',
      statoDellOra: 'Status der Stunde',
      ora: 'Die Stunde',
      piano: 'Der Plan',
      check: 'Der Check',
      progetto: 'Das Projekt',
      indirizzi: 'Adressen',
      elenco: 'Liste',
      famiglie: 'Familien',
      classe: 'Klasse',
      schermo: 'Der Bildschirm',
      sulloSchermo: 'Auf dem Bildschirm',
      comeSiVede: 'Darstellung',
      calendarioProiettato: 'Projizierter Kalender',
      documentiDi: 'Dokumente zu',
      genera: 'Erstellen',
      chiLiRifa: 'Wer sie neu erstellt',
      posta: 'E-Mail',
    },
    nonConQuelCheMostra: 'Nicht mit dem, was die Seite gerade zeigt.',
    dallaSuaPagina:
      'Das geht auf der eigenen Seite: Öffne sie, und du findest es in der Leiste.',
    annulla: 'Rückgängig',
    annullaAiuto: 'Macht den letzten Schritt im Klassenbuch rückgängig',
    annullaAiutoPassi: (passi) =>
      'Macht den letzten Schritt im Klassenbuch rückgängig ' +
      `(${plurale(passi, 'Schritt', 'Schritte')})`,
    nienteDaAnnullare: 'Es gibt nichts rückgängig zu machen.',
    ripristina: 'Wiederholen',
    ripristinaAiuto: 'Wiederholt den eben rückgängig gemachten Schritt',
    ripristinaAiutoPassi: (passi) =>
      `Wiederholt den eben rückgängig gemachten Schritt (${plurale(passi, 'Schritt', 'Schritte')})`,
    nienteDaRipristinare: 'Es gibt nichts zu wiederholen.',
  },
  fr: {
    gruppi: {
      documento: 'Le document',
      anno: 'L’année',
      modifica: 'Édition',
      finestra: 'La fenêtre',
      manutenzione: 'Maintenance',
      adesso: 'Maintenant',
      comeSiGuarda: 'Affichage',
      modificaLeOre: 'Modifier les leçons',
      calendarioIcs: 'Calendrier ICS',
      cheCosaSiGuarda: 'Ce qu’on regarde',
      crea: 'Créer',
      statoDellOra: 'État de la leçon',
      ora: 'La leçon',
      piano: 'Le plan',
      check: 'Le check',
      progetto: 'Le projet',
      indirizzi: 'Adresses',
      elenco: 'Liste',
      famiglie: 'Familles',
      classe: 'Classe',
      schermo: 'L’écran',
      sulloSchermo: 'À l’écran',
      comeSiVede: 'Présentation',
      calendarioProiettato: 'Calendrier projeté',
      documentiDi: 'Documents par',
      genera: 'Générer',
      chiLiRifa: 'Qui les refait',
      posta: 'Courrier',
    },
    nonConQuelCheMostra: 'Pas avec ce que la page montre maintenant.',
    dallaSuaPagina:
      'Cela se fait depuis sa page : ouvre-la, et tu le trouves dans la barre.',
    annulla: 'Annuler',
    annullaAiuto: 'Revient sur le dernier geste fait dans le registre',
    annullaAiutoPassi: (passi) =>
      `Revient sur le dernier geste fait dans le registre (${plurale(passi, 'pas', 'pas')})`,
    nienteDaAnnullare: 'Il n’y a rien à annuler.',
    ripristina: 'Rétablir',
    ripristinaAiuto: 'Refait le geste qui vient d’être annulé',
    ripristinaAiutoPassi: (passi) =>
      `Refait le geste qui vient d’être annulé (${plurale(passi, 'pas', 'pas')})`,
    nienteDaRipristinare: 'Il n’y a rien à rétablir.',
  },
  en: {
    gruppi: {
      documento: 'The document',
      anno: 'The year',
      modifica: 'Edit',
      finestra: 'The window',
      manutenzione: 'Maintenance',
      adesso: 'Now',
      comeSiGuarda: 'View',
      modificaLeOre: 'Edit lessons',
      calendarioIcs: 'ICS calendar',
      cheCosaSiGuarda: 'What you see',
      crea: 'Create',
      statoDellOra: 'Lesson status',
      ora: 'The lesson',
      piano: 'The plan',
      check: 'The check',
      progetto: 'The project',
      indirizzi: 'Addresses',
      elenco: 'List',
      famiglie: 'Families',
      classe: 'Class',
      schermo: 'The screen',
      sulloSchermo: 'On screen',
      comeSiVede: 'Display',
      calendarioProiettato: 'Projected calendar',
      documentiDi: 'Documents by',
      genera: 'Generate',
      chiLiRifa: 'Who remakes them',
      posta: 'Mail',
    },
    nonConQuelCheMostra: 'Not with what the page is showing now.',
    dallaSuaPagina:
      'This is done from its own page: open it, and you’ll find it in the bar.',
    annulla: 'Undo',
    annullaAiuto: 'Undoes the last step taken in the register',
    annullaAiutoPassi: (passi) =>
      `Undoes the last step taken in the register (${plurale(passi, 'step', 'steps')})`,
    nienteDaAnnullare: 'There is nothing to undo.',
    ripristina: 'Redo',
    ripristinaAiuto: 'Redoes the step just undone',
    ripristinaAiutoPassi: (passi) =>
      `Redoes the step just undone (${plurale(passi, 'step', 'steps')})`,
    nienteDaRipristinare: 'There is nothing to redo.',
  },
})
